In [1]:
import pandas as pd
import numpy as np
import re
from collections import Counter

In [2]:
data_DT = pd.read_csv('D:\OU\DoAn\DrugRecommandation\crawlData_DieuTri\Thuoc_DieuTri_data.csv', encoding='utf-8')

print(f"Kích thước dữ liệu ban đầu: {data_DT.shape}")
print(f"Số cột: {len(data_DT.columns)}")
print(f"Danh sách cột: {data_DT.columns.tolist()}")

data_DT

<>:1: SyntaxWarning: invalid escape sequence '\O'
<>:1: SyntaxWarning: invalid escape sequence '\O'
C:\Users\Admin\AppData\Local\Temp\ipykernel_29732\3257803002.py:1: SyntaxWarning: invalid escape sequence '\O'
  data_DT = pd.read_csv('D:\OU\DoAn\DrugRecommandation\crawlData_DieuTri\Thuoc_DieuTri_data.csv', encoding='utf-8')

Kích thước dữ liệu ban đầu: (1008, 248)
Số cột: 248
Danh sách cột: ['ten_thuoc', 'link', 'An toàn khi sử dụng', 'An toàn tiền lâm sàng', 'Atorvastatin', 'Bào chế và đóng gói', 'Bảo quản', 'Bảo quản thuốc GliritDHG như thế nào?', 'Bảo quản và sử dụng', 'Bệnh nhân suy gan', 'Bệnh nhân suy thận', 'Bệnh nhân uống rượu', 'Các thử nghiệm lâm sàng', 'Cho con bú', 'Chống chỉ định', 'Chú ý', 'Chú ý đề phòng', 'Chú ý đề phòng và thận trọng lúc dùng', 'Chỉ định', 'Chỉ định - Công dụng của thuốc hạ lipid máu Lipvar 20mg', 'Chỉ định cà công dụng', 'Chỉ định và công dụng', 'Chỉ định và liều dùng', 'Chỉ định/Công dụng', 'Chỉ định/công dụng', 'Chỉ định/công dụng Tagrisso', 'Chỉ\xa0định', 'Chống chỉ định', 'Chống chỉ định Tagrisso', 'Chống chỉ định khi sử dụng Lipvar 20mg', 'Chống chỉ định tuyệt đối', 'Chống chỉ định và thận trọng', 'Chống chỉ\xa0định', 'Các hướng dẫn đặc biệt về liều lượng', 'Các nghiên cứu lâm sàng', 'Các tác dụng phụ', 'Các tác dụng phụ hiếm gặp', 'Các tác dụng phụ khác', 'Các tác dụng phụ nghiêm trọng', 'Các tác dụng phụ sau khi tiếp thị', 'Các tác dụng phụ sau khi đưa ra thị trường', 'Các tác dụng phụ thường gặp', 'Các tác dụng phụ ít gặp hơn', 'Các đánh giá lâm sàng', 'Các đặc tính dược lực học', 'Các đặc tính dược động học', 'Các đặc điểm của V. Rohto', 'Cách dùng', 'Cách dùng Tagrisso', 'Cách sử dụng', 'Cách sử dụng thuốc', 'Cách sử dụng thuốc Glumeron', 'Có thai', 'Có thai và cho con bú', 'Có thai và nuôi con bú', 'Công thức', 'Cơ chế tác dụng', 'Cơ chế tác động', 'Cảnh báo', 'Cảnh báo thận trọng khi sử dụng thuốc Lipvar', 'Cảnh báo và thận trọng', 'Cảnh báo và thận trọng khi dùng thuốc', 'Cảnh báo và thận trọng khi sử dụng thuốc GliritDHG', 'Cảnh báo và thận trọng khi sử dụng thuốc Glumeron', 'Cảnh báo đặc biệt', 'Cảnh\xa0báo', 'Dược động học', 'Dược lâm sàng', 'Dược lý', 'Dược lý lâm sàng', 'Dược lý và cơ chế tác dụng', 'Dược lực', 'Dược lực học', 'Dược động học', 'Dược động học (dữ liệu nghiên cứu ở người lớn, trừ khi có ghi chú)', 'Dược động học:', 'Dạng bào chế', 'Dạng dùng', 'Dạng thuốc và hàm lượng', 'Dạng thuốc và hàm lượng', 'Dạng đóng gói', 'Dữ liệu an toàn tiền lâm sàng', 'Dữ liệu về tính an toàn tiền lâm sàng', 'Fluvastatin', 'Giới hạn sử dụng', 'Hiệu quả lâm sàng', 'Hoạt tính kháng khuẩn', 'Hướng dẫn cách sử trí ADR', 'Hướng dẫn cách xử trí ADR', 'Hướng dẫn sử dụng', 'Hướng dẫn sử dụng và bảo quản', 'Hạn dùng', 'Kinh nghiệm hậu mãi', 'Liêu lượng', 'Liều lượng và cách dùng', 'Liều dung', 'Liều dùng', 'Liều dùng cho người lớn', 'Liều dùng và cách dùng', 'Liều dùng và hướng dẫn sử dụng', 'Liều dùng/Hướng dẫn sử dụng', 'Liều dùng/hướng dẫn sử dụng', 'Liều dùng/hướng dẫn sử dụng Tagrisso', 'Liều lượng', 'Liều lượng & Cách dùng', 'Liều lượng & cách dùng', 'Liều lượng cho người lớn', 'Liều lượng cho trẻ em', 'Liều lượng dành cho người lớn', 'Liều lượng người lớn', 'Liều lượng và cách dùng', 'Liều lượng và cách sử dụng', 'Liều lượng, cách dùng', 'Liều thông thường', 'Lovastatin', 'Làm gì nếu bạn sử dụng GliritDHG quá liều?', 'Làm gì nếu bạn sử dụng Glumeron quá liều?', 'Lái xe', 'Lái xe và vận hành máy móc', 'Lúc có thai', 'Lúc nuôi con bú', 'Lưu ý khi bảo quản và sử dụng', 'Lưu ý khi sử dụng', 'Lưu ý khi sử dụng thuốc', 'Lạm dụng thuốc', 'Mang thai và cho con bú', 'Mang thai và cho con bú.', 'Mang thai và\xa0cho con bú', 'Mô tả', 'Nhiễm toan acid lactic', 'Nhà sản xuất', 'Nhóm dược lý', 'Nuôi con bú', 'Phân loại', 'Phân loại (US)/thai kỳ', 'Phân loại MIMS', 'Phân nhóm', 'Phòng bệnh bạch hầu', 'Phản ứng có hại', 'Phản ứng dị ứng', 'Phản ứng phụ', 'Phản ứng phụ của Tagrisso', 'Phản ứng truyền dịch', 'Phản\xa0ứng phụ', 'Phổ kháng khuẩn', 'Phổ tác dụng', 'Phụ nữ cho con bú', 'Phụ nữ có khả năng mang thai', 'Phụ nữ có thai', 'Phụ nữ có thai và cho con bú', 'Pravastatin', 'Qui chế', 'Quy chế', 'Quy cách đóng gói', 'Quá liều và xử trí', 'Quá liều', 'Quá liều và cách xử trí', 'Quá liều và xử trí', 'Quá liều và xử trí (xem thêm mục Hướng dẫn cách xử trí ADR)', 'Quá mẫn', 'Quá\xa0liều', 'Simvastatin', 'Sử dụng cho phụ nữ có thai và cho con bú', 'Sử dụng ở phụ nữ có thai và cho con bú', 'Sự kháng thuốc', 'Sự phụ thuộc về thể chất và tâm lý', 'Thai kỳ', 'Thành Phần', 'Thành phần', 'Thành phần Tagrisso', 'Thành phần cho 1 viên', 'Thành phần cho 100 g', 'Thành phần cho một viên', 'Thành phần công thức thuốc', 'Thành phần mỗi 100 ml', 'Thành phần mỗi 1000 ml', 'Thành phần mỗi viên', 'Thành phần thuốc', 'Thông tin qui chế', 'Thông tin thuốc', 'Thông tin thuốc GliritDHG', 'Thông tin thuốc Glumeron', 'Thận trọng', 'Thận trọng khi dùng', 'Thận trọng khi dùng Tagrisso', 'Thận trọng khi sử dụng', 'Thận trọng lúc dùng', 'Thời gian điều trị', 'Thời kỳ cho con bú', 'Thời kỳ mang thai', 'Thời kỳ mang thai và cho con bú', 'Thời kỳ mang thai và ở đàn ông', 'Triệu chứng cai nghiện opioid nghiêm trọng', 'Trình bày', 'Trình bày và đóng gói', 'Trình bày/Đóng gói', 'Trình bày/đóng gói', 'Tác dụng', 'Tác dụng không mong muốn', 'Tác dụng không mong muốn (ADR)', 'Tác dụng không mong muốn(ADR)', 'Tác dụng lý tưởng ít phổ biến', 'Tác dụng ngoài ý', 'Tác dụng ngoại ý', 'Tác dụng phụ', 'Tác dụng phụ hiếm gặp', 'Tác dụng phụ nghiêm trọng', 'Tác dụng phụ sau khi đưa ra thị trường', 'Tác dụng phụ thường gặp', 'Tác dụng phụ và xử trí', 'Tác dụng phụ về rối loạn tiêu hóa nghiêm trọng', 'Tác hại của việc lạm dụng thuốc', 'Tác động', 'Tên thương mại', 'Tính chất', 'Tương hợp - tương kỵ - độ ổn định', 'Tương kỵ', 'Tương tác dược động học', 'Tương tác', 'Tương tác của Tagrisso', 'Tương tác dược động học', 'Tương tác nghiêm trọng', 'Tương tác nhẹ', 'Tương tác thuốc', 'Tương tác thuốc.', 'Tương tác về dược lực học', 'Tương tác với các thuốc khác', 'Tương tác vừa phải', 'Tổng quan về tương tác thuốc', 'Ðiều trị giảm kali máu', 'Ðộ ổn định và bảo quản', 'Đau bụng dữ dội và/hoặc tiêu chảy', 'Điều trị ngoại trú', 'Điều trị nội trú', 'Đóng gói', 'Đảo ngược hiệu ứng apixaban', 'Đặc biệt cho trẻ sơ sinh', 'Đặc tính', 'Đặc tính dược lực', 'Đặc tính dược lực học', 'Đặc tính dược lực học và dược động học', 'Đặc tính dược động', 'Đặc tính dược động học', 'Để giảm tính độc với thận', 'Độ ổn định và bảo quản', 'Độc tính', 'Ảnh hưởng lâu dài', 'Ảnh hưởng độc với tế bào']

,ten_thuoc,link,An toàn khi sử dụng,An toàn tiền lâm sàng,Atorvastatin,Bào chế và đóng gói,Bảo quản,Bảo quản thuốc GliritDHG như thế nào?,Bảo quản và sử dụng,Bệnh nhân suy gan,...,Đặc tính dược lực,Đặc tính dược lực học,Đặc tính dược lực học và dược động học,Đặc tính dược động,Đặc tính dược động học,Để giảm tính độc với thận,Độ ổn định và bảo quản,Độc tính,Ảnh hưởng lâu dài,Ảnh hưởng độc với tế bào
0,Azelastine: thuốc điều trị viêm mũi,https://www.dieutri.vn/a/azelastine-thuoc-dieu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Axit acetohydroxamic: thuốc điều trị nhiễm trù...,https://www.dieutri.vn/a/axit-acetohydroxamic-...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Axalimogene Filolisbac: thuốc điều trị ung thư...,https://www.dieutri.vn/a/axalimogene-filolisba...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Avelumab: thuốc điều trị ung thư,https://www.dieutri.vn/a/avelumab-thuoc-dieu-t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Atovaquone Proguanil: thuốc điều trị sốt rét,https://www.dieutri.vn/a/atovaquone-proguanil-...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,Zymoplex,https://www.dieutri.vn/z/zymoplex,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004,Zyprexa,https://www.dieutri.vn/z/zyprexa,NaN,NaN,NaN,NaN,Bảo quản ở nhiệt độ 15 – 30 độ C. Thuốc nhạy c...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1005,Zytee RB,https://www.dieutri.vn/z/zytee-rb,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1006,Zyrtec,https://www.dieutri.vn/z/zyrtec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1007,Zidovudin,https://www.dieutri.vn/z/zidovudin,NaN,NaN,NaN,NaN,Bảo quản ở 15 – 25 độ C. Tránh ánh sáng.\nSau ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
print("Số lượng giá trị thiếu trên cột")
for col in data_DT.columns:
    print(f"{col}: {data_DT[col].isnull().sum()}")

Số lượng giá trị thiếu trên cột
ten_thuoc: 0
link: 0
An toàn khi sử dụng: 1007
An toàn tiền lâm sàng: 1006
Atorvastatin: 1007
Bào chế và đóng gói: 1007
Bảo quản: 855
Bảo quản thuốc GliritDHG như thế nào?: 1007
Bảo quản và sử dụng: 1007
Bệnh nhân suy gan: 1007
Bệnh nhân suy thận: 1007
Bệnh nhân uống rượu: 1007
Các thử nghiệm lâm sàng: 1007
Cho con bú: 1000
Chống chỉ định: 1007
Chú ý: 995
Chú ý đề phòng: 1006
Chú ý đề phòng và thận trọng lúc dùng: 1007
Chỉ định: 801
Chỉ định - Công dụng của thuốc hạ lipid máu Lipvar 20mg: 1007
Chỉ định cà công dụng: 1007
Chỉ định và công dụng: 946
Chỉ định và liều dùng: 1007
Chỉ định/Công dụng: 990
Chỉ định/công dụng: 983
Chỉ định/công dụng Tagrisso: 1007
Chỉ định: 971
Chống chỉ định: 69
Chống chỉ định Tagrisso: 1007
Chống chỉ định khi sử dụng Lipvar 20mg: 1007
Chống chỉ định tuyệt đối: 1007
Chống chỉ định và thận trọng: 1007
Chống chỉ định: 971
Các hướng dẫn đặc biệt về liều lượng: 1007
Các nghiên cứu lâm sàng: 1007
Các tác dụng phụ: 1003
Các tác dụng phụ hiếm gặp: 1001
Các tác dụng phụ khác: 1007
Các tác dụng phụ nghiêm trọng: 998
Các tác dụng phụ sau khi tiếp thị: 1006
Các tác dụng phụ sau khi đưa ra thị trường: 1007
Các tác dụng phụ thường gặp: 998
Các tác dụng phụ ít gặp hơn: 1007
Các đánh giá lâm sàng: 1007
Các đặc tính dược lực học: 1006
Các đặc tính dược động học: 1007
Các đặc điểm của V. Rohto: 1007
Cách dùng: 881
Cách dùng Tagrisso: 1007
Cách sử dụng: 1003
Cách sử dụng thuốc: 1006
Cách sử dụng thuốc Glumeron: 1007
Có thai: 997
Có thai và cho con bú: 985
Có thai và nuôi con bú: 1007
Công thức: 1007
Cơ chế tác dụng: 1001
Cơ chế tác động: 1006
Cảnh báo: 548
Cảnh báo thận trọng khi sử dụng thuốc Lipvar: 1007
Cảnh báo và thận trọng: 1007
Cảnh báo và thận trọng khi dùng thuốc: 1007
Cảnh báo và thận trọng khi sử dụng thuốc GliritDHG: 1007
Cảnh báo và thận trọng khi sử dụng thuốc Glumeron: 1007
Cảnh báo đặc biệt: 1007
Cảnh báo: 1005
Dược động học: 1007
Dược lâm sàng: 1007
Dược lý: 1005
Dược lý lâm sàng: 1005
Dược lý và cơ chế tác dụng: 943
Dược lực: 1006
Dược lực học: 869
Dược động học: 820
Dược động học (dữ liệu nghiên cứu ở người lớn, trừ khi có ghi chú): 1007
Dược động học:: 1006
Dạng bào chế: 1007
Dạng dùng: 1007
Dạng thuốc và hàm lượng: 1007
Dạng thuốc và hàm lượng: 888
Dạng đóng gói: 1007
Dữ liệu an toàn tiền lâm sàng: 1007
Dữ liệu về tính an toàn tiền lâm sàng: 1007
Fluvastatin: 1007
Giới hạn sử dụng: 1007
Hiệu quả lâm sàng: 1007
Hoạt tính kháng khuẩn: 1007
Hướng dẫn cách sử trí ADR: 1007
Hướng dẫn cách xử trí ADR: 911
Hướng dẫn sử dụng: 1006
Hướng dẫn sử dụng và bảo quản: 1007
Hạn dùng: 1005
Kinh nghiệm hậu mãi: 1007
Liêu lượng: 1007
Liều lượng và cách dùng: 1007
Liều dung: 1007
Liều dùng: 640
Liều dùng cho người lớn: 1007
Liều dùng và cách dùng: 1005
Liều dùng và hướng dẫn sử dụng: 1000
Liều dùng/Hướng dẫn sử dụng: 993
Liều dùng/hướng dẫn sử dụng: 985
Liều dùng/hướng dẫn sử dụng Tagrisso: 1007
Liều lượng: 649
Liều lượng & Cách dùng: 1004
Liều lượng & cách dùng: 1007
Liều lượng cho người lớn: 1004
Liều lượng cho trẻ em: 1007
Liều lượng dành cho người lớn: 1000
Liều lượng người lớn: 1007
Liều lượng và cách dùng: 877
Liều lượng và cách sử dụng: 1007
Liều lượng, cách dùng: 961
Liều thông thường: 1007
Lovastatin: 1007
Làm gì nếu bạn sử dụng GliritDHG quá liều?: 1007
Làm gì nếu bạn sử dụng Glumeron quá liều?: 1007
Lái xe: 1007
Lái xe và vận hành máy móc: 1007
Lúc có thai: 999
Lúc nuôi con bú: 999
Lưu ý khi bảo quản và sử dụng: 1007
Lưu ý khi sử dụng: 1006
Lưu ý khi sử dụng thuốc: 1007
Lạm dụng thuốc: 1007
Mang thai và cho con bú: 375
Mang thai và cho con bú.: 1007
Mang thai và cho con bú: 1004
Mô tả: 977
Nhiễm toan acid lactic: 1007
Nhà sản xuất: 876
Nhóm dược lý: 1007
Nuôi con bú: 1007
Phân loại: 991
Phân loại (US)/thai kỳ: 983
Phân loại MIMS: 1002
Phân nhóm: 1007
Phòng bệnh bạch hầu: 1007
Phản ứng có hại: 1007
Phản ứng dị ứng: 1007
Phản ứng phụ: 963
Phản ứng phụ của Tagrisso: 1007
Phản ứng truyền dịch: 1007
Phản ứng phụ: 972
Phổ kháng khuẩn: 1004
Phổ tác dụng: 1007
Phụ nữ cho con bú: 1006
Phụ nữ có khả năng mang thai: 1007
Phụ nữ có thai: 1006
Phụ nữ có thai và cho con bú: 1007
Pravastatin: 1007
Qui chế: 1006
Quy chế: 999
Quy cách đóng gói: 1007
Quá liều và xử trí: 1007
Quá liều: 917
Quá liều và cách xử trí: 1007
Quá liều và xử trí: 901
Quá liều và xử trí (xem thêm mục Hướng dẫn cách xử trí ADR): 1007
Quá mẫn: 1007
Quá liều: 1004
Simvastatin: 1007
Sử dụng cho phụ nữ có thai và cho con bú: 966
Sử dụng ở phụ nữ có thai và cho con bú: 957
Sự kháng thuốc: 1007
Sự phụ thuộc về thể chất và tâm lý: 1007
Thai kỳ: 1007
Thành Phần: 1007
Thành phần: 790
Thành phần Tagrisso: 1007
Thành phần cho 1 viên: 1006
Thành phần cho 100 g: 1007
Thành phần cho một viên: 1007
Thành phần công thức thuốc: 1007
Thành phần mỗi 100 ml: 1007
Thành phần mỗi 1000 ml: 1007
Thành phần mỗi viên: 1007
Thành phần thuốc: 1007
Thông tin qui chế: 1007
Thông tin thuốc: 1007
Thông tin thuốc GliritDHG: 1007
Thông tin thuốc Glumeron: 1007
Thận trọng: 186
Thận trọng khi dùng: 1007
Thận trọng khi dùng Tagrisso: 1007
Thận trọng khi sử dụng: 1007
Thận trọng lúc dùng: 1002
Thời gian điều trị: 1007
Thời kỳ cho con bú: 928
Thời kỳ mang thai: 929
Thời kỳ mang thai và cho con bú: 1007
Thời kỳ mang thai và ở đàn ông: 1007
Triệu chứng cai nghiện opioid nghiêm trọng: 1007
Trình bày: 1006
Trình bày và đóng gói: 907
Trình bày/Đóng gói: 992
Trình bày/đóng gói: 980
Tác dụng: 992
Tác dụng không mong muốn: 1001
Tác dụng không mong muốn (ADR): 891
Tác dụng không mong muốn(ADR): 1007
Tác dụng lý tưởng ít phổ biến: 1007
Tác dụng ngoài ý: 1007
Tác dụng ngoại ý: 952
Tác dụng phụ: 311
Tác dụng phụ hiếm gặp: 1006
Tác dụng phụ nghiêm trọng: 1007
Tác dụng phụ sau khi đưa ra thị trường: 1006
Tác dụng phụ thường gặp: 1005
Tác dụng phụ và xử trí: 1007
Tác dụng phụ về rối loạn tiêu hóa nghiêm trọng: 1007
Tác hại của việc lạm dụng thuốc: 1007
Tác động: 1007
Tên thương mại: 956
Tính chất: 1001
Tương hợp - tương kỵ - độ ổn định: 1007
Tương kỵ: 955
Tương tác dược động học: 1007
Tương tác: 848
Tương tác của Tagrisso: 1007
Tương tác dược động học: 1007
Tương tác nghiêm trọng: 1007
Tương tác nhẹ: 1007
Tương tác thuốc: 444
Tương tác thuốc.: 1007
Tương tác về dược lực học: 1007
Tương tác với các thuốc khác: 965
Tương tác vừa phải: 1007
Tổng quan về tương tác thuốc: 1002
Ðiều trị giảm kali máu: 1007
Ðộ ổn định và bảo quản: 1007
Đau bụng dữ dội và/hoặc tiêu chảy: 1007
Điều trị ngoại trú: 1007
Điều trị nội trú: 1007
Đóng gói: 1006
Đảo ngược hiệu ứng apixaban: 1007
Đặc biệt cho trẻ sơ sinh: 1007
Đặc tính: 1007
Đặc tính dược lực: 1006
Đặc tính dược lực học: 1004
Đặc tính dược lực học và dược động học: 1007
Đặc tính dược động: 1006
Đặc tính dược động học: 1004
Để giảm tính độc với thận: 1007
Độ ổn định và bảo quản: 946
Độc tính: 1006
Ảnh hưởng lâu dài: 1007
Ảnh hưởng độc với tế bào: 1007

In [4]:
counts = data_DT.count().reset_index()
counts.columns = ["Tên thuộc tính", "Số lượng dữ liệu"]

bins = [0, 10, 100, 500, 1008]
labels = ["1-10", "11-100", "101-500", "501-1008"]
counts["Nhóm dữ liệu"] = pd.cut(counts["Số lượng dữ liệu"], bins=bins, labels=labels, include_lowest=True, right=True)

summary_by_group = (
    counts.groupby("Nhóm dữ liệu")
    .agg(
        columns=("Tên thuộc tính", "count"),
        examples = ("Tên thuộc tính", lambda x: ", ".join(x))
    )
    .reset_index()
)
summary_by_group

C:\Users\Admin\AppData\Local\Temp\ipykernel_29732\1622601011.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  counts.groupby("Nhóm dữ liệu")

  Nhóm dữ liệu  columns                                           examples
0         1-10      194  An toàn khi sử dụng, An toàn tiền lâm sàng, At...
1       11-100       31  Chú ý, Chỉ định và công dụng, Chỉ định/Công dụ...
2      101-500       16  Bảo quản, Chỉ định, Cách dùng, Cảnh báo, Dược ...
3     501-1008        7  ten_thuoc, link, Chống chỉ định, Mang thai và ...

In [5]:
import unicodedata
def normalize_text(s):
    return unicodedata.normalize("NFC", s).lower().strip()
    
cols_chi_dinh = [ col for col in data_DT.columns if "chỉ định" in normalize_text(col) and "chống chỉ định" not in normalize_text(col) ]

cols_chong_chi_dinh = [ col for col in data_DT.columns if "chống chỉ định" in normalize_text(col) ]

cols_chi_dinh = list(set(cols_chi_dinh) - set(cols_chong_chi_dinh))

cols_lieu_dung = [col for col in data_DT.columns if 'liều dùng' in col.lower()]

cols_tac_dung_phu = [col for col in data_DT.columns if 'tác dụng phụ' in col.lower()]

cols_thanh_phan = [col for col in data_DT.columns if 'thành phần' in col.lower()]

cols_cach_dung = [col for col in data_DT.columns if 'cách dùng' in col.lower()]

cols_tuong_tac_thuoc = [col for col in data_DT.columns if 'tương tác thuốc' in col.lower()]

cols_than_trong = [col for col in data_DT.columns if 'thận trọng' in col.lower()]

cols_canh_bao = [col for col in data_DT.columns if 'cảnh báo' in col.lower()]

cols_mang_thai_cho_con_bu = [col for col in data_DT.columns if 'mang thai' in col.lower() or 'cho con bú' in col.lower()]

# Hiển thị số cột tìm được
print("Số cột tìm được theo từ khóa:")
print(f"Chỉ định: {len(cols_chi_dinh)} cột")
print(f"Chống chỉ định: {len(cols_chong_chi_dinh)} cột")
print(f"Liều dùng: {len(cols_lieu_dung)} cột")
print(f"Tác dụng phụ: {len(cols_tac_dung_phu)} cột")
print(f"Thành phần: {len(cols_thanh_phan)} cột")
print(f"Cách dùng: {len(cols_cach_dung)} cột")
print(f"Tương tác thuốc: {len(cols_tuong_tac_thuoc)} cột")
print(f"Thận trọng: {len(cols_than_trong)} cột")
print(f"Cảnh báo: {len(cols_canh_bao)} cột")
print(f"Mang thai và cho con bú: {len(cols_mang_thai_cho_con_bu)} cột")

Số cột tìm được theo từ khóa:
Chỉ định: 8 cột
Chống chỉ định: 6 cột
Liều dùng: 8 cột
Tác dụng phụ: 15 cột
Thành phần: 11 cột
Cách dùng: 8 cột
Tương tác thuốc: 3 cột
Thận trọng: 12 cột
Cảnh báo: 7 cột
Mang thai và cho con bú: 14 cột

In [6]:
groups = {
    "1. Chỉ định": cols_chi_dinh,
    "2. Chống chỉ định": cols_chong_chi_dinh,
    "3. Liều dùng": cols_lieu_dung,
    "4. Tác dụng phụ": cols_tac_dung_phu,
    "5. Thành phần": cols_thanh_phan,
    "6. Cách dùng": cols_cach_dung,
    "7. Tương tác thuốc": cols_tuong_tac_thuoc,
    "8. Thận trọng": cols_than_trong,
    "9. Cảnh báo": cols_canh_bao,
    "10. Mang thai và cho con bú": cols_mang_thai_cho_con_bu,
}

print("=== CHI TIẾT CÁC CỘT ĐƯỢC NHÓM THEO TỪ KHÓA ===")
for group_name, cols in groups.items():
    print(f"\n{group_name}: {len(cols)} cột")
    if cols:
        for i, col in enumerate(cols, start=1):
            print(f"   {i}. {col}")
    else:
        print("Không tìm thấy cột nào")

total_grouped_cols = sum(len(cols) for cols in groups.values())
print("\n=== TỔNG KẾT ===")
print(f"Tổng số cột được nhóm: {total_grouped_cols}/{len(data_DT.columns)} cột")
print(f"Tỷ lệ cột được nhóm: {(total_grouped_cols/len(data_DT.columns))*100:.1f}%")

all_grouped_cols = sum(groups.values(), [])  # nối tất cả list lại
ungrouped_cols = [col for col in data_DT.columns if col not in all_grouped_cols]

print(f"\nCác cột không được nhóm ({len(ungrouped_cols)} cột):")
for i, col in enumerate(ungrouped_cols[:10], start=1):  # Chỉ hiển thị 10 cột đầu
    print(f"   {i}. {col}")
if len(ungrouped_cols) > 10:
    print(f"...và {len(ungrouped_cols)-10} cột khác")

=== CHI TIẾT CÁC CỘT ĐƯỢC NHÓM THEO TỪ KHÓA ===

1. Chỉ định: 8 cột
   1. Chỉ định/Công dụng
   2. Chỉ định
   3. Chỉ định và công dụng
   4. Chỉ định - Công dụng của thuốc hạ lipid máu Lipvar 20mg
   5. Chỉ định/công dụng
   6. Chỉ định và liều dùng
   7. Chỉ định cà công dụng
   8. Chỉ định/công dụng Tagrisso

2. Chống chỉ định: 6 cột
   1. Chống chỉ định
   2. Chống chỉ định
   3. Chống chỉ định Tagrisso
   4. Chống chỉ định khi sử dụng Lipvar 20mg
   5. Chống chỉ định tuyệt đối
   6. Chống chỉ định và thận trọng

3. Liều dùng: 8 cột
   1. Chỉ định và liều dùng
   2. Liều dùng
   3. Liều dùng cho người lớn
   4. Liều dùng và cách dùng
   5. Liều dùng và hướng dẫn sử dụng
   6. Liều dùng/Hướng dẫn sử dụng
   7. Liều dùng/hướng dẫn sử dụng
   8. Liều dùng/hướng dẫn sử dụng Tagrisso

4. Tác dụng phụ: 15 cột
   1. Các tác dụng phụ
   2. Các tác dụng phụ hiếm gặp
   3. Các tác dụng phụ khác
   4. Các tác dụng phụ nghiêm trọng
   5. Các tác dụng phụ sau khi tiếp thị
   6. Các tác dụng phụ sau khi đưa ra thị trường
   7. Các tác dụng phụ thường gặp
   8. Các tác dụng phụ ít gặp hơn
   9. Tác dụng phụ
   10. Tác dụng phụ hiếm gặp
   11. Tác dụng phụ nghiêm trọng
   12. Tác dụng phụ sau khi đưa ra thị trường
   13. Tác dụng phụ thường gặp
   14. Tác dụng phụ và xử trí
   15. Tác dụng phụ về rối loạn tiêu hóa nghiêm trọng

5. Thành phần: 11 cột
   1. Thành Phần
   2. Thành phần
   3. Thành phần Tagrisso
   4. Thành phần cho 1 viên
   5. Thành phần cho 100 g
   6. Thành phần cho một viên
   7. Thành phần công thức thuốc
   8. Thành phần mỗi 100 ml
   9. Thành phần mỗi 1000 ml
   10. Thành phần mỗi viên
   11. Thành phần thuốc

6. Cách dùng: 8 cột
   1. Cách dùng
   2. Cách dùng Tagrisso
   3. Liều lượng và cách dùng
   4. Liều dùng và cách dùng
   5. Liều lượng & Cách dùng
   6. Liều lượng & cách dùng
   7. Liều lượng và cách dùng
   8. Liều lượng, cách dùng

7. Tương tác thuốc: 3 cột
   1. Tương tác thuốc
   2. Tương tác thuốc.
   3. Tổng quan về tương tác thuốc

8. Thận trọng: 12 cột
   1. Chú ý đề phòng và thận trọng lúc dùng
   2. Chống chỉ định và thận trọng
   3. Cảnh báo thận trọng khi sử dụng thuốc Lipvar
   4. Cảnh báo và thận trọng
   5. Cảnh báo và thận trọng khi dùng thuốc
   6. Cảnh báo và thận trọng khi sử dụng thuốc GliritDHG
   7. Cảnh báo và thận trọng khi sử dụng thuốc Glumeron
   8. Thận trọng
   9. Thận trọng khi dùng
   10. Thận trọng khi dùng Tagrisso
   11. Thận trọng khi sử dụng
   12. Thận trọng lúc dùng

9. Cảnh báo: 7 cột
   1. Cảnh báo
   2. Cảnh báo thận trọng khi sử dụng thuốc Lipvar
   3. Cảnh báo và thận trọng
   4. Cảnh báo và thận trọng khi dùng thuốc
   5. Cảnh báo và thận trọng khi sử dụng thuốc GliritDHG
   6. Cảnh báo và thận trọng khi sử dụng thuốc Glumeron
   7. Cảnh báo đặc biệt

10. Mang thai và cho con bú: 14 cột
   1. Cho con bú
   2. Có thai và cho con bú
   3. Mang thai và cho con bú
   4. Mang thai và cho con bú.
   5. Mang thai và cho con bú
   6. Phụ nữ cho con bú
   7. Phụ nữ có khả năng mang thai
   8. Phụ nữ có thai và cho con bú
   9. Sử dụng cho phụ nữ có thai và cho con bú
   10. Sử dụng ở phụ nữ có thai và cho con bú
   11. Thời kỳ cho con bú
   12. Thời kỳ mang thai
   13. Thời kỳ mang thai và cho con bú
   14. Thời kỳ mang thai và ở đàn ông

=== TỔNG KẾT ===
Tổng số cột được nhóm: 92/248 cột
Tỷ lệ cột được nhóm: 37.1%

Các cột không được nhóm (164 cột):
   1. ten_thuoc
   2. link
   3. An toàn khi sử dụng
   4. An toàn tiền lâm sàng
   5. Atorvastatin
   6. Bào chế và đóng gói
   7. Bảo quản
   8. Bảo quản thuốc GliritDHG như thế nào?
   9. Bảo quản và sử dụng
   10. Bệnh nhân suy gan
...và 154 cột khác

In [7]:
data_DT['Chỉ định'] = data_DT[cols_chi_dinh].apply(lambda row:'\n'.join(row.dropna()), axis=1)
data_DT['Chống chỉ định'] = data_DT[cols_chong_chi_dinh].apply(lambda row:'\n'.join(row.dropna()), axis=1)
data_DT['Tác dụng phụ'] = data_DT[cols_tac_dung_phu].apply(lambda row:'\n'.join(row.dropna()), axis=1)
data_DT['Tương tác thuốc'] = data_DT[cols_tuong_tac_thuoc].apply(lambda row:'\n'.join(row.dropna()), axis=1)
data_DT['Liều dùng'] = data_DT[cols_lieu_dung].apply(lambda row:'\n'.join(row.dropna()), axis=1)
data_DT['Cách dùng'] = data_DT[cols_cach_dung].apply(lambda row:'\n'.join(row.dropna()), axis=1)
data_DT['Thận trọng'] = data_DT[cols_than_trong].apply(lambda row:'\n'.join(row.dropna()), axis=1)
data_DT['Thành phần'] = data_DT[cols_thanh_phan].apply(lambda row:'\n'.join(row.dropna()), axis=1)
data_DT['Cảnh báo'] = data_DT[cols_canh_bao].apply(lambda row:'\n'.join(row.dropna()), axis=1)
data_DT['Mang thai và cho con bú'] = data_DT[cols_mang_thai_cho_con_bu].apply(lambda row:'\n'.join(row.dropna()), axis=1)


data_DT.dropna(axis=1, how='all', inplace=True) #Loại bỏ các cột có giá trị trống hoàn toàn

print(f"Kích thước sau khi gộp cột: {data_DT.shape}")
grouped_columns = ['Chỉ định', 'Chống chỉ định', 'Tác dụng phụ', 'Tương tác thuốc', 
                  'Liều dùng', 'Cách dùng', 'Thận trọng', 'Thành phần', 'Cảnh báo', 
                  'Mang thai và cho con bú']

data_DT.head(10)

Kích thước sau khi gộp cột: (1008, 248)

,ten_thuoc,link,An toàn khi sử dụng,An toàn tiền lâm sàng,Atorvastatin,Bào chế và đóng gói,Bảo quản,Bảo quản thuốc GliritDHG như thế nào?,Bảo quản và sử dụng,Bệnh nhân suy gan,...,Đặc tính dược lực,Đặc tính dược lực học,Đặc tính dược lực học và dược động học,Đặc tính dược động,Đặc tính dược động học,Để giảm tính độc với thận,Độ ổn định và bảo quản,Độc tính,Ảnh hưởng lâu dài,Ảnh hưởng độc với tế bào
0,Azelastine: thuốc điều trị viêm mũi,https://www.dieutri.vn/a/azelastine-thuoc-dieu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Axit acetohydroxamic: thuốc điều trị nhiễm trù...,https://www.dieutri.vn/a/axit-acetohydroxamic-...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Axalimogene Filolisbac: thuốc điều trị ung thư...,https://www.dieutri.vn/a/axalimogene-filolisba...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Avelumab: thuốc điều trị ung thư,https://www.dieutri.vn/a/avelumab-thuoc-dieu-t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Atovaquone Proguanil: thuốc điều trị sốt rét,https://www.dieutri.vn/a/atovaquone-proguanil-...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Atracurium: thuốc điều trị giãn cơ khi phẫu th...,https://www.dieutri.vn/a/atracurium-thuoc-dieu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Atropine Pralidoxime: thuốc điều trị ngộ độc p...,https://www.dieutri.vn/a/atropine-pralidoxime-...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Atomoxetine: thuốc điều trị tăng động giảm chú ý,https://www.dieutri.vn/a/atomoxetine-thuoc-die...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Atezolizumab: thuốc điều trị ung thư,https://www.dieutri.vn/a/atezolizumab-thuoc-di...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Ataluren: thuốc điều trị chứng loạn dưỡng cơ,https://www.dieutri.vn/a/ataluren-thuoc-dieu-t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
data_DT.rename(columns={'ten_thuoc': 'Tên thuốc'}, inplace=True)
main_cols = ['Tên thuốc','link','Chỉ định', 'Chống chỉ định', 'Tác dụng phụ', 'Tương tác thuốc', 'Liều dùng', 'Cách dùng', 'Thận trọng', 'Thành phần', 'Cảnh báo', 'Mang thai và cho con bú']

existing_main_cols = [col for col in main_cols if col in data_DT.columns]
print(f"Các cột được giữ lại: {existing_main_cols}")

data_DT_cleaned = data_DT[existing_main_cols].copy()
print(f"Kích thước sau khi chọn cột chính: {data_DT_cleaned.shape}")

data_DT_cleaned

Các cột được giữ lại: ['Tên thuốc', 'link', 'Chỉ định', 'Chống chỉ định', 'Tác dụng phụ', 'Tương tác thuốc', 'Liều dùng', 'Cách dùng', 'Thận trọng', 'Thành phần', 'Cảnh báo', 'Mang thai và cho con bú']
Kích thước sau khi chọn cột chính: (1008, 12)

,Tên thuốc,link,Chỉ định,Chống chỉ định,Tác dụng phụ,Tương tác thuốc,Liều dùng,Cách dùng,Thận trọng,Thành phần,Cảnh báo,Mang thai và cho con bú
0,Azelastine: thuốc điều trị viêm mũi,https://www.dieutri.vn/a/azelastine-thuoc-dieu...,,Quá mẫn đã được ghi nhận.\n,Các tác dụng phụ thường gặp\nVị đắng trong miệ...,Azelastine có tương tác nghiêm trọng với các l...,"Thuốc xịt mũi\n0,1% (137mcg / lần xịt).\n0,15%...",,Có thể gây suy nhược thần kinh trung ương / bu...,,,Dữ liệu hạn chế từ kinh nghiệm sau khi đưa thu...
1,Axit acetohydroxamic: thuốc điều trị nhiễm trù...,https://www.dieutri.vn/a/axit-acetohydroxamic-...,,Quá mẫn cảm.\nBệnh nhân thích nghi với phẫu th...,Tác dụng phụ thường gặp\nĐau đầu nhẹ; 48 giờ đ...,Axit acetohydroxamic không có tương tác nghiêm...,,,Luôn sử dụng cùng với điều trị kháng sinh thíc...,,Thuốc này chứa axit acetohydroxamic. Không dùn...,Không sử dụng axit acetohydroxamic trong thai ...
2,Axalimogene Filolisbac: thuốc điều trị ung thư...,https://www.dieutri.vn/a/axalimogene-filolisba...,,Không có thông tin.\n,Mệt mỏi.\nỚn lạnh.\nSốt.\nBuồn nôn.\nĐau đầu.\...,Axalimogene filolisbac đang trong quá trình th...,Axalimogene filolisbac đang trong quá trình th...,,Không có thông tin.\n,,Thuốc này chứa axalimogene filolisbac. Không d...,Axalimogene filolisbac đang trong quá trình th...
3,Avelumab: thuốc điều trị ung thư,https://www.dieutri.vn/a/avelumab-thuoc-dieu-t...,,Không có.\n,Viêm tụy.\nViêm cơ tim.\nViêm cơ.\nSuy tim sun...,Avelumab không có tương tác nghiêm trọng được ...,Thuốc tiêm: 20mg / ml (lọ đơn liều 200mg / 10m...,,Độc tính trên phôi thai có thể xảy ra dựa trên...,,Thuốc này có chứa avelumab. Không dùng Bavenci...,"Dựa trên cơ chế hoạt động của nó, có thể gây h..."
4,Atovaquone Proguanil: thuốc điều trị sốt rét,https://www.dieutri.vn/a/atovaquone-proguanil-...,,Quá mẫn cảm.\nDự phòng ở người suy thận nặng (...,"Không có.\n\nĐau dạ dày,\nĂn mất ngon,\nMệt mỏ...",Atovaquone / Proguanil có những tương tác nghi...,,,Sử dụng thuốc này không là một phương pháp chữ...,,,Thận trọng khi sử dụng nếu lợi ích mang lại nh...
...,...,...,...,...,...,...,...,...,...,...,...,...
1003,Zymoplex,https://www.dieutri.vn/z/zymoplex,Điều trị triệu chứng các rối loạn khó tiêu.\n,,,,,"Uống 4 - 6 viên/ngày, chia làm 2 - 3 lần, uống...",,"Mỗi viên chứa:\nCác enzyme tiêu hóa: 186,5 mg\...",,
1004,Zyprexa,https://www.dieutri.vn/z/zyprexa,Olanzapine dùng để điều trị tấn công và điều t...,Chống chỉ định dùng olanzapine ở người bệnh đã...,Thường gặp (> 10%)\nNhững tác dụng không mong ...,Khả năng những thuốc khác ảnh hưởng đến Olanza...,,Liều khuyên dùng khởi đầu của olanzapine là 10...,Những bệnh kèm theo\nOlanzapine có hoạt tính k...,Mỗi viên chứa:\nOlanzapine: 5mg; 10mg.\nTá dượ...,,
1005,Zytee RB,https://www.dieutri.vn/z/zytee-rb,"Dùng làm giảm đau răng, viêm lưỡi, viêm miệng,...",Tăng cảm với benzalkonium chloride hay choline...,,Chưa có báo cáo.\n,,Chấm xoa nhẹ lên vùng bị tổn thương. Có thể lặ...,Không nuốt số lượng lớn.\n,Choline salicylate: 9%.\nBenzalkonium chloride...,,
1006,Zyrtec,https://www.dieutri.vn/z/zyrtec,Điều trị triệu chứng các biểu hiện dị ứng đườn...,Quá mẫn với thuốc. Suy thận.\n,"Các rối loạn nhẹ đường tiêu hóa, khô miệng, ch...",,,Dạng viên 10 mg: dùng cho người lớn và trẻ em ...,,1 viên : Cétirizine dichlorhydrate10 mg.\n1ml:...,,C tirizine được bài tiết qua sữa mẹ dưới dạng ...
1007,Zidovudin,https://www.dieutri.vn/z/zidovudin,"Ðiều trị người nhiễm HIV, có số tế bào CD4 dướ...",Quá mẫn cảm với zidovudin có nguy hiểm đến tín...,"Thiếu máu hồng cầu khổng lồ, giảm bạch cầu hạt...",,,Nhiễm HIV có triệu chứng hoặc không\nTrẻ em từ...,Với người suy giảm chức năng gan hoặc thận.\nC...,,,Phụ nữ bị nhiễm HIV không nên cho con bú để tr...

In [9]:
def clean_text_data(df):
    def clean_text(text):
        if pd.isna(text) or text == 'nan':
            return np.nan
        text = str(text)
        text = re.sub(r'<[^>]+>', '', text) # Loại bỏ HTML tags
        text = re.sub(r'[\n\r\t]+', ' ', text)  # Chuẩn hóa khoảng trắng
        text = re.sub(r'\s+', ' ', text)
        # Loại bỏ ký tự đặc biệt (giữ dấu câu cơ bản)
        text = re.sub(r'[^\w\s\.,;:!?\-\(\)\[\]\/\+\%°]', '', text, flags=re.UNICODE)
        text = re.sub(r'\.{2,}', '.', text) # Chuẩn hóa dấu câu
        text = re.sub(r',{2,}', ',', text)
        text = text.strip()
        
        return text if text and len(text) > 3 else np.nan
    
    text_columns = [col for col in df.columns if col not in ['Tên thuốc', 'link']]
    
    print(f"Làm sạch {len(text_columns)} cột văn bản...")
    
    for col in text_columns:
        if col in df.columns:
            print(f"  - Đang làm sạch cột: {col}")
            df[col] = df[col].apply(clean_text)
    
    print("Đã hoàn thành việc làm sạch dữ liệu văn bản!")
    return df

data_DT_text_cleaned = clean_text_data(data_DT_cleaned)

Làm sạch 10 cột văn bản...
  - Đang làm sạch cột: Chỉ định
  - Đang làm sạch cột: Chống chỉ định

  - Đang làm sạch cột: Tác dụng phụ
  - Đang làm sạch cột: Tương tác thuốc
  - Đang làm sạch cột: Liều dùng
  - Đang làm sạch cột: Cách dùng
  - Đang làm sạch cột: Thận trọng
  - Đang làm sạch cột: Thành phần
  - Đang làm sạch cột: Cảnh báo
  - Đang làm sạch cột: Mang thai và cho con bú
Đã hoàn thành việc làm sạch dữ liệu văn bản!

In [10]:
def finalize_dataset(df):
    initial_rows = len(df)# Xóa hàng không có tên thuốc
    df = df.dropna(subset=['Tên thuốc'])
    removed_rows = initial_rows - len(df)
    if removed_rows > 0:
        print(f"Đã xóa {removed_rows} hàng không có tên thuốc")
    

    empty_columns = df.columns[df.isnull().all()].tolist()# Xóa cột hoàn toàn trống
    if empty_columns:
        df = df.drop(columns=empty_columns)
        print(f"Đã xóa {len(empty_columns)} cột hoàn toàn trống: {empty_columns}")
    
    priority_columns = [
        'Tên thuốc', 'link', 'Chỉ định', 'Thành phần', 
        'Liều dùng', 'Cách dùng', 'Tác dụng phụ',
        'Chống chỉ định', 'Thận trọng', 'Cảnh báo',
        'Tương tác thuốc', 'Mang thai và cho con bú'
    ]
    
    existing_priority = [col for col in priority_columns if col in df.columns]
    other_columns = [col for col in df.columns if col not in existing_priority]
    final_order = existing_priority + other_columns
    
    df = df[final_order]
    
    print(f"Kích thước cuối cùng: {df.shape}")
    print(f"\nCác cột trong dataset cuối:")
    for i, col in enumerate(df.columns):
        data_count = df[col].count()
        missing_pct = df[col].isnull().sum() / len(df) * 100
        print(f"  {i+1:2d}. {col:<30} ({data_count:4d} giá trị, {missing_pct:.1f}% thiếu)")
    
    return df

data_DT_final = finalize_dataset(data_DT_text_cleaned)

Kích thước cuối cùng: (1008, 12)

Các cột trong dataset cuối:
   1. Tên thuốc                      (1008 giá trị, 0.0% thiếu)
   2. link                           (1008 giá trị, 0.0% thiếu)
   3. Chỉ định                       ( 316 giá trị, 68.7% thiếu)
   4. Thành phần                     ( 229 giá trị, 77.3% thiếu)
   5. Liều dùng                      ( 420 giá trị, 58.3% thiếu)
   6. Cách dùng                      ( 313 giá trị, 68.9% thiếu)
   7. Tác dụng phụ                   ( 716 giá trị, 29.0% thiếu)
   8. Chống chỉ định                 ( 944 giá trị, 6.3% thiếu)
   9. Thận trọng                     ( 838 giá trị, 16.9% thiếu)
  10. Cảnh báo                       ( 466 giá trị, 53.8% thiếu)
  11. Tương tác thuốc                ( 567 giá trị, 43.8% thiếu)
  12. Mang thai và cho con bú        ( 847 giá trị, 16.0% thiếu)

In [11]:
def summarize_preprocessing(df_original, df_final):
    print(f"\nSo sánh trước và sau:")
    print(f"Kích thước ban đầu: {df_original.shape}")
    print(f"Kích thước cuối cùng: {df_final.shape}")
    print(f"Giảm {df_original.shape[1] - df_final.shape[1]} cột")
    print(f"Giảm {df_original.shape[0] - df_final.shape[0]} hàng")
    
    print(f"\nChất lượng dữ liệu:")
    total_cells_final = df_final.shape[0] * df_final.shape[1]
    missing_cells_final = df_final.isnull().sum().sum()
    completion_rate = ((total_cells_final - missing_cells_final) / total_cells_final) * 100
    print(f"Tỷ lệ hoàn thiện dữ liệu: {completion_rate:.2f}%")
    
    print(f"\nCác cột chính trong dữ liệu cuối:")
    for i, col in enumerate(df_final.columns):
        data_count = df_final[col].count()
        print(f"{i+1:2d}. {col:<30} ({data_count:4d} giá trị)")
    
    return df_final

Data_DT_processed = summarize_preprocessing(data_DT, data_DT_final)
print(f"\nDữ liệu sau khi xử lý:")
Data_DT_processed

So sánh trước và sau:
Kích thước ban đầu: (1008, 248)
Kích thước cuối cùng: (1008, 12)
Giảm 236 cột
Giảm 0 hàng

Chất lượng dữ liệu:
Tỷ lệ hoàn thiện dữ liệu: 63.43%

Các cột chính trong dữ liệu cuối:
 1. Tên thuốc                      (1008 giá trị)
 2. link                           (1008 giá trị)
 3. Chỉ định                       ( 316 giá trị)
 4. Thành phần                     ( 229 giá trị)
 5. Liều dùng                      ( 420 giá trị)
 6. Cách dùng                      ( 313 giá trị)
 7. Tác dụng phụ                   ( 716 giá trị)
 8. Chống chỉ định                 ( 944 giá trị)
 9. Thận trọng                     ( 838 giá trị)
10. Cảnh báo                       ( 466 giá trị)
11. Tương tác thuốc                ( 567 giá trị)
12. Mang thai và cho con bú        ( 847 giá trị)

Dữ liệu sau khi xử lý:

,Tên thuốc,link,Chỉ định,Thành phần,Liều dùng,Cách dùng,Tác dụng phụ,Chống chỉ định,Thận trọng,Cảnh báo,Tương tác thuốc,Mang thai và cho con bú
0,Azelastine: thuốc điều trị viêm mũi,https://www.dieutri.vn/a/azelastine-thuoc-dieu...,NaN,NaN,"Thuốc xịt mũi 0,1% (137mcg / lần xịt). 0,15% (...",NaN,Các tác dụng phụ thường gặp Vị đắng trong miện...,Quá mẫn đã được ghi nhận.,Có thể gây suy nhược thần kinh trung ương / bu...,NaN,Azelastine có tương tác nghiêm trọng với các l...,Dữ liệu hạn chế từ kinh nghiệm sau khi đưa thu...
1,Axit acetohydroxamic: thuốc điều trị nhiễm trù...,https://www.dieutri.vn/a/axit-acetohydroxamic-...,NaN,NaN,NaN,NaN,Tác dụng phụ thường gặp Đau đầu nhẹ; 48 giờ đầ...,Quá mẫn cảm. Bệnh nhân thích nghi với phẫu thu...,Luôn sử dụng cùng với điều trị kháng sinh thíc...,Thuốc này chứa axit acetohydroxamic. Không dùn...,Axit acetohydroxamic không có tương tác nghiêm...,Không sử dụng axit acetohydroxamic trong thai ...
2,Axalimogene Filolisbac: thuốc điều trị ung thư...,https://www.dieutri.vn/a/axalimogene-filolisba...,NaN,NaN,Axalimogene filolisbac đang trong quá trình th...,NaN,Mệt mỏi. Ớn lạnh. Sốt. Buồn nôn. Đau đầu. Hạ h...,Không có thông tin.,Không có thông tin.,Thuốc này chứa axalimogene filolisbac. Không d...,Axalimogene filolisbac đang trong quá trình th...,Axalimogene filolisbac đang trong quá trình th...
3,Avelumab: thuốc điều trị ung thư,https://www.dieutri.vn/a/avelumab-thuoc-dieu-t...,NaN,NaN,Thuốc tiêm: 20mg / ml (lọ đơn liều 200mg / 10m...,NaN,Viêm tụy. Viêm cơ tim. Viêm cơ. Suy tim sung h...,Không có.,Độc tính trên phôi thai có thể xảy ra dựa trên...,Thuốc này có chứa avelumab. Không dùng Bavenci...,Avelumab không có tương tác nghiêm trọng được ...,"Dựa trên cơ chế hoạt động của nó, có thể gây h..."
4,Atovaquone Proguanil: thuốc điều trị sốt rét,https://www.dieutri.vn/a/atovaquone-proguanil-...,NaN,NaN,NaN,NaN,"Không có. Đau dạ dày, Ăn mất ngon, Mệt mỏi, Ng...",Quá mẫn cảm. Dự phòng ở người suy thận nặng (C...,Sử dụng thuốc này không là một phương pháp chữ...,NaN,Atovaquone / Proguanil có những tương tác nghi...,Thận trọng khi sử dụng nếu lợi ích mang lại nh...
...,...,...,...,...,...,...,...,...,...,...,...,...
1003,Zymoplex,https://www.dieutri.vn/z/zymoplex,Điều trị triệu chứng các rối loạn khó tiêu.,"Mỗi viên chứa: Các enzyme tiêu hóa: 186,5 mg D...",NaN,"Uống 4 - 6 viên/ngày, chia làm 2 - 3 lần, uống...",NaN,NaN,NaN,NaN,NaN,NaN
1004,Zyprexa,https://www.dieutri.vn/z/zyprexa,Olanzapine dùng để điều trị tấn công và điều t...,Mỗi viên chứa: Olanzapine: 5mg; 10mg. Tá dược:...,NaN,Liều khuyên dùng khởi đầu của olanzapine là 10...,Thường gặp ( 10%) Những tác dụng không mong mu...,Chống chỉ định dùng olanzapine ở người bệnh đã...,Những bệnh kèm theo Olanzapine có hoạt tính kh...,NaN,Khả năng những thuốc khác ảnh hưởng đến Olanza...,NaN
1005,Zytee RB,https://www.dieutri.vn/z/zytee-rb,"Dùng làm giảm đau răng, viêm lưỡi, viêm miệng,...",Choline salicylate: 9%. Benzalkonium chloride:...,NaN,Chấm xoa nhẹ lên vùng bị tổn thương. Có thể lặ...,NaN,Tăng cảm với benzalkonium chloride hay choline...,Không nuốt số lượng lớn.,NaN,Chưa có báo cáo.,NaN
1006,Zyrtec,https://www.dieutri.vn/z/zyrtec,Điều trị triệu chứng các biểu hiện dị ứng đườn...,1 viên : Cétirizine dichlorhydrate10 mg. 1ml: ...,NaN,Dạng viên 10 mg: dùng cho người lớn và trẻ em ...,"Các rối loạn nhẹ đường tiêu hóa, khô miệng, ch...",Quá mẫn với thuốc. Suy thận.,NaN,NaN,NaN,C tirizine được bài tiết qua sữa mẹ dưới dạng ...
1007,Zidovudin,https://www.dieutri.vn/z/zidovudin,"Ðiều trị người nhiễm HIV, có số tế bào CD4 dướ...",NaN,NaN,Nhiễm HIV có triệu chứng hoặc không Trẻ em từ ...,"Thiếu máu hồng cầu khổng lồ, giảm bạch cầu hạt...",Quá mẫn cảm với zidovudin có nguy hiểm đến tín...,Với người suy giảm chức năng gan hoặc thận. Cầ...,NaN,NaN,Phụ nữ bị nhiễm HIV không nên cho con bú để tr...

In [12]:
# Data_DT_processed.to_csv('DieuTri_processed.csv', index=False, encoding='utf-8')