In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
ankhang_df = pd.read_csv(r'D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_AnKhang\ankhang_medicines_data_full.csv', encoding='utf-8-sig')
print(f"Số dòng: {ankhang_df.shape[0]}, Số cột: {ankhang_df.shape[1]}")
ankhang_df.info()
ankhang_df.head()

Số dòng: 2193, Số cột: 20
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2193 entries, 0 to 2192
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_thuoc            2139 non-null   object
 1   gia                  538 non-null    object
 2   hinh_anh             2102 non-null   object
 3   cong_dung_tom_tat    2139 non-null   object
 4   thanh_phan_chinh     2050 non-null   object
 5   doi_tuong            1817 non-null   object
 6   thuong_hieu          2137 non-null   object
 7   noi_san_xuat         2139 non-null   object
 8   dang_bao_che         2138 non-null   object
 9   han_dung             2119 non-null   object
 10  thanh_phan_chi_tiet  2131 non-null   object
 11  cong_dung_chi_tiet   2102 non-null   object
 12  cach_dung            2117 non-null   object
 13  chong_chi_dinh       2099 non-null   object
 14  tac_dung_phu         2042 non-null   object
 15  luu_y                925 non-null    object
 16  url                  2193 non-null   object
 17  category             2073 non-null   object
 18  drug_type            2073 non-null   object
 19  error                54 non-null     object
dtypes: object(20)
memory usage: 342.8+ KB

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type,error
0,"Timi Roitin trị viêm dây thần kinh, thoái hóa ...",528.000₫,https://cdn.tgdd.vn/Products/Images/10053/1304...,"Bổ sung vitamin nhóm B, điều trị viêm dây thần...","Chondroitin, Vitamin B5, Fursultiamine, Vitami...",Người lớn,Phil Inter Pharma,Việt Nam,Viên nang mềm,36 tháng kể từ ngày sản xuất,"Hoạt chất: Chondroitin sulfate natri 90mg, Nic...",- Bổ sung các vitamin nhóm B trong các trường ...,Người lớn: Uống 1 viên/ngày.\n- Quá liều\nDùng...,- Quá mẫn với bất cứ thành phần nào của thuốc....,TIMIROITIN thường được dung nạp tốt khi dùng ở...,- Thận trọng khi sử dụng\n- Khi sử dụng nicoti...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
1,B Complex C bổ sung vitamin nhóm B và vitamin ...,800₫,https://cdn.tgdd.vn/Products/Images/10053/1295...,Dự phòng & bổ sung khi thiếu hụt các vitamin n...,"Vitamin PP, Vitamin C, Vitamin B6, Vitamin B2,...",NaN,Vidipha,Việt Nam,Viên nang cứng,24 tháng kể từ ngày sản xuất,"Hoạt chất: Vitamin B1 15mg, Vitamin B2 10mg, V...",B Complex C dự phòng và bổ sung thiếu hụt các ...,Liều lượng: Trung bình: 1 - 2 viên/ngày.\nCách...,Dị ứng với một trong các thành phần của thuốc....,Dùng liều cao nước tiểu sẽ có màu vàng nhạt (d...,- Thận trọng khi sử dụng\nKhi sử dụng nicotina...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
3,Vitamin PP 50 Pharmedic ngăn ngừa thiếu nicoti...,12.000₫,https://cdn.tgdd.vn/Products/Images/10053/1533...,Bổ sung vào khẩu phần ăn để ngăn ngừa thiếu hụ...,Vitamin PP,Người lớn và trẻ em trên 5 tuổi,Pharmedic,Việt Nam,Viên nén,NaN,Nicotinamid 50mg.\nTá dược 1 viên.,Vitamin PP 50 giúp bổ sung vào khẩu phần ăn để...,"Người lớn: mỗi lần 1 - 2 viên, ngày 3 lần.\nTr...","- Dị ứng với nicotinamid.\n- Bệnh gan nặng, lo...",NaN,- Thận trọng khi sử dụng\nNgười có tiền sử loé...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
4,"Agi-Calci bổ sung canxi, trị loãng xương (20 v...",150.000₫,https://cdn.tgdd.vn/Products/Images/10053/2463...,Bổ sung calci khi thiếu hay tăng nhu cầu calci...,"Calci cacbonat, Vitamin D3",NaN,Agimexpharm,Việt Nam,Viên nén bao phim,24 tháng kể từ ngày sản xuất,Mỗi viên nén bao phim chứa:\nHoạt chất: Calci ...,- Agi-Calci bổ sung calci trong các trường hợp...,Uống thuốc buổi sáng hoặc buổi trưa theo liều ...,"- Tăng calci huyết, calci niệu, sỏi calci, suy...",- Dùng thuốc chứa muối calci qua đường uống có...,- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN

In [3]:
# Kiểm tra các dòng còn thiếu category
category_missing = ankhang_df[ankhang_df['category'].isnull()]
print(f"Số dòng thiếu category: {category_missing.shape[0]}")
category_missing.head()

Số dòng thiếu category: 120

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type,error
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-tri-ung-...,NaN,NaN,Message: no such element: Unable to locate ele...
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...

In [4]:
# Kiểm tra số dòng có trùng url
duplicate_urls = ankhang_df[ankhang_df.duplicated(subset=['url'], keep=False)]
print(f"Số dòng có trùng url: {duplicate_urls.shape[0]}")
duplicate_urls.head()

Số dòng có trùng url: 424

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type,error
0,"Timi Roitin trị viêm dây thần kinh, thoái hóa ...",528.000₫,https://cdn.tgdd.vn/Products/Images/10053/1304...,"Bổ sung vitamin nhóm B, điều trị viêm dây thần...","Chondroitin, Vitamin B5, Fursultiamine, Vitami...",Người lớn,Phil Inter Pharma,Việt Nam,Viên nang mềm,36 tháng kể từ ngày sản xuất,"Hoạt chất: Chondroitin sulfate natri 90mg, Nic...",- Bổ sung các vitamin nhóm B trong các trường ...,Người lớn: Uống 1 viên/ngày.\n- Quá liều\nDùng...,- Quá mẫn với bất cứ thành phần nào của thuốc....,TIMIROITIN thường được dung nạp tốt khi dùng ở...,- Thận trọng khi sử dụng\n- Khi sử dụng nicoti...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
1,B Complex C bổ sung vitamin nhóm B và vitamin ...,800₫,https://cdn.tgdd.vn/Products/Images/10053/1295...,Dự phòng & bổ sung khi thiếu hụt các vitamin n...,"Vitamin PP, Vitamin C, Vitamin B6, Vitamin B2,...",NaN,Vidipha,Việt Nam,Viên nang cứng,24 tháng kể từ ngày sản xuất,"Hoạt chất: Vitamin B1 15mg, Vitamin B2 10mg, V...",B Complex C dự phòng và bổ sung thiếu hụt các ...,Liều lượng: Trung bình: 1 - 2 viên/ngày.\nCách...,Dị ứng với một trong các thành phần của thuốc....,Dùng liều cao nước tiểu sẽ có màu vàng nhạt (d...,- Thận trọng khi sử dụng\nKhi sử dụng nicotina...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
3,Vitamin PP 50 Pharmedic ngăn ngừa thiếu nicoti...,12.000₫,https://cdn.tgdd.vn/Products/Images/10053/1533...,Bổ sung vào khẩu phần ăn để ngăn ngừa thiếu hụ...,Vitamin PP,Người lớn và trẻ em trên 5 tuổi,Pharmedic,Việt Nam,Viên nén,NaN,Nicotinamid 50mg.\nTá dược 1 viên.,Vitamin PP 50 giúp bổ sung vào khẩu phần ăn để...,"Người lớn: mỗi lần 1 - 2 viên, ngày 3 lần.\nTr...","- Dị ứng với nicotinamid.\n- Bệnh gan nặng, lo...",NaN,- Thận trọng khi sử dụng\nNgười có tiền sử loé...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
4,"Agi-Calci bổ sung canxi, trị loãng xương (20 v...",150.000₫,https://cdn.tgdd.vn/Products/Images/10053/2463...,Bổ sung calci khi thiếu hay tăng nhu cầu calci...,"Calci cacbonat, Vitamin D3",NaN,Agimexpharm,Việt Nam,Viên nén bao phim,24 tháng kể từ ngày sản xuất,Mỗi viên nén bao phim chứa:\nHoạt chất: Calci ...,- Agi-Calci bổ sung calci trong các trường hợp...,Uống thuốc buổi sáng hoặc buổi trưa theo liều ...,"- Tăng calci huyết, calci niệu, sỏi calci, suy...",- Dùng thuốc chứa muối calci qua đường uống có...,- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN

In [5]:
# Loại bỏ những dòng có lỗi (cột error có dữ liệu)
error_rows = ankhang_df[ankhang_df['error'].notnull()]
print(f"Số dòng có lỗi: {error_rows.shape[0]}")
error_rows.head()

Số dòng có lỗi: 54

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type,error
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-tri-ung-...,NaN,NaN,Message: no such element: Unable to locate ele...
106,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...
124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,NaN,NaN,Message: no such element: Unable to locate ele...

In [6]:
# Loại bỏ những dòng có lỗi
ankhang_df_cleaned = ankhang_df[ankhang_df['error'].isnull()]
print(f"Số dòng sau khi loại bỏ lỗi: {ankhang_df_cleaned.shape[0]}")
ankhang_df_cleaned.head()

Số dòng sau khi loại bỏ lỗi: 2139

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type,error
0,"Timi Roitin trị viêm dây thần kinh, thoái hóa ...",528.000₫,https://cdn.tgdd.vn/Products/Images/10053/1304...,"Bổ sung vitamin nhóm B, điều trị viêm dây thần...","Chondroitin, Vitamin B5, Fursultiamine, Vitami...",Người lớn,Phil Inter Pharma,Việt Nam,Viên nang mềm,36 tháng kể từ ngày sản xuất,"Hoạt chất: Chondroitin sulfate natri 90mg, Nic...",- Bổ sung các vitamin nhóm B trong các trường ...,Người lớn: Uống 1 viên/ngày.\n- Quá liều\nDùng...,- Quá mẫn với bất cứ thành phần nào của thuốc....,TIMIROITIN thường được dung nạp tốt khi dùng ở...,- Thận trọng khi sử dụng\n- Khi sử dụng nicoti...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
1,B Complex C bổ sung vitamin nhóm B và vitamin ...,800₫,https://cdn.tgdd.vn/Products/Images/10053/1295...,Dự phòng & bổ sung khi thiếu hụt các vitamin n...,"Vitamin PP, Vitamin C, Vitamin B6, Vitamin B2,...",NaN,Vidipha,Việt Nam,Viên nang cứng,24 tháng kể từ ngày sản xuất,"Hoạt chất: Vitamin B1 15mg, Vitamin B2 10mg, V...",B Complex C dự phòng và bổ sung thiếu hụt các ...,Liều lượng: Trung bình: 1 - 2 viên/ngày.\nCách...,Dị ứng với một trong các thành phần của thuốc....,Dùng liều cao nước tiểu sẽ có màu vàng nhạt (d...,- Thận trọng khi sử dụng\nKhi sử dụng nicotina...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
3,Vitamin PP 50 Pharmedic ngăn ngừa thiếu nicoti...,12.000₫,https://cdn.tgdd.vn/Products/Images/10053/1533...,Bổ sung vào khẩu phần ăn để ngăn ngừa thiếu hụ...,Vitamin PP,Người lớn và trẻ em trên 5 tuổi,Pharmedic,Việt Nam,Viên nén,NaN,Nicotinamid 50mg.\nTá dược 1 viên.,Vitamin PP 50 giúp bổ sung vào khẩu phần ăn để...,"Người lớn: mỗi lần 1 - 2 viên, ngày 3 lần.\nTr...","- Dị ứng với nicotinamid.\n- Bệnh gan nặng, lo...",NaN,- Thận trọng khi sử dụng\nNgười có tiền sử loé...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
4,"Agi-Calci bổ sung canxi, trị loãng xương (20 v...",150.000₫,https://cdn.tgdd.vn/Products/Images/10053/2463...,Bổ sung calci khi thiếu hay tăng nhu cầu calci...,"Calci cacbonat, Vitamin D3",NaN,Agimexpharm,Việt Nam,Viên nén bao phim,24 tháng kể từ ngày sản xuất,Mỗi viên nén bao phim chứa:\nHoạt chất: Calci ...,- Agi-Calci bổ sung calci trong các trường hợp...,Uống thuốc buổi sáng hoặc buổi trưa theo liều ...,"- Tăng calci huyết, calci niệu, sỏi calci, suy...",- Dùng thuốc chứa muối calci qua đường uống có...,- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
5,Vitamin B1 Mekophar 250mg trị các bệnh thiếu v...,7.000₫,https://cdn.tgdd.vn/Products/Images/10053/1535...,"Điều trị các bệnh do thiếu B1, suy nhược cơ th...",NaN,NaN,Mekophar,Việt Nam,Viên nén bao đường,36 tháng kể từ ngày sản xuất,Hoạt chất: Thiamine nitrate (vitamin B1) 250mg...,- Điều trị các bệnh do thiếu vitamin B1 như: b...,- Theo chỉ dẫn của bác sĩ.\n- Người lớn: uống ...,Quá mẫn với một trong các thành phần của thuốc.,"- Tác dụng phụ rất hiếm khi xảy ra như: ngứa, ...",- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN

In [8]:
# Hoặc xem chi tiết một url cụ thể
sample_url = duplicate_urls['url'].iloc[1]
ankhang_df_cleaned[ankhang_df_cleaned['url'] == sample_url]

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type,error
1,B Complex C bổ sung vitamin nhóm B và vitamin ...,800₫,https://cdn.tgdd.vn/Products/Images/10053/1295...,Dự phòng & bổ sung khi thiếu hụt các vitamin n...,"Vitamin PP, Vitamin C, Vitamin B6, Vitamin B2,...",NaN,Vidipha,Việt Nam,Viên nang cứng,24 tháng kể từ ngày sản xuất,"Hoạt chất: Vitamin B1 15mg, Vitamin B2 10mg, V...",B Complex C dự phòng và bổ sung thiếu hụt các ...,Liều lượng: Trung bình: 1 - 2 viên/ngày.\nCách...,Dị ứng với một trong các thành phần của thuốc....,Dùng liều cao nước tiểu sẽ có màu vàng nhạt (d...,- Thận trọng khi sử dụng\nKhi sử dụng nicotina...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
1970,B Complex C bổ sung vitamin nhóm B và vitamin ...,800₫,https://cdn.tgdd.vn/Products/Images/10053/1295...,Dự phòng & bổ sung khi thiếu hụt các vitamin n...,"Vitamin PP, Vitamin C, Vitamin B6, Vitamin B2,...",NaN,Vidipha,Việt Nam,Viên nang cứng,24 tháng kể từ ngày sản xuất,"Hoạt chất: Vitamin B1 15mg, Vitamin B2 10mg, V...",B Complex C dự phòng và bổ sung thiếu hụt các ...,Liều lượng: Trung bình: 1 - 2 viên/ngày.\nCách...,Dị ứng với một trong các thành phần của thuốc....,Dùng liều cao nước tiểu sẽ có màu vàng nhạt (d...,- Thận trọng khi sử dụng\nKhi sử dụng nicotina...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN

In [9]:
# Giữ dòng đầu tiên của mỗi url trùng lặp
ankhang_df_cleaned = ankhang_df_cleaned.drop_duplicates(subset=['url'], keep='first')
print(f"Số dòng sau khi loại bỏ trùng url: {ankhang_df_cleaned.shape[0]}")

Số dòng sau khi loại bỏ trùng url: 1969

In [11]:
ankhang_df_cleaned.info()
ankhang_df_cleaned.head()

<class 'pandas.core.frame.DataFrame'>
Index: 1969 entries, 0 to 2180
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_thuoc            1969 non-null   object
 1   gia                  453 non-null    object
 2   hinh_anh             1945 non-null   object
 3   cong_dung_tom_tat    1969 non-null   object
 4   thanh_phan_chinh     1899 non-null   object
 5   doi_tuong            1705 non-null   object
 6   thuong_hieu          1967 non-null   object
 7   noi_san_xuat         1969 non-null   object
 8   dang_bao_che         1968 non-null   object
 9   han_dung             1952 non-null   object
 10  thanh_phan_chi_tiet  1964 non-null   object
 11  cong_dung_chi_tiet   1938 non-null   object
 12  cach_dung            1953 non-null   object
 13  chong_chi_dinh       1937 non-null   object
 14  tac_dung_phu         1887 non-null   object
 15  luu_y                851 non-null    object
 16  url                  1969 non-null   object
 17  category             1921 non-null   object
 18  drug_type            1921 non-null   object
 19  error                0 non-null      object
dtypes: object(20)
memory usage: 323.0+ KB

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type,error
0,"Timi Roitin trị viêm dây thần kinh, thoái hóa ...",528.000₫,https://cdn.tgdd.vn/Products/Images/10053/1304...,"Bổ sung vitamin nhóm B, điều trị viêm dây thần...","Chondroitin, Vitamin B5, Fursultiamine, Vitami...",Người lớn,Phil Inter Pharma,Việt Nam,Viên nang mềm,36 tháng kể từ ngày sản xuất,"Hoạt chất: Chondroitin sulfate natri 90mg, Nic...",- Bổ sung các vitamin nhóm B trong các trường ...,Người lớn: Uống 1 viên/ngày.\n- Quá liều\nDùng...,- Quá mẫn với bất cứ thành phần nào của thuốc....,TIMIROITIN thường được dung nạp tốt khi dùng ở...,- Thận trọng khi sử dụng\n- Khi sử dụng nicoti...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
1,B Complex C bổ sung vitamin nhóm B và vitamin ...,800₫,https://cdn.tgdd.vn/Products/Images/10053/1295...,Dự phòng & bổ sung khi thiếu hụt các vitamin n...,"Vitamin PP, Vitamin C, Vitamin B6, Vitamin B2,...",NaN,Vidipha,Việt Nam,Viên nang cứng,24 tháng kể từ ngày sản xuất,"Hoạt chất: Vitamin B1 15mg, Vitamin B2 10mg, V...",B Complex C dự phòng và bổ sung thiếu hụt các ...,Liều lượng: Trung bình: 1 - 2 viên/ngày.\nCách...,Dị ứng với một trong các thành phần của thuốc....,Dùng liều cao nước tiểu sẽ có màu vàng nhạt (d...,- Thận trọng khi sử dụng\nKhi sử dụng nicotina...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
3,Vitamin PP 50 Pharmedic ngăn ngừa thiếu nicoti...,12.000₫,https://cdn.tgdd.vn/Products/Images/10053/1533...,Bổ sung vào khẩu phần ăn để ngăn ngừa thiếu hụ...,Vitamin PP,Người lớn và trẻ em trên 5 tuổi,Pharmedic,Việt Nam,Viên nén,NaN,Nicotinamid 50mg.\nTá dược 1 viên.,Vitamin PP 50 giúp bổ sung vào khẩu phần ăn để...,"Người lớn: mỗi lần 1 - 2 viên, ngày 3 lần.\nTr...","- Dị ứng với nicotinamid.\n- Bệnh gan nặng, lo...",NaN,- Thận trọng khi sử dụng\nNgười có tiền sử loé...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
4,"Agi-Calci bổ sung canxi, trị loãng xương (20 v...",150.000₫,https://cdn.tgdd.vn/Products/Images/10053/2463...,Bổ sung calci khi thiếu hay tăng nhu cầu calci...,"Calci cacbonat, Vitamin D3",NaN,Agimexpharm,Việt Nam,Viên nén bao phim,24 tháng kể từ ngày sản xuất,Mỗi viên nén bao phim chứa:\nHoạt chất: Calci ...,- Agi-Calci bổ sung calci trong các trường hợp...,Uống thuốc buổi sáng hoặc buổi trưa theo liều ...,"- Tăng calci huyết, calci niệu, sỏi calci, suy...",- Dùng thuốc chứa muối calci qua đường uống có...,- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN
5,Vitamin B1 Mekophar 250mg trị các bệnh thiếu v...,7.000₫,https://cdn.tgdd.vn/Products/Images/10053/1535...,"Điều trị các bệnh do thiếu B1, suy nhược cơ th...",NaN,NaN,Mekophar,Việt Nam,Viên nén bao đường,36 tháng kể từ ngày sản xuất,Hoạt chất: Thiamine nitrate (vitamin B1) 250mg...,- Điều trị các bệnh do thiếu vitamin B1 như: b...,- Theo chỉ dẫn của bác sĩ.\n- Người lớn: uống ...,Quá mẫn với một trong các thành phần của thuốc.,"- Tác dụng phụ rất hiếm khi xảy ra như: ngứa, ...",- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,NaN

In [12]:
# Loại bỏ cột error
ankhang_df_cleaned = ankhang_df_cleaned.drop(columns=['error'])
print(f"Số dòng sau khi loại bỏ cột error: {ankhang_df_cleaned.shape[0]}, Số cột: {ankhang_df_cleaned.shape[1]}")
ankhang_df_cleaned.info()

Số dòng sau khi loại bỏ cột error: 1969, Số cột: 19
<class 'pandas.core.frame.DataFrame'>
Index: 1969 entries, 0 to 2180
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_thuoc            1969 non-null   object
 1   gia                  453 non-null    object
 2   hinh_anh             1945 non-null   object
 3   cong_dung_tom_tat    1969 non-null   object
 4   thanh_phan_chinh     1899 non-null   object
 5   doi_tuong            1705 non-null   object
 6   thuong_hieu          1967 non-null   object
 7   noi_san_xuat         1969 non-null   object
 8   dang_bao_che         1968 non-null   object
 9   han_dung             1952 non-null   object
 10  thanh_phan_chi_tiet  1964 non-null   object
 11  cong_dung_chi_tiet   1938 non-null   object
 12  cach_dung            1953 non-null   object
 13  chong_chi_dinh       1937 non-null   object
 14  tac_dung_phu         1887 non-null   object
 15  luu_y                851 non-null    object
 16  url                  1969 non-null   object
 17  category             1921 non-null   object
 18  drug_type            1921 non-null   object
dtypes: object(19)
memory usage: 307.7+ KB

In [14]:
ankhang_df_link = pd.read_csv(r'D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_AnKhang\ankhang_medicine_links.csv', encoding='utf-8-sig')
ankhang_df_link.info()
ankhang_df_link.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2127 entries, 0 to 2126
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   link       2127 non-null   object
 1   category   2127 non-null   object
 2   drug_type  2127 non-null   object
dtypes: object(3)
memory usage: 50.0+ KB

,link,category,drug_type
0,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
1,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
2,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
3,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
4,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn

In [17]:
ankhang_df_final = pd.merge(
    ankhang_df_cleaned,
    ankhang_df_link[['link', 'category', 'drug_type']].drop_duplicates('link'),
    left_on='url',
    right_on='link',
    how='left',
    validate='m:1'
).drop(columns=['link'])  # bỏ cột links sau khi ghép nếu không cần

print(f"Số dòng sau khi merge: {ankhang_df_final.shape[0]}, Số cột: {ankhang_df_final.shape[1]}")
ankhang_df_final.info()

Số dòng sau khi merge: 1969, Số cột: 21
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_thuoc            1969 non-null   object
 1   gia                  453 non-null    object
 2   hinh_anh             1945 non-null   object
 3   cong_dung_tom_tat    1969 non-null   object
 4   thanh_phan_chinh     1899 non-null   object
 5   doi_tuong            1705 non-null   object
 6   thuong_hieu          1967 non-null   object
 7   noi_san_xuat         1969 non-null   object
 8   dang_bao_che         1968 non-null   object
 9   han_dung             1952 non-null   object
 10  thanh_phan_chi_tiet  1964 non-null   object
 11  cong_dung_chi_tiet   1938 non-null   object
 12  cach_dung            1953 non-null   object
 13  chong_chi_dinh       1937 non-null   object
 14  tac_dung_phu         1887 non-null   object
 15  luu_y                851 non-null    object
 16  url                  1969 non-null   object
 17  category_x           1921 non-null   object
 18  drug_type_x          1921 non-null   object
 19  category_y           1969 non-null   object
 20  drug_type_y          1969 non-null   object
dtypes: object(21)
memory usage: 323.2+ KB

In [19]:
print(f"category_x non-null: {ankhang_df_final['category_x'].notna().sum()}")
print(f"category_y non-null: {ankhang_df_final['category_y'].notna().sum()}")

# Kiểm tra các dòng có cả 2 giá trị
both_not_null = ankhang_df_final[ankhang_df_final['category_x'].notna() & ankhang_df_final['category_y'].notna()]
print(f"\nSố dòng có cả category_x và category_y: {len(both_not_null)}")

# So sánh giá trị khi cả 2 đều có dữ liệu
same_values = both_not_null[both_not_null['category_x'] == both_not_null['category_y']]
diff_values = both_not_null[both_not_null['category_x'] != both_not_null['category_y']]
print(f"Số dòng giống nhau: {len(same_values)}")
print(f"Số dòng KHÁC NHAU: {len(diff_values)}")

category_x non-null: 1921
category_y non-null: 1969

Số dòng có cả category_x và category_y: 1921
Số dòng giống nhau: 1921
Số dòng KHÁC NHAU: 0

In [20]:
print(f"drug_type_x non-null: {ankhang_df_final['drug_type_x'].notna().sum()}")
print(f"drug_type_y non-null: {ankhang_df_final['drug_type_y'].notna().sum()}")

both_not_null_dt = ankhang_df_final[ankhang_df_final['drug_type_x'].notna() & ankhang_df_final['drug_type_y'].notna()]
same_values_dt = both_not_null_dt[both_not_null_dt['drug_type_x'] == both_not_null_dt['drug_type_y']]
diff_values_dt = both_not_null_dt[both_not_null_dt['drug_type_x'] != both_not_null_dt['drug_type_y']]

print(f"Số dòng giống nhau: {len(same_values_dt)}")
print(f"Số dòng KHÁC NHAU: {len(diff_values_dt)}")

if len(diff_values_dt) > 0:
    print(diff_values_dt[['ten_thuoc', 'drug_type_x', 'drug_type_y']].head(10))

drug_type_x non-null: 1921
drug_type_y non-null: 1969
Số dòng giống nhau: 1921
Số dòng KHÁC NHAU: 0

In [21]:
ankhang_df_fix = ankhang_df_final.drop(columns=['category_x', 'drug_type_x'])
ankhang_df_fix = ankhang_df_fix.rename(columns={'category_y': 'category', 'drug_type_y': 'drug_type'})
ankhang_df_fix.info()
ankhang_df_fix.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_thuoc            1969 non-null   object
 1   gia                  453 non-null    object
 2   hinh_anh             1945 non-null   object
 3   cong_dung_tom_tat    1969 non-null   object
 4   thanh_phan_chinh     1899 non-null   object
 5   doi_tuong            1705 non-null   object
 6   thuong_hieu          1967 non-null   object
 7   noi_san_xuat         1969 non-null   object
 8   dang_bao_che         1968 non-null   object
 9   han_dung             1952 non-null   object
 10  thanh_phan_chi_tiet  1964 non-null   object
 11  cong_dung_chi_tiet   1938 non-null   object
 12  cach_dung            1953 non-null   object
 13  chong_chi_dinh       1937 non-null   object
 14  tac_dung_phu         1887 non-null   object
 15  luu_y                851 non-null    object
 16  url                  1969 non-null   object
 17  category             1969 non-null   object
 18  drug_type            1969 non-null   object
dtypes: object(19)
memory usage: 292.4+ KB

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type
0,"Timi Roitin trị viêm dây thần kinh, thoái hóa ...",528.000₫,https://cdn.tgdd.vn/Products/Images/10053/1304...,"Bổ sung vitamin nhóm B, điều trị viêm dây thần...","Chondroitin, Vitamin B5, Fursultiamine, Vitami...",Người lớn,Phil Inter Pharma,Việt Nam,Viên nang mềm,36 tháng kể từ ngày sản xuất,"Hoạt chất: Chondroitin sulfate natri 90mg, Nic...",- Bổ sung các vitamin nhóm B trong các trường ...,Người lớn: Uống 1 viên/ngày.\n- Quá liều\nDùng...,- Quá mẫn với bất cứ thành phần nào của thuốc....,TIMIROITIN thường được dung nạp tốt khi dùng ở...,- Thận trọng khi sử dụng\n- Khi sử dụng nicoti...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
1,B Complex C bổ sung vitamin nhóm B và vitamin ...,800₫,https://cdn.tgdd.vn/Products/Images/10053/1295...,Dự phòng & bổ sung khi thiếu hụt các vitamin n...,"Vitamin PP, Vitamin C, Vitamin B6, Vitamin B2,...",NaN,Vidipha,Việt Nam,Viên nang cứng,24 tháng kể từ ngày sản xuất,"Hoạt chất: Vitamin B1 15mg, Vitamin B2 10mg, V...",B Complex C dự phòng và bổ sung thiếu hụt các ...,Liều lượng: Trung bình: 1 - 2 viên/ngày.\nCách...,Dị ứng với một trong các thành phần của thuốc....,Dùng liều cao nước tiểu sẽ có màu vàng nhạt (d...,- Thận trọng khi sử dụng\nKhi sử dụng nicotina...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
2,Vitamin PP 50 Pharmedic ngăn ngừa thiếu nicoti...,12.000₫,https://cdn.tgdd.vn/Products/Images/10053/1533...,Bổ sung vào khẩu phần ăn để ngăn ngừa thiếu hụ...,Vitamin PP,Người lớn và trẻ em trên 5 tuổi,Pharmedic,Việt Nam,Viên nén,NaN,Nicotinamid 50mg.\nTá dược 1 viên.,Vitamin PP 50 giúp bổ sung vào khẩu phần ăn để...,"Người lớn: mỗi lần 1 - 2 viên, ngày 3 lần.\nTr...","- Dị ứng với nicotinamid.\n- Bệnh gan nặng, lo...",NaN,- Thận trọng khi sử dụng\nNgười có tiền sử loé...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
3,"Agi-Calci bổ sung canxi, trị loãng xương (20 v...",150.000₫,https://cdn.tgdd.vn/Products/Images/10053/2463...,Bổ sung calci khi thiếu hay tăng nhu cầu calci...,"Calci cacbonat, Vitamin D3",NaN,Agimexpharm,Việt Nam,Viên nén bao phim,24 tháng kể từ ngày sản xuất,Mỗi viên nén bao phim chứa:\nHoạt chất: Calci ...,- Agi-Calci bổ sung calci trong các trường hợp...,Uống thuốc buổi sáng hoặc buổi trưa theo liều ...,"- Tăng calci huyết, calci niệu, sỏi calci, suy...",- Dùng thuốc chứa muối calci qua đường uống có...,- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
4,Vitamin B1 Mekophar 250mg trị các bệnh thiếu v...,7.000₫,https://cdn.tgdd.vn/Products/Images/10053/1535...,"Điều trị các bệnh do thiếu B1, suy nhược cơ th...",NaN,NaN,Mekophar,Việt Nam,Viên nén bao đường,36 tháng kể từ ngày sản xuất,Hoạt chất: Thiamine nitrate (vitamin B1) 250mg...,- Điều trị các bệnh do thiếu vitamin B1 như: b...,- Theo chỉ dẫn của bác sĩ.\n- Người lớn: uống ...,Quá mẫn với một trong các thành phần của thuốc.,"- Tác dụng phụ rất hiếm khi xảy ra như: ngứa, ...",- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn

In [22]:
ankhang_df_fix.to_csv("Ankhang_data_preprocessed.csv", index=False, encoding='utf-8-sig')

In [3]:
ankhang_df = pd.read_csv("Ankhang_data_preprocessed.csv", encoding='utf-8-sig')
print(ankhang_df.shape)
ankhang_df.info()
ankhang_df.head()

(1969, 19)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_thuoc            1969 non-null   object
 1   gia                  453 non-null    object
 2   hinh_anh             1945 non-null   object
 3   cong_dung_tom_tat    1969 non-null   object
 4   thanh_phan_chinh     1899 non-null   object
 5   doi_tuong            1705 non-null   object
 6   thuong_hieu          1967 non-null   object
 7   noi_san_xuat         1969 non-null   object
 8   dang_bao_che         1968 non-null   object
 9   han_dung             1952 non-null   object
 10  thanh_phan_chi_tiet  1964 non-null   object
 11  cong_dung_chi_tiet   1938 non-null   object
 12  cach_dung            1953 non-null   object
 13  chong_chi_dinh       1937 non-null   object
 14  tac_dung_phu         1887 non-null   object
 15  luu_y                851 non-null    object
 16  url                  1969 non-null   object
 17  category             1969 non-null   object
 18  drug_type            1969 non-null   object
dtypes: object(19)
memory usage: 292.4+ KB

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type
0,"Timi Roitin trị viêm dây thần kinh, thoái hóa ...",528.000₫,https://cdn.tgdd.vn/Products/Images/10053/1304...,"Bổ sung vitamin nhóm B, điều trị viêm dây thần...","Chondroitin, Vitamin B5, Fursultiamine, Vitami...",Người lớn,Phil Inter Pharma,Việt Nam,Viên nang mềm,36 tháng kể từ ngày sản xuất,"Hoạt chất: Chondroitin sulfate natri 90mg, Nic...",- Bổ sung các vitamin nhóm B trong các trường ...,Người lớn: Uống 1 viên/ngày.\n- Quá liều\nDùng...,- Quá mẫn với bất cứ thành phần nào của thuốc....,TIMIROITIN thường được dung nạp tốt khi dùng ở...,- Thận trọng khi sử dụng\n- Khi sử dụng nicoti...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
1,B Complex C bổ sung vitamin nhóm B và vitamin ...,800₫,https://cdn.tgdd.vn/Products/Images/10053/1295...,Dự phòng & bổ sung khi thiếu hụt các vitamin n...,"Vitamin PP, Vitamin C, Vitamin B6, Vitamin B2,...",NaN,Vidipha,Việt Nam,Viên nang cứng,24 tháng kể từ ngày sản xuất,"Hoạt chất: Vitamin B1 15mg, Vitamin B2 10mg, V...",B Complex C dự phòng và bổ sung thiếu hụt các ...,Liều lượng: Trung bình: 1 - 2 viên/ngày.\nCách...,Dị ứng với một trong các thành phần của thuốc....,Dùng liều cao nước tiểu sẽ có màu vàng nhạt (d...,- Thận trọng khi sử dụng\nKhi sử dụng nicotina...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
2,Vitamin PP 50 Pharmedic ngăn ngừa thiếu nicoti...,12.000₫,https://cdn.tgdd.vn/Products/Images/10053/1533...,Bổ sung vào khẩu phần ăn để ngăn ngừa thiếu hụ...,Vitamin PP,Người lớn và trẻ em trên 5 tuổi,Pharmedic,Việt Nam,Viên nén,NaN,Nicotinamid 50mg.\nTá dược 1 viên.,Vitamin PP 50 giúp bổ sung vào khẩu phần ăn để...,"Người lớn: mỗi lần 1 - 2 viên, ngày 3 lần.\nTr...","- Dị ứng với nicotinamid.\n- Bệnh gan nặng, lo...",NaN,- Thận trọng khi sử dụng\nNgười có tiền sử loé...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
3,"Agi-Calci bổ sung canxi, trị loãng xương (20 v...",150.000₫,https://cdn.tgdd.vn/Products/Images/10053/2463...,Bổ sung calci khi thiếu hay tăng nhu cầu calci...,"Calci cacbonat, Vitamin D3",NaN,Agimexpharm,Việt Nam,Viên nén bao phim,24 tháng kể từ ngày sản xuất,Mỗi viên nén bao phim chứa:\nHoạt chất: Calci ...,- Agi-Calci bổ sung calci trong các trường hợp...,Uống thuốc buổi sáng hoặc buổi trưa theo liều ...,"- Tăng calci huyết, calci niệu, sỏi calci, suy...",- Dùng thuốc chứa muối calci qua đường uống có...,- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn
4,Vitamin B1 Mekophar 250mg trị các bệnh thiếu v...,7.000₫,https://cdn.tgdd.vn/Products/Images/10053/1535...,"Điều trị các bệnh do thiếu B1, suy nhược cơ th...",NaN,NaN,Mekophar,Việt Nam,Viên nén bao đường,36 tháng kể từ ngày sản xuất,Hoạt chất: Thiamine nitrate (vitamin B1) 250mg...,- Điều trị các bệnh do thiếu vitamin B1 như: b...,- Theo chỉ dẫn của bác sĩ.\n- Người lớn: uống ...,Quá mẫn với một trong các thành phần của thuốc.,"- Tác dụng phụ rất hiếm khi xảy ra như: ngứa, ...",- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn

In [8]:
# Lấy 1 thuốc bất kỳ để kiểm tra thông tin 'công dụng tóm tắt' và 'công dụng chi tiết'
sample_medicine = ankhang_df['ten_thuoc'].iloc[2]
sample_row = ankhang_df[ankhang_df['ten_thuoc'] == sample_medicine].iloc[0]

for col in ['ten_thuoc', 'cong_dung_tom_tat', 'cong_dung_chi_tiet']:
    print(f"\n{'='*50}")
    print(f"{col}:")
    print(sample_row[col])

==================================================
ten_thuoc:
Vitamin PP 50 Pharmedic ngăn ngừa thiếu nicotinamide lọ 60 viên

==================================================
cong_dung_tom_tat:
Bổ sung vào khẩu phần ăn để ngăn ngừa thiếu hụt nicotinamid, điều trị bệnh pellagra

==================================================
cong_dung_chi_tiet:
Vitamin PP 50 giúp bổ sung vào khẩu phần ăn để ngăn ngừa thiếu hụt nicotinamid.
Điều trị bệnh pellagra.

In [9]:
# Kiểm tra số lượng thiếu công dụng tóm tắt và công dụng chi tiết
missing_summary = ankhang_df['cong_dung_tom_tat'].isnull().sum()
missing_detail = ankhang_df['cong_dung_chi_tiet'].isnull().sum()
print(f"Số dòng thiếu công dụng tóm tắt: {missing_summary}")
print(f"Số dòng thiếu công dụng chi tiết: {missing_detail}")

Số dòng thiếu công dụng tóm tắt: 0
Số dòng thiếu công dụng chi tiết: 31

In [10]:
# Tạo cột mới để thống nhất công dụng
ankhang_df['cong_dung'] = ankhang_df.apply(
    lambda row: row['cong_dung_chi_tiet'] if pd.notnull(row['cong_dung_chi_tiet']) else row['cong_dung_tom_tat'],
    axis=1
)

In [11]:
ankhang_df.info()
ankhang_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ten_thuoc            1969 non-null   object
 1   gia                  453 non-null    object
 2   hinh_anh             1945 non-null   object
 3   cong_dung_tom_tat    1969 non-null   object
 4   thanh_phan_chinh     1899 non-null   object
 5   doi_tuong            1705 non-null   object
 6   thuong_hieu          1967 non-null   object
 7   noi_san_xuat         1969 non-null   object
 8   dang_bao_che         1968 non-null   object
 9   han_dung             1952 non-null   object
 10  thanh_phan_chi_tiet  1964 non-null   object
 11  cong_dung_chi_tiet   1938 non-null   object
 12  cach_dung            1953 non-null   object
 13  chong_chi_dinh       1937 non-null   object
 14  tac_dung_phu         1887 non-null   object
 15  luu_y                851 non-null    object
 16  url                  1969 non-null   object
 17  category             1969 non-null   object
 18  drug_type            1969 non-null   object
 19  cong_dung            1969 non-null   object
dtypes: object(20)
memory usage: 307.8+ KB

,ten_thuoc,gia,hinh_anh,cong_dung_tom_tat,thanh_phan_chinh,doi_tuong,thuong_hieu,noi_san_xuat,dang_bao_che,han_dung,thanh_phan_chi_tiet,cong_dung_chi_tiet,cach_dung,chong_chi_dinh,tac_dung_phu,luu_y,url,category,drug_type,cong_dung
0,"Timi Roitin trị viêm dây thần kinh, thoái hóa ...",528.000₫,https://cdn.tgdd.vn/Products/Images/10053/1304...,"Bổ sung vitamin nhóm B, điều trị viêm dây thần...","Chondroitin, Vitamin B5, Fursultiamine, Vitami...",Người lớn,Phil Inter Pharma,Việt Nam,Viên nang mềm,36 tháng kể từ ngày sản xuất,"Hoạt chất: Chondroitin sulfate natri 90mg, Nic...",- Bổ sung các vitamin nhóm B trong các trường ...,Người lớn: Uống 1 viên/ngày.\n- Quá liều\nDùng...,- Quá mẫn với bất cứ thành phần nào của thuốc....,TIMIROITIN thường được dung nạp tốt khi dùng ở...,- Thận trọng khi sử dụng\n- Khi sử dụng nicoti...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,- Bổ sung các vitamin nhóm B trong các trường ...
1,B Complex C bổ sung vitamin nhóm B và vitamin ...,800₫,https://cdn.tgdd.vn/Products/Images/10053/1295...,Dự phòng & bổ sung khi thiếu hụt các vitamin n...,"Vitamin PP, Vitamin C, Vitamin B6, Vitamin B2,...",NaN,Vidipha,Việt Nam,Viên nang cứng,24 tháng kể từ ngày sản xuất,"Hoạt chất: Vitamin B1 15mg, Vitamin B2 10mg, V...",B Complex C dự phòng và bổ sung thiếu hụt các ...,Liều lượng: Trung bình: 1 - 2 viên/ngày.\nCách...,Dị ứng với một trong các thành phần của thuốc....,Dùng liều cao nước tiểu sẽ có màu vàng nhạt (d...,- Thận trọng khi sử dụng\nKhi sử dụng nicotina...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,B Complex C dự phòng và bổ sung thiếu hụt các ...
2,Vitamin PP 50 Pharmedic ngăn ngừa thiếu nicoti...,12.000₫,https://cdn.tgdd.vn/Products/Images/10053/1533...,Bổ sung vào khẩu phần ăn để ngăn ngừa thiếu hụ...,Vitamin PP,Người lớn và trẻ em trên 5 tuổi,Pharmedic,Việt Nam,Viên nén,NaN,Nicotinamid 50mg.\nTá dược 1 viên.,Vitamin PP 50 giúp bổ sung vào khẩu phần ăn để...,"Người lớn: mỗi lần 1 - 2 viên, ngày 3 lần.\nTr...","- Dị ứng với nicotinamid.\n- Bệnh gan nặng, lo...",NaN,- Thận trọng khi sử dụng\nNgười có tiền sử loé...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,Vitamin PP 50 giúp bổ sung vào khẩu phần ăn để...
3,"Agi-Calci bổ sung canxi, trị loãng xương (20 v...",150.000₫,https://cdn.tgdd.vn/Products/Images/10053/2463...,Bổ sung calci khi thiếu hay tăng nhu cầu calci...,"Calci cacbonat, Vitamin D3",NaN,Agimexpharm,Việt Nam,Viên nén bao phim,24 tháng kể từ ngày sản xuất,Mỗi viên nén bao phim chứa:\nHoạt chất: Calci ...,- Agi-Calci bổ sung calci trong các trường hợp...,Uống thuốc buổi sáng hoặc buổi trưa theo liều ...,"- Tăng calci huyết, calci niệu, sỏi calci, suy...",- Dùng thuốc chứa muối calci qua đường uống có...,- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,- Agi-Calci bổ sung calci trong các trường hợp...
4,Vitamin B1 Mekophar 250mg trị các bệnh thiếu v...,7.000₫,https://cdn.tgdd.vn/Products/Images/10053/1535...,"Điều trị các bệnh do thiếu B1, suy nhược cơ th...",NaN,NaN,Mekophar,Việt Nam,Viên nén bao đường,36 tháng kể từ ngày sản xuất,Hoạt chất: Thiamine nitrate (vitamin B1) 250mg...,- Điều trị các bệnh do thiếu vitamin B1 như: b...,- Theo chỉ dẫn của bác sĩ.\n- Người lớn: uống ...,Quá mẫn với một trong các thành phần của thuốc.,"- Tác dụng phụ rất hiếm khi xảy ra như: ngứa, ...",- Thận trọng khi sử dụng\nThận trọng khi sử dụ...,https://www.nhathuocankhang.com/thuoc-bo-va-vi...,Thuốc bổ và vitamin,Không kê đơn,- Điều trị các bệnh do thiếu vitamin B1 như: b...

In [12]:
# Luu lại file đã chỉnh sửa
ankhang_df.to_csv("Ankhang_data_preprocessed_final.csv", index=False, encoding='utf-8-sig')