In [14]:
import pandas as pd
import numpy as np

In [15]:
minhchau_df = pd.read_csv(r'D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_MinhChau\minhchau_medicines_data.csv')
minhchau_df.info()
minhchau_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9544 entries, 0 to 9543
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   category            9544 non-null   object
 1   link                9544 non-null   object
 2   name                9265 non-null   object
 3   images              9266 non-null   object
 4   error               253 non-null    object
 5   hoat_chat           4146 non-null   object
 6   quy_cach_dong_goi   8493 non-null   object
 7   thuong_hieu         7867 non-null   object
 8   xuat_xu             8764 non-null   object
 9   thuoc_can_ke_toa    4108 non-null   object
 10  dang_bao_che        4242 non-null   object
 11  ham_luong           0 non-null      float64
 12  nha_san_xuat        4251 non-null   object
 13  tieu_chuan          1367 non-null   object
 14  thanh_phan          8931 non-null   object
 15  cong_dung_chi_dinh  9057 non-null   object
 16  lieu_dung           6648 non-null   object
 17  cach_dung           5139 non-null   object
 18  luu_y               6496 non-null   object
 19  chong_chi_dinh      8303 non-null   object
 20  tac_dung_phu        8048 non-null   object
 21  tuong_tac_thuoc     6665 non-null   object
 22  Bao_quan            4992 non-null   object
 23  detail_raw_text     9080 non-null   object
dtypes: float64(1), object(23)
memory usage: 1.7+ MB

,category,link,name,images,error,hoat_chat,quy_cach_dong_goi,thuong_hieu,xuat_xu,thuoc_can_ke_toa,...,thanh_phan,cong_dung_chi_dinh,lieu_dung,cach_dung,luu_y,chong_chi_dinh,tac_dung_phu,tuong_tac_thuoc,Bao_quan,detail_raw_text
0,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/apilevo-500-ap...,Apilevo 500 Apimed 3 vỉ x 10 viên,https://cdn.famitaa.net/storage/uploads/images...,NaN,Levofloxacin,Hộp 3 vỉ x 10 viên,Apimed,Việt Nam,Có,...,Levofloxacin: 500mg.,Viêm phổi mắc phải cộng đồng.\nNhiễm khuẩn đườ...,Liều dùng của viên nén levofloxacin: Dùng 1 – ...,Thuốc dùng đường uống.\nUống nguyên viên thuốc...,Các phản ứng có hại nghiêm trọng có khả năng k...,Bệnh nhân quá mẫn với levofloxacin hoặc các qu...,"Trong mỗi nhóm phân loại theo tần suất, các tá...","Ảnh hưởng của các thuốc khác:\nMuối sắt, muối ...","Nơi khô, tránh ánh sáng, nhiệt độ dưới 30°C.",Thành phần\nLevofloxacin: 500mg.\nCông dụng (C...
1,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/vigentin-87512...,Vigentin 875/125 DT. Pharbaco 2 vỉ x 7 viên (A...,https://cdn.famitaa.net/storage/uploads/images...,NaN,Amoxicillin/Acid Clavulanic,Hộp 2 vỉ x 7 viên,Pharbaco,Việt Nam,Có,...,Amoxicillin trihydrat: 875mg\nAcid clavulanic:...,Các chế phẩm amoxicilin và kali clavulanat đượ...,Liều lượng thường được biểu thị dưới dạng amox...,Dùng đường uống.,"Chú ý đến người già, người bệnh có tiền sử vàn...",Dị ứng với nhóm beta-lactam (các penicilin và ...,Các tác dụng không mong muốn thường có liên qu...,Thuốc có thể gây kéo dài thời gian chảy máu và...,"Nơi khô, tránh ánh sáng, nhiệt độ dưới 30°C.",Thành phần\nAmoxicillin trihydrat: 875mg\nAcid...
2,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/novofenti-200m...,Novofenti 200mg CPC1 Hà Nội 1 vỉ x 3 viên,https://cdn.famitaa.net/storage/uploads/images...,NaN,Fenticonazole,3 viên,CPC1,Việt Nam,Có,...,Fenticonazol nitrat: 200mg.,Novofenti được chỉ định dùng cho các trường hợ...,Người lớn và trẻ trên 16 tuổi:\nĐặt một viên N...,Đặt âm đạo.,Không nên sử dụng kết hợp với các biện pháp tr...,Mẫn cảm với các thành phần của sản phẩm và các...,Sau khi điều trị có thể xảy ra tái phát nhẹ sa...,"Không được thống kê.\nThành phần dầu, chất béo...","Nơi khô, tránh ánh sáng, nhiệt độ dưới 30°C.",Thành phần\nFenticonazol nitrat: 200mg.\nCông ...
3,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/cotrimoxazol-4...,Cotrimoxazol 480mg Thephaco 20 vỉ x 20 viên (S...,https://cdn.famitaa.net/storage/uploads/images...,NaN,Trimethoprim/Sulfamethoxazole,Hộp 20 vỉ x 20 viên,Thephaco,Việt Nam,Có,...,Sulfamethoxazol: 400mg\nTrimethoprim: 80mg,Viêm tai giữa cấp.\nNhiễm khuẩn đường tiết niệ...,Viêm tai giữa cấp: Trẻ em từ 2 tháng tuổi trở ...,Cotrimoxazol 480mg được uống cùng với thức ăn ...,Viêm họng do S.Pyogenes: Không nên dùng Cotrim...,Bệnh nhân quá mẫn với sulfamethoxazole hay tri...,"Thường gặp (1/100 ≤ ADR < 1/10):\nBuồn nôn, nô...",Warfarin: Cotrimoxazol 480mg có thế kéo dài th...,"Nơi khô, tránh ánh sáng, nhiệt độ dưới 30°C.",Thành phần\nSulfamethoxazol: 400mg\nTrimethopr...
4,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/fungafin-10mg-...,Fungafin 10mg CPC1 Hà Nội lọ 15ml,https://cdn.famitaa.net/storage/uploads/images...,NaN,Terbinafine,15ml,CPC1,Việt Nam,Không,...,Terbinafin hydroclorid: 10mg.,Nhiễm nấm da gây ra bởi các loại nấm như Trich...,Người lớn và trẻ em lớn hơn 16 tuổi: Sử dụng 1...,Rửa sạch và lau khô vùng da bị nhiễm nấm trước...,Thận trọng với bệnh nhân có tổn thương mà có t...,Mẫn cảm với terbinafin hydroclorid hoặc bất cứ...,"Các triệu chứng tại chỗ như ngứa, ban da tróc ...",Chưa có thông tin về sự tương tác giữa terbina...,"Nơi khô, tránh ánh sáng, nhiệt độ dưới 30°C.",Thành phần\nTerbinafin hydroclorid: 10mg.\nCôn...

In [16]:
# Kiểm tra các dòng có lỗi (cột error có giá trị)
error_rows = minhchau_df[minhchau_df['error'].notna()]
# Hiển thị các dòng có lỗi
print(error_rows[['name', 'error']])

     name                                              error
244   NaN  TimeoutException: Message: \nStacktrace:\n\tch...
252   NaN  ReadTimeoutError: HTTPConnectionPool(host='loc...
253   NaN  ReadTimeoutError: HTTPConnectionPool(host='loc...
2689  NaN  WebDriverException: Message: unknown error: ne...
2690  NaN  WebDriverException: Message: unknown error: ne...
...   ...                                                ...
5275  NaN  WebDriverException: Message: unknown error: ne...
5276  NaN  WebDriverException: Message: unknown error: ne...
5277  NaN  WebDriverException: Message: unknown error: ne...
5278  NaN  WebDriverException: Message: unknown error: ne...
5279  NaN  WebDriverException: Message: unknown error: ne...

[253 rows x 2 columns]

In [17]:
# Đếm số dòng có lỗi unknown error (có chứa giá trị 'unknown error: ' trong cột error)
unknown_error_count = error_rows[error_rows['error'].str.contains('unknown error: ', case=False, na=False)].shape[0]
print(f"Số dòng có lỗi 'unknown error: ': {unknown_error_count}")
print("In ra các dòng có lỗi 'unknown error: ':")
unknown_error_rows = error_rows[error_rows['error'].str.contains('unknown error: ', case=False, na=False)]
unknown_error_rows[['name', 'error']]

Số dòng có lỗi 'unknown error: ': 249
In ra các dòng có lỗi 'unknown error: ':

     name                                              error
2689  NaN  WebDriverException: Message: unknown error: ne...
2690  NaN  WebDriverException: Message: unknown error: ne...
2691  NaN  WebDriverException: Message: unknown error: ne...
2692  NaN  WebDriverException: Message: unknown error: ne...
2693  NaN  WebDriverException: Message: unknown error: ne...
...   ...                                                ...
5275  NaN  WebDriverException: Message: unknown error: ne...
5276  NaN  WebDriverException: Message: unknown error: ne...
5277  NaN  WebDriverException: Message: unknown error: ne...
5278  NaN  WebDriverException: Message: unknown error: ne...
5279  NaN  WebDriverException: Message: unknown error: ne...

[249 rows x 2 columns]

In [18]:
# Kiểm tra tên thuốc có trùng nhau không
duplicate_names = minhchau_df[minhchau_df.duplicated(subset=['name'], keep=False)]
print(f"Số dòng có tên thuốc trùng nhau: {duplicate_names.shape[0]}")
print("In ra các dòng có tên thuốc trùng nhau:")
duplicate_names[['name', 'error']]

Số dòng có tên thuốc trùng nhau: 382
In ra các dòng có tên thuốc trùng nhau:

,name,error
83,Fyranco 400mg Demo S.A 1 lọ x 3ml,NaN
115,Fyranco 400mg Demo S.A 1 lọ x 3ml,NaN
244,NaN,TimeoutException: Message: \nStacktrace:\n\tch...
252,NaN,ReadTimeoutError: HTTPConnectionPool(host='loc...
253,NaN,ReadTimeoutError: HTTPConnectionPool(host='loc...
...,...,...
8942,Posinight 1 Agimexpharm 1 viên,NaN
9236,NaN,NaN
9257,Thuốc hỗ trợ điều trị viêm khớp CELECOXID - Ce...,NaN
9258,Thuốc hỗ trợ điều trị viêm khớp CELECOXID - Ce...,NaN
9340,NaN,NaN

In [19]:
# Kiểm tra có bao nhiêu tên thuốc bị NaN
nan_name_count = minhchau_df['name'].isna().sum()
print(f"Số dòng có tên thuốc bị NaN: {nan_name_count}")

Số dòng có tên thuốc bị NaN: 279

In [24]:
# Kiểm tra các hàng có thông tin cột Name,link, category nhưng các cột khác đều bị NaN
non_na_col = ['name', 'link', 'category','images']
other_cols = minhchau_df.columns.difference(non_na_col)

mask = (
    minhchau_df[non_na_col].notna().all(axis=1) &
    minhchau_df[other_cols].isna().all(axis=1)
)

rows_only_core = minhchau_df[mask]
rows_only_core.shape[0]
rows_only_core

,category,link,name,images,error,hoat_chat,quy_cach_dong_goi,thuong_hieu,xuat_xu,thuoc_can_ke_toa,...,thanh_phan,cong_dung_chi_dinh,lieu_dung,cach_dung,luu_y,chong_chi_dinh,tac_dung_phu,tuong_tac_thuoc,Bao_quan,detail_raw_text
103,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/akurit-4-sando...,"Akurit 4 Sandoz, 24 vỉ x 28 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/imexpharm-phar...,"Imexpharm Pharmox 500mg, Chai 100 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1383,Thuốc tim mạch & Huyết áp,https://nhathuocminhchau.com.vn/ebitac-forte-f...,"Ebitac Forte Farmak, Hộp 2 vỉ x 10 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1422,Thuốc tim mạch & Huyết áp,https://nhathuocminhchau.com.vn/rivaxored-10mg...,Rivaxored 10mg Dr. Reddy's 1 vỉ x 10 viên,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1423,Thuốc tim mạch & Huyết áp,https://nhathuocminhchau.com.vn/rivaxored-15mg...,Rivaxored 15mg Dr. Reddy's 1 vỉ x 14 viên,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1424,Thuốc tim mạch & Huyết áp,https://nhathuocminhchau.com.vn/rivaxored-20mg...,Rivaxored 20mg Dr. Reddy's 1 vỉ x 14 viên,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1460,Thuốc tim mạch & Huyết áp,https://nhathuocminhchau.com.vn/xarelto-15mg-b...,Xarelto 15mg Bayer 1 vỉ x 14 viên,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2930,Thuốc hướng thần & Cai nghiện,https://nhathuocminhchau.com.vn/thuoc-mibeserc...,"Thuốc Mibeserc 24mg, Hộp 100 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2964,Thuốc hướng thần & Cai nghiện,https://nhathuocminhchau.com.vn/thuoc-huong-th...,"Thuốc hướng thần Invega Sustenna 75mg/0,75ml",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2965,Thuốc hướng thần & Cai nghiện,https://nhathuocminhchau.com.vn/thuoc-huong-th...,Thuốc hướng thần Invega Sustenna 100mg/1ml,https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2966,Thuốc hướng thần & Cai nghiện,https://nhathuocminhchau.com.vn/thuoc-huong-th...,"Thuốc hướng thần Invega Sustenna 150mg/1,5ml",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3012,Thuốc hướng thần & Cai nghiện,https://nhathuocminhchau.com.vn/thuoc-huong-th...,"Thuốc hướng thần Citalopram Sandoz 20mg, Hộp 2...",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3013,Thuốc hướng thần & Cai nghiện,https://nhathuocminhchau.com.vn/thuoc-huong-th...,"Thuốc hướng thần Temeta 1mg, Hộp 30 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3516,Thuốc chống dị ứng ( kháng histamin),https://nhathuocminhchau.com.vn/histirine-micr...,"Histirine Micro, 5mg, Hộp 10 Vỉ x 10 Viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3816,Thuốc dùng ngoài,https://nhathuocminhchau.com.vn/dau-xoa-bop-ch...,Dầu xoa bóp Chỉ Thống Linh Chánh Đại Gpharm 100ml,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3997,Thuốc dùng ngoài,https://nhathuocminhchau.com.vn/vizulize-inten...,Vizulize Intensive Dry Eye Drops 10ml cung cấp...,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4013,Thuốc dùng ngoài,https://nhathuocminhchau.com.vn/dau-ngai-diep-...,Dầu ngải diệp Nam Hà 100ml,https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4026,Thuốc dùng ngoài,https://nhathuocminhchau.com.vn/axe-brand-medi...,Axe Brand Medicated Oil 10ml dầu gió trắng cây...,https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4041,Thuốc dùng ngoài,https://nhathuocminhchau.com.vn/thuoc-nho-mat-...,Thuốc nhỏ mắt DHG Eyelight Tetrahydrozolin HCL...,https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4066,Thuốc dùng ngoài,https://nhathuocminhchau.com.vn/kem-boi-da-avi...,"Kem bôi da AVI-05 Việt Phúc, Hộp 10gr",https://cdn.famitaa.net/storage/uploads/images...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4101,Thuốc dùng ngoài,https://nhathuocminhchau.com.vn/kem-boi-da-ib-...,Kem bôi da IB 10gr,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4803,Thuốc Hô Hấp,https://nhathuocminhchau.com.vn/xach-tay-duc-t...,Tinh chất Prospan Hustentropfen 50ml,https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4831,Thuốc Hô Hấp,https://nhathuocminhchau.com.vn/vien-ngam-bao-...,"Viên ngậm BẢO THANH No Sugar, Hộp 20 vỉ",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5498,"Thuốc kháng viêm, giảm đau & hạ sốt",https://nhathuocminhchau.com.vn/locobile-100-1...,Locobile-100 100mg Windlas 3 vỉ x 10 viên,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5499,"Thuốc kháng viêm, giảm đau & hạ sốt",https://nhathuocminhchau.com.vn/locobile-200-2...,Locobile-200 200mg Windlas 3 vỉ x 10 viên,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5523,"Thuốc kháng viêm, giảm đau & hạ sốt",https://nhathuocminhchau.com.vn/dexamethason-0...,"Dexamethason 0,5mg Imexpharm, Chai 500 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5559,"Thuốc kháng viêm, giảm đau & hạ sốt",https://nhathuocminhchau.com.vn/thuoc-giam-dau...,"Thuốc giảm đau Tylenol Extra Strength 650mg, H...",https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5658,"Thuốc kháng viêm, giảm đau & hạ sốt",https://nhathuocminhchau.com.vn/tylenol-acetam...,Tylenol Acetaminophen Extra Strength 500mg 225...,https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5752,"Thuốc kháng viêm, giảm đau & hạ sốt",https://nhathuocminhchau.com.vn/thuoc-macleods...,Thuốc Macleods Lamivudine 150mg and Zidovudine...,https://cdn.famitaa.net/storage/uploads/images...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5989,"Thuốc kháng viêm, giảm đau & hạ sốt",https://nhathuocminhchau.com.vn/thuoc-acepron-...,"VPC Acepron 325mg, Hộp 20 gói",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6102,Thuốc cường dương,https://nhathuocminhchau.com.vn/glotafil-20mg-...,"Glotafil 20mg Glomed, Hộp 2 viên",https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6103,Thuốc cường dương,https://nhathuocminhchau.com.vn/glotafil-20mg-...,"Glotafil 20mg Abbott, Hộp 2 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6375,"Thuốc Tiêu Hóa, gan mật",https://nhathuocminhchau.com.vn/biosubtyl-ii-b...,Biosubtyl-II Biopharco 1g x 50 gói - Men vi si...,https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6389,"Thuốc Tiêu Hóa, gan mật",https://nhathuocminhchau.com.vn/mestad-500mg-s...,Mestad 500mg Stella,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6412,"Thuốc Tiêu Hóa, gan mật",https://nhathuocminhchau.com.vn/atproton-20mg-...,"Atproton 20mg Macleods, Hộp 3 vỉ x 10 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6516,"Thuốc Tiêu Hóa, gan mật",https://nhathuocminhchau.com.vn/thuoc-tiem-epr...,"Thuốc tiêm Eprex U 3000IU/0,3ml",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6608,"Thuốc Tiêu Hóa, gan mật",https://nhathuocminhchau.com.vn/thuoc-zozo-150...,"Thuốc Zozo 150mg, Hộp 30 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6716,"Thuốc Tiêu Hóa, gan mật",https://nhathuocminhchau.com.vn/thuoc-normagut...,"Thuốc Normagut 250mg, Hộp 30 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6731,"Thuốc Tiêu Hóa, gan mật",https://nhathuocminhchau.com.vn/traphaco-dafra...,"Traphaco Dafrazol, Hộp 14 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6775,"Thuốc Tiêu Hóa, gan mật",https://nhathuocminhchau.com.vn/thuoc-berberin...,"Thuốc Berberin 50mg TW3, Hộp 30 viên",https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7163,"Thuốc trị ung thư, u bướu",https://nhathuocminhchau.com.vn/thuoc-tri-ung-...,"Thuốc trị ung thư Zytiga 500mg, Hộp 60 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7164,"Thuốc trị ung thư, u bướu",https://nhathuocminhchau.com.vn/thuoc-darzalex...,Thuốc Darzalex 100mg/5ml,https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7165,"Thuốc trị ung thư, u bướu",https://nhathuocminhchau.com.vn/thuoc-darzalex...,Thuốc Darzalex 400mg/20ml,https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7578,"Thuốc Hocmon, Nội tiết tố",https://nhathuocminhchau.com.vn/mezamazol-5mg-...,"Mezamazol 5mg DHT, Hộp 10 vỉ x 10 viên",https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7730,"Thuốc tiêm, dịch truyền",https://nhathuocminhchau.com.vn/thuoc-lucentis...,"Thuốc Lucentis 1,65mg/0.65ml",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8188,Thuốc kháng Virus,https://nhathuocminhchau.com.vn/biktarvy-50mg2...,Biktarvy 50mg/200mg/25mg Gilead 30 viên - Thuố...,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8523,Thuốc bổ - Vitamin - Khoáng chất,https://nhathuocminhchau.com.vn/homtamin-ginse...,"Homtamin Ginseng Korea United Pharma, Hộp 60 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8937,Thuốc ngừa thai,https://nhathuocminhchau.com.vn/new-choice-ad-...,New Choice AD Nam Hà 1 vỉ x 21 viên,https://cdn.famitaa.net/storage/uploads/images...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9084,"Thuốc gout, cơ, xương khớp",https://nhathuocminhchau.com.vn/vien-xuong-kho...,Viên xương Khớp malaysia Professors Pill ( TEM...,https://cdn.famitaa.net/storage/uploads/noidun...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9091,"Thuốc gout, cơ, xương khớp",https://nhathuocminhchau.com.vn/thuoc-colthimu...,Thuốc Colthimus 4Mg,https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9306,Thuốc tác dụng đối với máu,https://nhathuocminhchau.com.vn/thuoc-elopag-e...,"Thuốc Elopag Eltrombopag 25mg, Chai 28 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9451,"Thuốc trị viêm gan B,C & HIV",https://nhathuocminhchau.com.vn/tafer-25mg-hop...,"Tafer 25mg, Hộp 30 viên",https://nhathuocminhchau.vn/storage/uploads/im...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Số tên thuốc trùng khác nan
non_nan_duplicate_names = duplicate_names[duplicate_names['name'].notna()]
print(f"Số dòng có tên thuốc trùng nhau nhưng không phải NaN: {non_nan_duplicate_names.shape[0]}")
print("In ra các dòng có tên thuốc trùng nhau nhưng không phải NaN:")
non_nan_duplicate_names[['name']]

Số dòng có tên thuốc trùng nhau nhưng không phải NaN: 103
In ra các dòng có tên thuốc trùng nhau nhưng không phải NaN:

                                                   name
83                    Fyranco 400mg Demo S.A 1 lọ x 3ml
115                   Fyranco 400mg Demo S.A 1 lọ x 3ml
656   Cebest 200mg Merap 2 vỉ x 10 viên - Điều trị n...
657   Cebest 200mg Merap 2 vỉ x 10 viên - Điều trị n...
878   Thuốc kháng nấm METRONIZAZOL - Metronidazol 250mg
...                                                 ...
8771                 Viên uống bổ sung Vitamin B1 250mg
8940                     Posinight 1 Agimexpharm 1 viên
8942                     Posinight 1 Agimexpharm 1 viên
9257  Thuốc hỗ trợ điều trị viêm khớp CELECOXID - Ce...
9258  Thuốc hỗ trợ điều trị viêm khớp CELECOXID - Ce...

[103 rows x 1 columns]

In [ ]:
# Kiểm tra số lần trùng của mỗi tên thuốc trong non_nan_duplicate_names
duplicate_name_counts = non_nan_duplicate_names['name'].value_counts()
print("Số lần trùng của mỗi tên thuốc trong non_nan_duplicate_names:")
print(duplicate_name_counts)

Số lần trùng của mỗi tên thuốc trong non_nan_duplicate_names:
name
Thuốc PREDNISON 5mg TW25, 500 viên                                                             3
Thuốc kháng Histamin CETIRIZIN - Cetiricin dihydroclorid 10mg                                  3
Dostinex 0.5mg Pfizer 8 viên                                                                   3
Thuốc kháng nấm METRONIZAZOL - Metronidazol 250mg                                              2
Spiranisol Forte OPV 2 vỉ x 10 viên                                                            2
Lipitor 40mg Pfizer 3 vỉ x 10 viên                                                             2
Valsgim H 160/12.5 Agimexpharm 2 vỉ x 14 viên                                                  2
Thuốc kháng sinh DOXYCYCLIN - Doxycyclin 100mg                                                 2
Valsgim 80mg Agimexpharm 2 vỉ x 14 viên                                                        2
Valsgim 160mg Agimexpharm 2 vỉ x 14 viên                                                       2
Thuốc chống đông Brilinta Ticagrelor 90mg, Hộp 60 viên                                         2
FINABRAT 100 - Fenofibrat 100mg                                                                2
Sitagibes 50mg Agimexpharm 4 vỉ x 7 viên                                                       2
Sitagibes 100mg Agimexpharm 4 vỉ x 7 viên                                                      2
Thuốc tiểu đường Jardiance 25mg, Hộp 30 viên                                                   2
Valsgim H 80mg Agimexpharm 2 vỉ x 14 viên                                                      2
Fyranco 400mg Demo S.A 1 lọ x 3ml                                                              2
Cebest 200mg Merap 2 vỉ x 10 viên - Điều trị nhiễm khuẩn                                       2
Lugtils Agimexpharm 3 vỉ x 10 viên                                                             2
Lyrica 75mg Pfizer 4 vỉ x 14 viên                                                              2
Vaco-Piracetam 400mg Vacopharm 10 vỉ x 10 viên – Thuốc điều trị chóng mặt, suy giảm trí nhớ    2
Thuốc Ginkor Fort, Hộp 30 viên                                                                 2
Cetazin Vacopharm 200 viên                                                                     2
Cetazin Vacopharm 10 vỉ x 10 viên                                                              2
Cestasin Vacopharm 500 viên                                                                    2
Acetakan 80 Agimexpharm 6 vỉ x 10 viên                                                         2
Levnew 5mg Agimexpharm 1 vỉ x 10 viên                                                          2
Dầu Gió Xanh Eagle Brand Singapore 24ml                                                        2
Utrahealth F.C Tablet Standard 10 vỉ x 10 viên                                                 2
Baburol Agimexpharm 3 vỉ x 10 viên                                                             2
Acetab 325 Agimexpharm 10 vỉ x 10 viên                                                         2
Racedagim 30mg Agimexpharm 25 gói x 3g                                                         2
Acedagim 10mg Agimexpharm 10 gói x 1g                                                          2
Aricept 10mg Pfizer 2 vỉ x 14 viên                                                             2
Loperamid 2mg Agimexpharm 10 vỉ x 10 viên                                                      2
Doagithicon Agimexpharm 30ml                                                                   2
Purinethol 50mg Aspen 25 viên                                                                  2
Thuốc lợi gan mật BAR, Chai 180 viên                                                           2
Thuốc ung thư Methotrexate 2.5mg 24 viên                                                       2
NUTRIFLEX PERI SOL. BAG 1000ML, Hộp 5 túi                                                      2
PROPOFOL-LIPURO 0.5% INJ. 20ML, Hộp 5 lọ                                                       2
DIPRIVAN PRE-FILLED SYRING10MG/ML50ML                                                          2
Kim Tiền Thảo AGP 160 Agimexpharm 60 viên                                                      2
Tenofovir 300mg DHG 3 vỉ x 10 viên                                                             2
Viên sủi Ca-C 1000mg Sandoz Orange, Tube 10 viên                                               2
Thuốc Phuzibi 140mg, Hộp 100 viên                                                              2
Viên uống bổ sung Vitamin B COMPLEX C                                                          2
Viên uống bổ sung Vitamin B1 250mg                                                             2
Posinight 1 Agimexpharm 1 viên                                                                 2
Thuốc hỗ trợ điều trị viêm khớp CELECOXID - Celecoxib 200mg                                    2
Name: count, dtype: int64

In [27]:
# Cột khóa
key_col = 'name'
non_key_cols = non_nan_duplicate_names.columns.difference([key_col])

# Với mỗi name, kiểm tra xem có cột nào có >1 giá trị khác nhau
diff_mask = (
    non_nan_duplicate_names
    .groupby(key_col)[non_key_cols]
    .nunique(dropna=False)  # coi NaN là một giá trị để so sánh
    .gt(1)
    .any(axis=1)
)

duplicate_name_groups = diff_mask[diff_mask].index

print(f"Số tên thuốc trùng nhau nhưng nội dung khác nhau: {len(duplicate_name_groups)}")
print("In ra các tên thuốc trùng nhau nhưng nội dung khác nhau:")
print(duplicate_name_groups)

Số tên thuốc trùng nhau nhưng nội dung khác nhau: 50
In ra các tên thuốc trùng nhau nhưng nội dung khác nhau:
Index(['Acedagim 10mg Agimexpharm 10 gói x 1g',
       'Acetab 325 Agimexpharm 10 vỉ x 10 viên',
       'Acetakan 80 Agimexpharm 6 vỉ x 10 viên',
       'Aricept 10mg Pfizer 2 vỉ x 14 viên',
       'Baburol Agimexpharm 3 vỉ x 10 viên',
       'Cebest 200mg Merap 2 vỉ x 10 viên - Điều trị nhiễm khuẩn',
       'Cestasin Vacopharm 500 viên', 'Cetazin Vacopharm 10 vỉ x 10 viên',
       'Cetazin Vacopharm 200 viên', 'DIPRIVAN PRE-FILLED SYRING10MG/ML50ML',
       'Doagithicon Agimexpharm 30ml', 'Dostinex 0.5mg Pfizer 8 viên',
       'Dầu Gió Xanh Eagle Brand Singapore 24ml',
       'FINABRAT 100 - Fenofibrat 100mg', 'Fyranco 400mg Demo S.A 1 lọ x 3ml',
       'Kim Tiền Thảo AGP 160 Agimexpharm 60 viên',
       'Levnew 5mg Agimexpharm 1 vỉ x 10 viên',
       'Lipitor 40mg Pfizer 3 vỉ x 10 viên',
       'Loperamid 2mg Agimexpharm 10 vỉ x 10 viên',
       'Lugtils Agimexpharm 3 vỉ x 10 viên',
       'Lyrica 75mg Pfizer 4 vỉ x 14 viên',
       'NUTRIFLEX PERI SOL. BAG 1000ML, Hộp 5 túi',
       'PROPOFOL-LIPURO 0.5% INJ. 20ML, Hộp 5 lọ',
       'Posinight 1 Agimexpharm 1 viên', 'Purinethol 50mg Aspen 25 viên',
       'Racedagim 30mg Agimexpharm 25 gói x 3g',
       'Sitagibes 100mg Agimexpharm 4 vỉ x 7 viên',
       'Sitagibes 50mg Agimexpharm 4 vỉ x 7 viên',
       'Spiranisol Forte OPV 2 vỉ x 10 viên',
       'Tenofovir 300mg DHG 3 vỉ x 10 viên', 'Thuốc Ginkor Fort, Hộp 30 viên',
       'Thuốc PREDNISON 5mg TW25, 500 viên',
       'Thuốc Phuzibi 140mg, Hộp 100 viên',
       'Thuốc chống đông Brilinta Ticagrelor 90mg, Hộp 60 viên',
       'Thuốc hỗ trợ điều trị viêm khớp CELECOXID - Celecoxib 200mg',
       'Thuốc kháng Histamin CETIRIZIN - Cetiricin dihydroclorid 10mg',
       'Thuốc kháng nấm METRONIZAZOL - Metronidazol 250mg',
       'Thuốc kháng sinh DOXYCYCLIN - Doxycyclin 100mg',
       'Thuốc lợi gan mật BAR, Chai 180 viên',
       'Thuốc tiểu đường Jardiance 25mg, Hộp 30 viên',
       'Thuốc ung thư Methotrexate 2.5mg 24 viên',
       'Utrahealth F.C Tablet Standard 10 vỉ x 10 viên',
       'Vaco-Piracetam 400mg Vacopharm 10 vỉ x 10 viên – Thuốc điều trị chóng mặt, suy giảm trí nhớ',
       'Valsgim 160mg Agimexpharm 2 vỉ x 14 viên',
       'Valsgim 80mg Agimexpharm 2 vỉ x 14 viên',
       'Valsgim H 160/12.5 Agimexpharm 2 vỉ x 14 viên',
       'Valsgim H 80mg Agimexpharm 2 vỉ x 14 viên',
       'Viên sủi Ca-C 1000mg Sandoz Orange, Tube 10 viên',
       'Viên uống bổ sung Vitamin B COMPLEX C',
       'Viên uống bổ sung Vitamin B1 250mg'],
      dtype='object', name='name')

In [29]:
# Bảng số lượng giá trị khác nhau theo từng cột
nunique_table = (
    non_nan_duplicate_names
    .groupby(key_col)[non_key_cols]
    .nunique(dropna=False)  # NaN cũng tính là một giá trị
)

# Chỉ giữ những cột có >1 giá trị (tức là khác nhau)
diff_cols_per_name = nunique_table.gt(1)

# In ra các cột khác nhau theo từng name
for name, row in diff_cols_per_name.iterrows():
    diff_cols = row[row].index.tolist()
    if diff_cols:
        print(f"{name} khác ở cột: {diff_cols}")

Acedagim 10mg Agimexpharm 10 gói x 1g khác ở cột: ['detail_raw_text', 'images', 'link', 'thanh_phan']
Acetab 325 Agimexpharm 10 vỉ x 10 viên khác ở cột: ['cach_dung', 'chong_chi_dinh', 'cong_dung_chi_dinh', 'dang_bao_che', 'detail_raw_text', 'images', 'lieu_dung', 'link', 'luu_y', 'tac_dung_phu', 'tuong_tac_thuoc']
Acetakan 80 Agimexpharm 6 vỉ x 10 viên khác ở cột: ['chong_chi_dinh', 'dang_bao_che', 'detail_raw_text', 'images', 'link', 'luu_y', 'tuong_tac_thuoc']
Aricept 10mg Pfizer 2 vỉ x 14 viên khác ở cột: ['Bao_quan', 'cach_dung', 'chong_chi_dinh', 'cong_dung_chi_dinh', 'dang_bao_che', 'detail_raw_text', 'hoat_chat', 'images', 'lieu_dung', 'link', 'luu_y', 'nha_san_xuat', 'tac_dung_phu', 'thanh_phan', 'thuoc_can_ke_toa', 'tuong_tac_thuoc', 'xuat_xu']
Baburol Agimexpharm 3 vỉ x 10 viên khác ở cột: ['Bao_quan', 'cach_dung', 'cong_dung_chi_dinh', 'dang_bao_che', 'detail_raw_text', 'hoat_chat', 'images', 'lieu_dung', 'link', 'luu_y', 'nha_san_xuat', 'tac_dung_phu', 'thanh_phan', 'thuoc_can_ke_toa']
Cebest 200mg Merap 2 vỉ x 10 viên - Điều trị nhiễm khuẩn khác ở cột: ['detail_raw_text', 'images', 'link']
Cestasin Vacopharm 500 viên khác ở cột: ['chong_chi_dinh', 'cong_dung_chi_dinh', 'dang_bao_che', 'detail_raw_text', 'images', 'link', 'luu_y', 'quy_cach_dong_goi', 'tac_dung_phu', 'thanh_phan', 'thuoc_can_ke_toa', 'tuong_tac_thuoc']
Cetazin Vacopharm 10 vỉ x 10 viên khác ở cột: ['Bao_quan', 'chong_chi_dinh', 'cong_dung_chi_dinh', 'dang_bao_che', 'detail_raw_text', 'images', 'lieu_dung', 'link', 'luu_y', 'tac_dung_phu', 'thanh_phan', 'tuong_tac_thuoc']
Cetazin Vacopharm 200 viên khác ở cột: ['Bao_quan', 'chong_chi_dinh', 'cong_dung_chi_dinh', 'dang_bao_che', 'detail_raw_text', 'images', 'lieu_dung', 'link', 'luu_y', 'tac_dung_phu', 'thanh_phan', 'tuong_tac_thuoc']
DIPRIVAN PRE-FILLED SYRING10MG/ML50ML khác ở cột: ['images', 'link', 'thuong_hieu', 'xuat_xu']
Doagithicon Agimexpharm 30ml khác ở cột: ['Bao_quan', 'cach_dung', 'cong_dung_chi_dinh', 'dang_bao_che', 'detail_raw_text', 'hoat_chat', 'images', 'lieu_dung', 'link', 'luu_y', 'nha_san_xuat', 'thanh_phan', 'thuoc_can_ke_toa']
Dostinex 0.5mg Pfizer 8 viên khác ở cột: ['images', 'link', 'quy_cach_dong_goi', 'xuat_xu']
Dầu Gió Xanh Eagle Brand Singapore 24ml khác ở cột: ['Bao_quan', 'chong_chi_dinh', 'cong_dung_chi_dinh', 'detail_raw_text', 'images', 'lieu_dung', 'link', 'luu_y', 'quy_cach_dong_goi', 'thanh_phan', 'thuong_hieu', 'xuat_xu']
FINABRAT 100 - Fenofibrat 100mg khác ở cột: ['cach_dung', 'detail_raw_text', 'link']
Fyranco 400mg Demo S.A 1 lọ x 3ml khác ở cột: ['Bao_quan', 'detail_raw_text', 'images', 'link', 'quy_cach_dong_goi', 'thanh_phan']
Kim Tiền Thảo AGP 160 Agimexpharm 60 viên khác ở cột: ['Bao_quan', 'cach_dung', 'dang_bao_che', 'detail_raw_text', 'hoat_chat', 'images', 'lieu_dung', 'link', 'luu_y', 'nha_san_xuat', 'tac_dung_phu', 'thanh_phan', 'thuoc_can_ke_toa', 'tuong_tac_thuoc']
Levnew 5mg Agimexpharm 1 vỉ x 10 viên khác ở cột: ['Bao_quan', 'dang_bao_che', 'detail_raw_text', 'hoat_chat', 'images', 'lieu_dung', 'link', 'luu_y', 'nha_san_xuat', 'tac_dung_phu', 'thanh_phan', 'thuoc_can_ke_toa']
Lipitor 40mg Pfizer 3 vỉ x 10 viên khác ở cột: ['images', 'link']
Loperamid 2mg Agimexpharm 10 vỉ x 10 viên khác ở cột: ['Bao_quan', 'cach_dung', 'dang_bao_che', 'detail_raw_text', 'hoat_chat', 'images', 'lieu_dung', 'link', 'nha_san_xuat', 'thanh_phan', 'thuoc_can_ke_toa']
Lugtils Agimexpharm 3 vỉ x 10 viên khác ở cột: ['detail_raw_text', 'images', 'lieu_dung', 'link', 'luu_y', 'tac_dung_phu', 'thanh_phan']
Lyrica 75mg Pfizer 4 vỉ x 14 viên khác ở cột: ['images', 'link', 'xuat_xu']
NUTRIFLEX PERI SOL. BAG 1000ML, Hộp 5 túi khác ở cột: ['link']
PROPOFOL-LIPURO 0.5% INJ. 20ML, Hộp 5 lọ khác ở cột: ['link']
Posinight 1 Agimexpharm 1 viên khác ở cột: ['detail_raw_text', 'images', 'link', 'thanh_phan']
Purinethol 50mg Aspen 25 viên khác ở cột: ['images', 'link', 'thuoc_can_ke_toa']
Racedagim 30mg Agimexpharm 25 gói x 3g khác ở cột: ['detail_raw_text', 'images', 'link', 'thanh_phan']
Sitagibes 100mg Agimexpharm 4 vỉ x 7 viên khác ở cột: ['Bao_quan', 'cach_dung', 'detail_raw_text', 'images', 'lieu_dung', 'link', 'luu_y', 'thanh_phan']
Sitagibes 50mg Agimexpharm 4 vỉ x 7 viên khác ở cột: ['detail_raw_text', 'images', 'link', 'thanh_phan']
Spiranisol Forte OPV 2 vỉ x 10 viên khác ở cột: ['images', 'link']
Tenofovir 300mg DHG 3 vỉ x 10 viên khác ở cột: ['images', 'link']
Thuốc Ginkor Fort, Hộp 30 viên khác ở cột: ['cach_dung', 'category', 'cong_dung_chi_dinh', 'detail_raw_text', 'images', 'lieu_dung', 'link', 'luu_y', 'thanh_phan']
Thuốc PREDNISON 5mg TW25, 500 viên khác ở cột: ['images', 'link']
Thuốc Phuzibi 140mg, Hộp 100 viên khác ở cột: ['cach_dung', 'chong_chi_dinh', 'cong_dung_chi_dinh', 'detail_raw_text', 'images', 'link', 'luu_y', 'tac_dung_phu', 'thanh_phan']
Thuốc chống đông Brilinta Ticagrelor 90mg, Hộp 60 viên khác ở cột: ['images', 'link', 'quy_cach_dong_goi', 'thuong_hieu', 'xuat_xu']
Thuốc hỗ trợ điều trị viêm khớp CELECOXID - Celecoxib 200mg khác ở cột: ['detail_raw_text', 'images', 'link', 'quy_cach_dong_goi', 'thanh_phan']
Thuốc kháng Histamin CETIRIZIN - Cetiricin dihydroclorid 10mg khác ở cột: ['images', 'link', 'quy_cach_dong_goi']
Thuốc kháng nấm METRONIZAZOL - Metronidazol 250mg khác ở cột: ['images', 'link']
Thuốc kháng sinh DOXYCYCLIN - Doxycyclin 100mg khác ở cột: ['images', 'link']
Thuốc lợi gan mật BAR, Chai 180 viên khác ở cột: ['cach_dung', 'chong_chi_dinh', 'cong_dung_chi_dinh', 'detail_raw_text', 'images', 'link', 'quy_cach_dong_goi', 'thanh_phan']
Thuốc tiểu đường Jardiance 25mg, Hộp 30 viên khác ở cột: ['chong_chi_dinh', 'cong_dung_chi_dinh', 'detail_raw_text', 'images', 'lieu_dung', 'link', 'tac_dung_phu', 'thanh_phan', 'thuong_hieu', 'tuong_tac_thuoc']
Thuốc ung thư Methotrexate 2.5mg 24 viên khác ở cột: ['images', 'link', 'thuong_hieu', 'xuat_xu']
Utrahealth F.C Tablet Standard 10 vỉ x 10 viên khác ở cột: ['images', 'link']
Vaco-Piracetam 400mg Vacopharm 10 vỉ x 10 viên – Thuốc điều trị chóng mặt, suy giảm trí nhớ khác ở cột: ['dang_bao_che', 'images', 'link']
Valsgim 160mg Agimexpharm 2 vỉ x 14 viên khác ở cột: ['detail_raw_text', 'images', 'link', 'thanh_phan']
Valsgim 80mg Agimexpharm 2 vỉ x 14 viên khác ở cột: ['detail_raw_text', 'images', 'link', 'thanh_phan']
Valsgim H 160/12.5 Agimexpharm 2 vỉ x 14 viên khác ở cột: ['detail_raw_text', 'images', 'link', 'tac_dung_phu']
Valsgim H 80mg Agimexpharm 2 vỉ x 14 viên khác ở cột: ['detail_raw_text', 'images', 'link', 'thanh_phan']
Viên sủi Ca-C 1000mg Sandoz Orange, Tube 10 viên khác ở cột: ['cach_dung', 'cong_dung_chi_dinh', 'detail_raw_text', 'images', 'lieu_dung', 'link', 'luu_y', 'quy_cach_dong_goi', 'tac_dung_phu', 'tuong_tac_thuoc', 'xuat_xu']
Viên uống bổ sung Vitamin B COMPLEX C khác ở cột: ['images', 'link']
Viên uống bổ sung Vitamin B1 250mg khác ở cột: ['images', 'link']

In [32]:
# Lấy 1 trường hợp có tên thuốc trùng nhau nhưng nội dung khác nhau để xem chi tiết
example_name = duplicate_name_groups[1]
example_rows = non_nan_duplicate_names[non_nan_duplicate_names['name'] == example_name]
print(f"Chi tiết các dòng có tên thuốc '{example_name}' trùng nhau nhưng nội dung khác nhau:")
example_rows

Chi tiết các dòng có tên thuốc 'Acetab 325 Agimexpharm 10 vỉ x 10 viên' trùng nhau nhưng nội dung khác nhau:

,category,link,name,images,error,hoat_chat,quy_cach_dong_goi,thuong_hieu,xuat_xu,thuoc_can_ke_toa,...,thanh_phan,cong_dung_chi_dinh,lieu_dung,cach_dung,luu_y,chong_chi_dinh,tac_dung_phu,tuong_tac_thuoc,Bao_quan,detail_raw_text
5606,"Thuốc kháng viêm, giảm đau & hạ sốt",https://nhathuocminhchau.com.vn/acetab-325-agi...,Acetab 325 Agimexpharm 10 vỉ x 10 viên,https://cdn.famitaa.net/storage/uploads/images...,NaN,Paracetamol (Acetaminophen),100 viên,Agimexpharm,Việt Nam,Không,...,Paracetamol 325mg.,"Hạ sốt.\nGiảm đau từ nhẹ đến vừa: Nhức đầu, đa...",Liều thường dùng như sau:\nNgười lớn: Uống 1 –...,"Dùng theo đường uống, không được dùng paraceta...",Paracetamol tương đối không độc với liều điều ...,Quá mẫn cảm với paracetamol hoặc với bất cứ th...,Phản ứng da nghiêm trọng như hội chứng Stevens...,Không dùng chung với các thuốc khác có chứa pa...,"Bảo quản nơi khô thoáng, tránh ánh nắng trực t...",Thành phần\nParacetamol 325mg.\nCông dụng (Chỉ...
5607,"Thuốc kháng viêm, giảm đau & hạ sốt",https://nhathuocminhchau.com.vn/acetab-325-agi...,Acetab 325 Agimexpharm 10 vỉ x 10 viên,https://cdn.famitaa.net/storage/uploads/images...,NaN,Paracetamol (Acetaminophen),100 viên,Agimexpharm,Việt Nam,Không,...,Paracetamol 325mg.,Điều trị các chứng đau và sốt từ nhẹ đến vừa.\...,"Trẻ em từ 2 – 5 tuổi: Uống ½ viên/ lần, 3 – 4 ...",NaN,Khi dùng chung với các thuốc khác có chứa Para...,Quá mẫn cảm với Paracetamol.\nNgười suy gan ha...,Paracetamol hầu như không gây tác dụng không m...,Uống dài ngày liều cao Paracetamol làm tăng nh...,"Bảo quản nơi khô thoáng, tránh ánh nắng trực t...",Thành phần\nParacetamol 325mg.\nCông dụng (Chỉ...