In [1]:
import pandas as pd
import numpy as np
import re
import unicodedata

In [2]:
minhchau_df = pd.read_csv(r'D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_MinhChau\minhchau_medicines_data.csv')
cleaned_df = minhchau_df.copy()
print(cleaned_df.shape)
cleaned_df.info()
cleaned_df.head()

(9544, 24)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9544 entries, 0 to 9543
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   category            9544 non-null   object
 1   link                9544 non-null   object
 2   name                9265 non-null   object
 3   images              9266 non-null   object
 4   error               253 non-null    object
 5   hoat_chat           4146 non-null   object
 6   quy_cach_dong_goi   8493 non-null   object
 7   thuong_hieu         7867 non-null   object
 8   xuat_xu             8764 non-null   object
 9   thuoc_can_ke_toa    4108 non-null   object
 10  dang_bao_che        4242 non-null   object
 11  ham_luong           0 non-null      float64
 12  nha_san_xuat        4251 non-null   object
 13  tieu_chuan          1367 non-null   object
 14  thanh_phan          8931 non-null   object
 15  cong_dung_chi_dinh  9057 non-null   object
 16  lieu_dung           6648 non-null   object
 17  cach_dung           5139 non-null   object
 18  luu_y               6496 non-null   object
 19  chong_chi_dinh      8303 non-null   object
 20  tac_dung_phu        8048 non-null   object
 21  tuong_tac_thuoc     6665 non-null   object
 22  Bao_quan            4992 non-null   object
 23  detail_raw_text     9080 non-null   object
dtypes: float64(1), object(23)
memory usage: 1.7+ MB

,category,link,name,images,error,hoat_chat,quy_cach_dong_goi,thuong_hieu,xuat_xu,thuoc_can_ke_toa,...,thanh_phan,cong_dung_chi_dinh,lieu_dung,cach_dung,luu_y,chong_chi_dinh,tac_dung_phu,tuong_tac_thuoc,Bao_quan,detail_raw_text
0,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/apilevo-500-ap...,Apilevo 500 Apimed 3 vỉ x 10 viên,https://cdn.famitaa.net/storage/uploads/images...,NaN,Levofloxacin,Hộp 3 vỉ x 10 viên,Apimed,Việt Nam,Có,...,Levofloxacin: 500mg.,Viêm phổi mắc phải cộng đồng.\nNhiễm khuẩn đườ...,Liều dùng của viên nén levofloxacin: Dùng 1 – ...,Thuốc dùng đường uống.\nUống nguyên viên thuốc...,Các phản ứng có hại nghiêm trọng có khả năng k...,Bệnh nhân quá mẫn với levofloxacin hoặc các qu...,"Trong mỗi nhóm phân loại theo tần suất, các tá...","Ảnh hưởng của các thuốc khác:\nMuối sắt, muối ...","Nơi khô, tránh ánh sáng, nhiệt độ dưới 30°C.",Thành phần\nLevofloxacin: 500mg.\nCông dụng (C...
1,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/vigentin-87512...,Vigentin 875/125 DT. Pharbaco 2 vỉ x 7 viên (A...,https://cdn.famitaa.net/storage/uploads/images...,NaN,Amoxicillin/Acid Clavulanic,Hộp 2 vỉ x 7 viên,Pharbaco,Việt Nam,Có,...,Amoxicillin trihydrat: 875mg\nAcid clavulanic:...,Các chế phẩm amoxicilin và kali clavulanat đượ...,Liều lượng thường được biểu thị dưới dạng amox...,Dùng đường uống.,"Chú ý đến người già, người bệnh có tiền sử vàn...",Dị ứng với nhóm beta-lactam (các penicilin và ...,Các tác dụng không mong muốn thường có liên qu...,Thuốc có thể gây kéo dài thời gian chảy máu và...,"Nơi khô, tránh ánh sáng, nhiệt độ dưới 30°C.",Thành phần\nAmoxicillin trihydrat: 875mg\nAcid...
2,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/novofenti-200m...,Novofenti 200mg CPC1 Hà Nội 1 vỉ x 3 viên,https://cdn.famitaa.net/storage/uploads/images...,NaN,Fenticonazole,3 viên,CPC1,Việt Nam,Có,...,Fenticonazol nitrat: 200mg.,Novofenti được chỉ định dùng cho các trường hợ...,Người lớn và trẻ trên 16 tuổi:\nĐặt một viên N...,Đặt âm đạo.,Không nên sử dụng kết hợp với các biện pháp tr...,Mẫn cảm với các thành phần của sản phẩm và các...,Sau khi điều trị có thể xảy ra tái phát nhẹ sa...,"Không được thống kê.\nThành phần dầu, chất béo...","Nơi khô, tránh ánh sáng, nhiệt độ dưới 30°C.",Thành phần\nFenticonazol nitrat: 200mg.\nCông ...
3,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/cotrimoxazol-4...,Cotrimoxazol 480mg Thephaco 20 vỉ x 20 viên (S...,https://cdn.famitaa.net/storage/uploads/images...,NaN,Trimethoprim/Sulfamethoxazole,Hộp 20 vỉ x 20 viên,Thephaco,Việt Nam,Có,...,Sulfamethoxazol: 400mg\nTrimethoprim: 80mg,Viêm tai giữa cấp.\nNhiễm khuẩn đường tiết niệ...,Viêm tai giữa cấp: Trẻ em từ 2 tháng tuổi trở ...,Cotrimoxazol 480mg được uống cùng với thức ăn ...,Viêm họng do S.Pyogenes: Không nên dùng Cotrim...,Bệnh nhân quá mẫn với sulfamethoxazole hay tri...,"Thường gặp (1/100 ≤ ADR < 1/10):\nBuồn nôn, nô...",Warfarin: Cotrimoxazol 480mg có thế kéo dài th...,"Nơi khô, tránh ánh sáng, nhiệt độ dưới 30°C.",Thành phần\nSulfamethoxazol: 400mg\nTrimethopr...
4,"Thuốc kháng sinh, Kháng nấm",https://nhathuocminhchau.com.vn/fungafin-10mg-...,Fungafin 10mg CPC1 Hà Nội lọ 15ml,https://cdn.famitaa.net/storage/uploads/images...,NaN,Terbinafine,15ml,CPC1,Việt Nam,Không,...,Terbinafin hydroclorid: 10mg.,Nhiễm nấm da gây ra bởi các loại nấm như Trich...,Người lớn và trẻ em lớn hơn 16 tuổi: Sử dụng 1...,Rửa sạch và lau khô vùng da bị nhiễm nấm trước...,Thận trọng với bệnh nhân có tổn thương mà có t...,Mẫn cảm với terbinafin hydroclorid hoặc bất cứ...,"Các triệu chứng tại chỗ như ngứa, ban da tróc ...",Chưa có thông tin về sự tương tác giữa terbina...,"Nơi khô, tránh ánh sáng, nhiệt độ dưới 30°C.",Thành phần\nTerbinafin hydroclorid: 10mg.\nCôn...

In [3]:
# Loại bỏ cột trống hoàn toàn
cleaned_df = cleaned_df.dropna(axis=1, how='all')
print(f"Sau khi loại bỏ cột trống hoàn toàn{cleaned_df.shape}")

Sau khi loại bỏ cột trống hoàn toàn(9544, 23)

In [4]:
missing_token = {"", "nan", "none", "null", "na", "n/a", "không có", "-"}
def norm_text(x):
    if pd.isna(x):
        return np.nan
    s = str(x).strip()
    s = unicodedata.normalize("NFC", s)
    s = re.sub(r"\s+", " ", s)  
    return s

def to_missing(x):
    if pd.isna(x):
        return np.nan
    s = str(x).strip().lower()
    return np.nan if s in missing_token else x

# Chuẩn hóa toàn bộ cột object
obj_cols = cleaned_df.select_dtypes(include=["object"]).columns
for c in obj_cols:
    cleaned_df[c] = cleaned_df[c].map(norm_text).map(to_missing)

In [5]:
if "error" not in cleaned_df.columns:
    cleaned_df["error"] = np.nan

cleaned_df["has_error"] = cleaned_df["error"].notna()
cleaned_df["is_unknown_error"] = cleaned_df["error"].str.contains("unknown error", case=False, na=False)
cleaned_df["error_type"] = cleaned_df["error"].str.extract(r"^([A-Za-z_]+Error|[A-Za-z_]+Exception)", expand=False)

quarantine_df = cleaned_df[cleaned_df["has_error"]].copy()
work_df = cleaned_df[~cleaned_df["has_error"]].copy()

print("raw_df:", minhchau_df.shape)
print("clean_df:", cleaned_df.shape)
print("work_df (không lỗi):", work_df.shape)
print("quarantine_df (có lỗi):", quarantine_df.shape)

raw_df: (9544, 24)
clean_df: (9544, 26)
work_df (không lỗi): (9291, 26)
quarantine_df (có lỗi): (253, 26)

In [6]:
# Các cột hay cần union
UNION_PIPE_COLS = [c for c in ["images", "category"] if c in work_df.columns]

def is_empty(v):
    return pd.isna(v) or str(v).strip() == ""

def pick_longest(series):
    vals = [str(v).strip() for v in series if not is_empty(v)]
    if not vals:
        return np.nan
    # Ưu tiên chuỗi dài nhất (thường nhiều thông tin hơn)
    return max(vals, key=len)

def union_pipe(series):
    vals = []
    for v in series.dropna():
        parts = [p.strip() for p in str(v).split("|") if p.strip()]
        vals.extend(parts)
    if not vals:
        return np.nan
    # giữ thứ tự xuất hiện
    uniq = list(dict.fromkeys(vals))
    return " | ".join(uniq)

def merge_group(g):
    out = {}
    for c in g.columns:
        if c in UNION_PIPE_COLS:
            out[c] = union_pipe(g[c])
        elif c == "error":
            # trong work_df thường rỗng, vẫn xử lý an toàn
            non_empty = [str(v).strip() for v in g[c] if not is_empty(v)]
            out[c] = " || ".join(dict.fromkeys(non_empty)) if non_empty else np.nan
        else:
            out[c] = pick_longest(g[c])
    out["n_rows_merged_link"] = len(g)
    return pd.Series(out)

if "link" in work_df.columns:
    dedup_link_df = work_df.groupby("link", dropna=False, as_index=False).apply(merge_group).reset_index(drop=True)
else:
    dedup_link_df = work_df.copy()
    dedup_link_df["n_rows_merged_link"] = 1

print("Sau gộp theo link:", dedup_link_df.shape)

Sau gộp theo link: (9291, 27)

C:\Users\Admin\AppData\Local\Temp\ipykernel_36560\123271309.py:40: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  dedup_link_df = work_df.groupby("link", dropna=False, as_index=False).apply(merge_group).reset_index(drop=True)

In [7]:
def normalize_name(s):
    if pd.isna(s):
        return np.nan
    x = str(s).strip().lower()
    x = unicodedata.normalize("NFC", x)
    x = re.sub(r"\s+", " ", x)
    return x

if "name" in dedup_link_df.columns:
    name_stage = dedup_link_df.copy()
    name_stage["name_norm"] = name_stage["name"].map(normalize_name)

    # chỉ gộp những dòng có name_norm; dòng name trống giữ nguyên
    has_name = name_stage["name_norm"].notna()
    a = name_stage[has_name].copy()
    b = name_stage[~has_name].copy()

    dedup_name_df = (
        a.groupby("name_norm", dropna=False, as_index=False)
         .apply(merge_group)
         .reset_index(drop=True)
    )

    # bỏ name_norm phụ
    if "name_norm" in dedup_name_df.columns:
        dedup_name_df = dedup_name_df.drop(columns=["name_norm"], errors="ignore")

    final_df = pd.concat([dedup_name_df, b.drop(columns=["name_norm"], errors="ignore")], ignore_index=True)
else:
    final_df = dedup_link_df.copy()

print("Sau gộp theo name:", final_df.shape)

Sau gộp theo name: (9237, 27)

C:\Users\Admin\AppData\Local\Temp\ipykernel_36560\308624143.py:20: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(merge_group)

In [8]:
def contains_any(text, keywords):
    if pd.isna(text):
        return False
    t = str(text).lower()
    return any(k in t for k in keywords)

# Cờ nghi ngờ: chống chỉ định bị rơi vào chỉ định
if {"cong_dung_chi_dinh", "chong_chi_dinh"}.issubset(final_df.columns):
    final_df["contra_suspect"] = (
        final_df["chong_chi_dinh"].isna()
        & final_df["cong_dung_chi_dinh"].map(lambda x: contains_any(x, ["chống chỉ định", "không sử dụng", "không dùng", "cấm dùng"]))
    )
else:
    final_df["contra_suspect"] = False

# Cờ nghi ngờ: tương tác thuốc bị thiếu
if {"cong_dung_chi_dinh", "tuong_tac_thuoc"}.issubset(final_df.columns):
    final_df["interaction_suspect"] = (
        final_df["tuong_tac_thuoc"].isna()
        & final_df["cong_dung_chi_dinh"].map(lambda x: contains_any(x, ["tương tác", "dùng chung", "kết hợp thuốc"]))
    )
else:
    final_df["interaction_suspect"] = False

important_cols = [c for c in [
    "name", "category", "link", "images",
    "thanh_phan", "cong_dung_chi_dinh", "chong_chi_dinh",
    "tac_dung_phu", "tuong_tac_thuoc", "Bao_quan", "error"
] if c in final_df.columns]

report = pd.DataFrame({
    "column": important_cols,
    "non_null": [final_df[c].notna().sum() for c in important_cols],
    "null": [final_df[c].isna().sum() for c in important_cols],
    "fill_rate_%": [round(final_df[c].notna().mean() * 100, 2) for c in important_cols]
}).sort_values("fill_rate_%", ascending=False)

print("=== Quality report ===")
display(report)

print("\nSố dòng contra_suspect:", int(final_df["contra_suspect"].sum()))
print("Số dòng interaction_suspect:", int(final_df["interaction_suspect"].sum()))

=== Quality report ===

                column  non_null  null  fill_rate_%
1             category      9237     0       100.00
2                 link      9237     0       100.00
3               images      9212    25        99.73
0                 name      9211    26        99.72
5   cong_dung_chi_dinh      9004   233        97.48
4           thanh_phan      8879   358        96.12
6       chong_chi_dinh      8254   983        89.36
7         tac_dung_phu      8005  1232        86.66
8      tuong_tac_thuoc      6625  2612        71.72
9             Bao_quan      4960  4277        53.70
10               error         0  9237         0.00

Số dòng contra_suspect: 15
Số dòng interaction_suspect: 13

In [10]:
def pick_by_kw(text, kws):
    if pd.isna(text): 
        return pd.NA
    s = str(text)
    low = s.lower()
    hits = [low.find(k) for k in kws if k in low]
    if not hits:
        return pd.NA
    i = min(hits)
    return s[i:].strip()

# fill chong_chi_dinh nếu đang rỗng
m1 = final_df["chong_chi_dinh"].isna()
final_df.loc[m1, "chong_chi_dinh"] = final_df.loc[m1, "cong_dung_chi_dinh"].map(
    lambda x: pick_by_kw(x, ["chống chỉ định", "không sử dụng", "không dùng", "cấm dùng"])
)

# fill tuong_tac_thuoc nếu đang rỗng
m2 = final_df["tuong_tac_thuoc"].isna()
final_df.loc[m2, "tuong_tac_thuoc"] = final_df.loc[m2, "cong_dung_chi_dinh"].map(
    lambda x: pick_by_kw(x, ["tương tác", "dùng chung", "kết hợp thuốc"])
)

# cập nhật lại suspect
final_df["contra_suspect"] = final_df["chong_chi_dinh"].isna() & final_df["cong_dung_chi_dinh"].str.contains(
    "chống chỉ định|không sử dụng|không dùng|cấm dùng", case=False, na=False
)
final_df["interaction_suspect"] = final_df["tuong_tac_thuoc"].isna() & final_df["cong_dung_chi_dinh"].str.contains(
    "tương tác|dùng chung|kết hợp thuốc", case=False, na=False
)

print("contra_suspect:", int(final_df["contra_suspect"].sum()))
print("interaction_suspect:", int(final_df["interaction_suspect"].sum()))

contra_suspect: 0
interaction_suspect: 0

In [12]:
print(final_df.columns)
final_df.info()

Index(['category', 'link', 'name', 'images', 'error', 'hoat_chat',
       'quy_cach_dong_goi', 'thuong_hieu', 'xuat_xu', 'thuoc_can_ke_toa',
       'dang_bao_che', 'nha_san_xuat', 'tieu_chuan', 'thanh_phan',
       'cong_dung_chi_dinh', 'lieu_dung', 'cach_dung', 'luu_y',
       'chong_chi_dinh', 'tac_dung_phu', 'tuong_tac_thuoc', 'Bao_quan',
       'detail_raw_text', 'has_error', 'is_unknown_error', 'error_type',
       'n_rows_merged_link', 'contra_suspect', 'interaction_suspect'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9237 entries, 0 to 9236
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   category             9237 non-null   object
 1   link                 9237 non-null   object
 2   name                 9211 non-null   object
 3   images               9212 non-null   object
 4   error                0 non-null      float64
 5   hoat_chat            4132 non-null   object
 6   quy_cach_dong_goi    8446 non-null   object
 7   thuong_hieu          7826 non-null   object
 8   xuat_xu              8713 non-null   object
 9   thuoc_can_ke_toa     4095 non-null   object
 10  dang_bao_che         4228 non-null   object
 11  nha_san_xuat         4237 non-null   object
 12  tieu_chuan           1366 non-null   object
 13  thanh_phan           8879 non-null   object
 14  cong_dung_chi_dinh   9004 non-null   object
 15  lieu_dung            6612 non-null   object
 16  cach_dung            5115 non-null   object
 17  luu_y                6456 non-null   object
 18  chong_chi_dinh       8269 non-null   object
 19  tac_dung_phu         8005 non-null   object
 20  tuong_tac_thuoc      6638 non-null   object
 21  Bao_quan             4960 non-null   object
 22  detail_raw_text      9027 non-null   object
 23  has_error            9237 non-null   object
 24  is_unknown_error     9237 non-null   object
 25  error_type           0 non-null      float64
 26  n_rows_merged_link   9237 non-null   int64
 27  contra_suspect       9237 non-null   bool
 28  interaction_suspect  9237 non-null   bool
dtypes: bool(2), float64(2), int64(1), object(24)
memory usage: 1.9+ MB

In [ ]:
# Loại bỏ cột rõng và không cần thiết
final_df = final_df.drop(columns=["error", "has_error", "is_unknown_error", "error_type","contra_suspect","interaction_suspect","n_rows_merged_link"], errors="ignore")

In [14]:
print(final_df.columns)
final_df.info()

Index(['category', 'link', 'name', 'images', 'hoat_chat', 'quy_cach_dong_goi',
       'thuong_hieu', 'xuat_xu', 'thuoc_can_ke_toa', 'dang_bao_che',
       'nha_san_xuat', 'tieu_chuan', 'thanh_phan', 'cong_dung_chi_dinh',
       'lieu_dung', 'cach_dung', 'luu_y', 'chong_chi_dinh', 'tac_dung_phu',
       'tuong_tac_thuoc', 'Bao_quan', 'detail_raw_text'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9237 entries, 0 to 9236
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   category            9237 non-null   object
 1   link                9237 non-null   object
 2   name                9211 non-null   object
 3   images              9212 non-null   object
 4   hoat_chat           4132 non-null   object
 5   quy_cach_dong_goi   8446 non-null   object
 6   thuong_hieu         7826 non-null   object
 7   xuat_xu             8713 non-null   object
 8   thuoc_can_ke_toa    4095 non-null   object
 9   dang_bao_che        4228 non-null   object
 10  nha_san_xuat        4237 non-null   object
 11  tieu_chuan          1366 non-null   object
 12  thanh_phan          8879 non-null   object
 13  cong_dung_chi_dinh  9004 non-null   object
 14  lieu_dung           6612 non-null   object
 15  cach_dung           5115 non-null   object
 16  luu_y               6456 non-null   object
 17  chong_chi_dinh      8269 non-null   object
 18  tac_dung_phu        8005 non-null   object
 19  tuong_tac_thuoc     6638 non-null   object
 20  Bao_quan            4960 non-null   object
 21  detail_raw_text     9027 non-null   object
dtypes: object(22)
memory usage: 1.6+ MB

In [15]:
final_df.to_csv("minhchau_medicines_data_cleaned.csv", index=False)