In [1]:
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException 
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import re
import time

In [2]:
def set_up_driver():
    chrome_options = Options()
    chrome_options.add_argument("--headless") 
    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument("start-maximized")
    chrome_options.add_argument("--disable-blink-features=AutomationControlled") # Tắt tính năng phát hiện tự động của trình duyệt
    chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"]) # Loại bỏ thông báo "Chrome is being controlled by automated test software"
    chrome_options.add_experimental_option('useAutomationExtension', False) # Vô hiệu hóa tiện ích mở rộng tự động hóa
    driver = webdriver.Chrome(options=chrome_options)
    return driver

In [3]:
pharmacity_df = pd.read_csv("pharmacity_medicines_data_demo(4).csv")
pharmacity_df.shape[0]
pharmacity_df.tail()

,name,price,images,nha_san_xuat,noi_san_xuat,thuoc_can_ke_don,hoat_chat,chi_dinh_tom_tat,dang_bao_che,quy_cach,...,huong_dan_su_dung,cach_su_dung,than_trong,thong_tin_san_xuat,url,category,drug_type,category_link,category_name,error
2195,"Viên nén Gensler 5mg điều trị tăng huyết áp, s...",NaN,['https://prod-cdn.pharmacity.io/e-com/images/...,Davipharm,NaN,NaN,Ramipril,"Điều trị tăng huyết áp, suy tim",Viên nén,10 vỉ x 10 viên,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/gensler-5mg-hop-10-v...,"Thuốc tim mạch, huyết áp",Thuốc kê đơn,https://www.pharmacity.vn/rx-thuoc-tim-mach-hu...,"Thuốc tim mạch, huyết áp",NaN
2196,Viên nén Fenostad 160mg điều trị rối loạn mỡ m...,NaN,['https://prod-cdn.pharmacity.io/e-com/images/...,STELLA,NaN,NaN,Fenofibrat,Điều trị rối loạn mỡ máu,Viên nén,3 vỉ x 10 viên,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/fenostad-160-hop-3-v...,"Thuốc tim mạch, huyết áp",Thuốc kê đơn,https://www.pharmacity.vn/rx-thuoc-tim-mach-hu...,"Thuốc tim mạch, huyết áp",NaN
2197,Viên nén Irbesartan Domesco 150mg điều trị tăn...,NaN,['https://prod-cdn.pharmacity.io/e-com/images/...,Domesco,NaN,NaN,Irbesartan,Điều trị tăng huyết áp,Viên nén,2 vỉ x 14 viên,...,"Tác dụng phụ\n\nThường gặp, ADR >1/100\n\nToàn...",NaN,"Thông tin sản xuất\nBảo quản: Dưới 30°C, tránh...",NaN,https://www.pharmacity.vn/irbesartan-150mg-2-v...,"Thuốc tim mạch, huyết áp",Thuốc kê đơn,https://www.pharmacity.vn/rx-thuoc-tim-mach-hu...,"Thuốc tim mạch, huyết áp",NaN
2198,Viên nén Ihybes 150mg điều trị tăng huyết áp (...,NaN,['https://prod-cdn.pharmacity.io/e-com/images/...,Agimexpharm,NaN,NaN,Irbesartan,Điều trị tăng huyết áp,Viên nén bao phim,3 vỉ x 10 viên,...,Tác dụng phụ\nThường gặp (ADR > 1/100):\n\nThầ...,NaN,"Bảo quản\nNhiệt độ dưới 30oC, tránh ẩm và ánh ...",NaN,https://www.pharmacity.vn/ihybes-150-3-vi-x-10...,"Thuốc tim mạch, huyết áp",Thuốc kê đơn,https://www.pharmacity.vn/rx-thuoc-tim-mach-hu...,"Thuốc tim mạch, huyết áp",NaN
2199,Viên nén Dogrel Savi 75mg phòng ngừa thành lập...,NaN,['https://prod-cdn.pharmacity.io/e-com/images/...,Savi,NaN,NaN,Clopidogrel,"Phòng ngừa thành lập cục máu đông, huyết khối",Viên nén bao phim,3 vỉ x 10 viên,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/dogrel-savi-75mg-3-v...,"Thuốc tim mạch, huyết áp",Thuốc kê đơn,https://www.pharmacity.vn/rx-thuoc-tim-mach-hu...,"Thuốc tim mạch, huyết áp",NaN

In [4]:
pharmcity_copy_df = pharmacity_df.copy()
pharmcity_copy_df.isnull().sum()

name                   482
price                 1169
images                 469
nha_san_xuat           548
noi_san_xuat          1884
thuoc_can_ke_don      1649
hoat_chat              632
chi_dinh_tom_tat       657
dang_bao_che           638
quy_cach               711
luu_y                  674
mo_ta                 1495
thanh_phan            1088
chi_dinh_chi_tiet     1365
huong_dan_su_dung     1092
cach_su_dung          2200
than_trong            1339
thong_tin_san_xuat    2200
url                      0
category               469
drug_type              469
category_link          469
category_name          469
error                 1731
dtype: int64

In [5]:
pharmcity_copy_df.iloc[1031:1250, 0:10]

,name,price,images,nha_san_xuat,noi_san_xuat,thuoc_can_ke_don,hoat_chat,chi_dinh_tom_tat,dang_bao_che,quy_cach
1031,Dung dịch uống Atiferlit 50mg/5ml An Thiên bổ ...,17.333 ₫/Ống,['https://prod-cdn.pharmacity.io/e-com/images/...,An Thien,NaN,Không,Sắt nguyên tố (dưới dạng Sắt (III) hydroxyd po...,Dung dịch thuốc uống Atiferlit giúp bổ sung th...,Dung dịch uống,Hộp 30 ống x 10ml
1032,Elnitine Stella (Hop 20 ong 10ml),80.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,STELLA,NaN,Không,"Calci glyceroposphat, Magnesium gluconate.",Bổ sung calcium và magnesium trong một số trườ...,Dung dịch uống,Hộp 20 ống 10ml
1033,Viên nén sủi bọt CalciumBoston 500mg bổ sung c...,58.990 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Boston,NaN,Không,Calcium (different salts in combination),NaN,Viên nén sủi bọt,NaN
1034,Enat 400 (3 vỉ x 10 viên) Mã mới – Bổ sung vit...,45.000 ₫/Vỉ,['https://prod-cdn.pharmacity.io/e-com/images/...,Mega Lifesciences,NaN,Không,Vitamin E 400IU,"Ngăn ngừa lão hóa da, điều trị dự phòng thiếu ...",Viên nang,3 vỉ x 10 viên
1035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1248,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
def get_product_information(driver, label):
    try:
        # Tìm tất cả p tags có class text-sm (chứa label)
        labels = driver.find_elements(By.CSS_SELECTOR, "p[class*='text-sm'][class*='leading-14']")
        
        for label_el in labels:
            label_text = label_el.text.strip()
            
            if label.lower() in label_text.lower():
                # Lấy parent div grid rồi tìm value trong sibling
                parent = label_el.find_element(By.XPATH, "./ancestor::div[contains(@class, 'grid')][1]")
                # Tìm div chứa text value (không phải label)
                value_els = parent.find_elements(By.CSS_SELECTOR, "div")
                
                for val in value_els:
                    val_text = val.text.strip()
                    # Lấy value khác label
                    if val_text and val_text != label_text:
                        return val_text
    except:
        return None

In [7]:
def get_section_detail(driver, section_id):
    try:
        # Tìm element theo id
        heading = driver.find_element(By.ID, section_id)
        
        # Lấy siblings trực tiếp từ heading
        siblings = heading.find_elements(By.XPATH, "./following-sibling::*")
        
        content = []
        for sib in siblings:
            tag = sib.tag_name.lower()
            
            # Dừng khi gặp heading tiếp theo (h2 hoặc h3)
            if tag in ["h2", "h3"]:
                break
            
            # Lấy text
            t = sib.get_attribute("textContent") or ""
            t = t.strip()
            if t:
                content.append(t)
        
        return "\n".join(content) if content else None
    
    except:
        None

In [8]:
def get_product_images(driver):
    images = []
    
    try:
        # Tìm tất cả img elements trong product detail
        img_elements = driver.find_elements(By.CSS_SELECTOR, "img[src*='production-cdn'], img[src*='pharmacity']")
        
        for img in img_elements:
            src = img.get_attribute("src")
            
            # Nếu src rỗng, thử lấy từ srcset hoặc data-src
            if not src:
                src = img.get_attribute("srcset") or img.get_attribute("data-src")
            
            if src:
                # Extract URL đầy đủ từ production-cdn.pharmacity.io
                match = re.search(r'(https://production-cdn\.pharmacity\.io/[^\s]+)', src)
                if match:
                    url = match.group(1).split()[0]  # Loại bỏ size info nếu có
                    if url not in images:
                        images.append(url)
                # Hoặc lấy trực tiếp nếu là URL hợp lệ
                elif src.startswith('http') and 'pharmacity' in src:
                    if src not in images:
                        images.append(src)
    
    except Exception as e:
        print(f"Error getting images: {e}")
    
    return images

In [9]:
def get_medicine_data(driver):
    try:
        WebDriverWait(driver, 3).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.mb-4.grid.grid-cols-1.gap-6.lg\:grid-cols-2.lg\:items-start > div.grid.grid-cols-1.gap-4 > div > div > div.flex.flex-col.gap-4")))
    except:
        pass

    try:
        name = driver.find_element(By.XPATH, "//*[@id='pmc-v2']/div[4]/div/div[1]/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/h2").text.strip()
        time.sleep(1)
    except:
        name = None
    
    try:
        price = driver.find_element(By.CSS_SELECTOR, "#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.mb-4.grid.grid-cols-1.gap-6.lg\:grid-cols-2.lg\:items-start > div.grid.grid-cols-1.gap-4 > div > div > div.flex.flex-col.gap-4 > div.rounded-xs.bg-surface-canvas > div > div.flex.flex-row.items-center.gap-2 > h3").text.strip()
        time.sleep(1)
    except:
        price = None

    images = get_product_images(driver)
    time.sleep(1)

    nha_san_xuat = get_product_information(driver, "Nhà sản xuất:")
    noi_san_xuat = get_product_information(driver, "Nơi sản xuất:")
    thuoc_can_ke_don = get_product_information(driver, "Thuốc cần kê đơn:")
    hoat_chat = get_product_information(driver,"Hoạt chất:")
    chi_dinh_tom_tat = get_product_information(driver, "Chỉ định:")
    dang_bao_che = get_product_information(driver, "Dạng bào chế:")
    quy_cach = get_product_information(driver, "Quy cách:")
    luu_y = get_product_information(driver, "Lưu ý:")
    
    try:
        time.sleep(1)
        btn_section = driver.find_element(By.CSS_SELECTOR,"#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.relative.left-1\/2.right-1\/2.-ml-\[50vw\].-mr-\[50vw\].w-screen.bg-surface-neutral-canvas > div > div:nth-child(1) > div > div.max-md\:pb-2.md\:h-auto.md\:max-h-\[inherit\] > div > div.relative.flex.items-center.justify-center")
        time.sleep(1)
        btn = btn_section.find_element(By.TAG_NAME, "button")
        driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", btn)
        time.sleep(1)
        btn.click()
        time.sleep(1)
    except Exception as e:
        print(f"Error clicking 'Xem thêm' button: {e}")


    mo_ta = get_section_detail(driver, "mo-ta")
    thanh_phan = get_section_detail(driver, "thanh-phan")
    chi_dinh_chi_tiet = get_section_detail(driver, "chi-dinh")
    huong_dan_su_dung = get_section_detail(driver, "huong-dan-su-dung")
    cach_su_dung = get_section_detail(driver, "cach-su-dung")
    than_trong = get_section_detail(driver, "than-trong")
    thong_tin_san_xuat = get_section_detail(driver, "thong-tin-san-xuat")

    return {
        "name": name,
        "price": price,
        "images": images,
        "nha_san_xuat": nha_san_xuat,
        "noi_san_xuat": noi_san_xuat,
        "thuoc_can_ke_don": thuoc_can_ke_don,
        "hoat_chat": hoat_chat,
        "chi_dinh_tom_tat": chi_dinh_tom_tat,
        "dang_bao_che": dang_bao_che,
        "quy_cach": quy_cach,
        "luu_y": luu_y,
        "mo_ta": mo_ta,
        "thanh_phan": thanh_phan,
        "chi_dinh_chi_tiet": chi_dinh_chi_tiet,
        "huong_dan_su_dung": huong_dan_su_dung,
        "cach_su_dung": cach_su_dung,
        "than_trong": than_trong,
        "thong_tin_san_xuat": thong_tin_san_xuat
    }

<>:3: SyntaxWarning: invalid escape sequence '\['
<>:14: SyntaxWarning: invalid escape sequence '\['
<>:33: SyntaxWarning: invalid escape sequence '\['
<>:3: SyntaxWarning: invalid escape sequence '\['
<>:14: SyntaxWarning: invalid escape sequence '\['
<>:33: SyntaxWarning: invalid escape sequence '\['
C:\Users\Admin\AppData\Local\Temp\ipykernel_29432\832258993.py:3: SyntaxWarning: invalid escape sequence '\['
  WebDriverWait(driver, 3).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.mb-4.grid.grid-cols-1.gap-6.lg\:grid-cols-2.lg\:items-start > div.grid.grid-cols-1.gap-4 > div > div > div.flex.flex-col.gap-4")))
C:\Users\Admin\AppData\Local\Temp\ipykernel_29432\832258993.py:14: SyntaxWarning: invalid escape sequence '\['
  price = driver.find_element(By.CSS_SELECTOR, "#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.mb-4.grid.grid-cols-1.gap-6.lg\:grid-cols-2.lg\:items-start > div.grid.grid-cols-1.gap-4 > div > div > div.flex.flex-col.gap-4 > div.rounded-xs.bg-surface-canvas > div > div.flex.flex-row.items-center.gap-2 > h3").text.strip()
C:\Users\Admin\AppData\Local\Temp\ipykernel_29432\832258993.py:33: SyntaxWarning: invalid escape sequence '\['
  btn_section = driver.find_element(By.CSS_SELECTOR,"#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.relative.left-1\/2.right-1\/2.-ml-\[50vw\].-mr-\[50vw\].w-screen.bg-surface-neutral-canvas > div > div:nth-child(1) > div > div.max-md\:pb-2.md\:h-auto.md\:max-h-\[inherit\] > div > div.relative.flex.items-center.justify-center")

In [10]:
#Tìm ra link cuối cùng đã crawl
try:
    existing_data = pd.read_csv("pharmacity_medicines_data_demo(4).csv")
    crawled_urls = set(existing_data['url'].dropna())
    print(f"Đã crawl: {len(crawled_urls)} link")
except:
    crawled_urls = set()
    print("Chưa có file output")

Đã crawl: 2200 link

In [11]:
#Tìm ra link chưa crawl
df = pd.read_csv("pharmacity_medicine_links.csv")
uncrawled_df = df[~df['links'].isin(crawled_urls)].reset_index(drop=True)
print(f"Còn {len(uncrawled_df)} link chưa crawl")

Còn 1368 link chưa crawl

In [ ]:
# Crawl tiếp những link chưa crawl
if len(uncrawled_df) > 0:
    driver = set_up_driver()
    results = list(existing_data.to_dict('records')) if len(crawled_urls) > 0 else []
    
    for i, row in uncrawled_df.iterrows():
        url = row['links']
        drug_type = row.get('drug_type', '')
        category_link = row.get('category_link', '')
        category = row.get('category_name', '')

        try:
            driver.get(url)
            time.sleep(3)
            data = get_medicine_data(driver)
            data['url'] = url
            data['category'] = category
            data['drug_type'] = drug_type
            data['category_link'] = category_link
            data['category_name'] = category
            results.append(data)
            print(f"[{i+1}/{len(uncrawled_df)}] crawled: {data.get('name', 'N/A')}")
            
        except Exception as e:
            results.append({'url': url, 'error': str(e)})
            print(f"[{i+1}/{len(uncrawled_df)}] error: {url}")
        
        if (i + 1) % 10 == 0:
            pd.DataFrame(results).to_csv("pharmacity_medicines_data_demo(5).csv", index=False, encoding='utf-8-sig')
            print(f"Saved checkpoint: {len(results)} total records")

    driver.quit()
    pd.DataFrame(results).to_csv("pharmacity_medicines_data_demo(5).csv", index=False, encoding='utf-8-sig')
    print(f"Done! Total: {len(results)} records")
else:
    print("Tất cả link đã crawl!")

[1/1368] crawled: Viên nén bao phim Savi prolol 5mg điều trị tăng huyết áp, đau thắt ngực, suy tim (3 vỉ x 10 viên)
[2/1368] crawled: Viên nén A.T Bisoprolol 2.5mg điều trị tăng huyết áp, đau thắt ngực, suy tim (10 vỉ x 10 viên)
[3/1368] crawled: Viên nén Uperio 200mg điều trị suy tim (4 vỉ x 7 viên)
[4/1368] crawled: Viên nén Zafular 200mg điều trị tăng cholesterol máu, giảm mỡ máu (5 vỉ x 10 viên)
[5/1368] crawled: Viên nén Losartan 25mg TV điều trị tăng huyết áp (3 vỉ x 10 viên)
[6/1368] crawled: Viên nén Peruzi 12.5mg điều trị tăng huyết áp, suy tim (3 vỉ x 10 viên)
[7/1368] crawled: Viên nén Zoamco 40mg điều trị tăng cholesterol máu, giảm mỡ máu (2 vỉ x 15 viên)
[8/1368] crawled: Viên nén Viacoram 7mg/5mg điều trị tăng huyết áp (chai 30 viên)
[9/1368] crawled: Viên nén Troysar AM Troikaa điều trị tăng huyết áp, đau thắt ngực (10 vỉ x 10 viên)
[10/1368] crawled: Viên nén Maxxprolol 2,5mg Ampharco điều trị tăng huyết áp, đau thắt ngực, suy tim (10 vỉ x 10 viên)
Saved checkpoint: 2210 total records
[11/1368] crawled: Viên nén Tovecor Plus 5mg/1,25mg TW2 điều trị tăng huyết áp (3 vỉ x 10 viên)
[12/1368] crawled: Viên nén Rosuvas 10mg Hasan điều trị tăng cholesterol máu, giảm mỡ máu (2 vỉ x 14 viên)
[13/1368] crawled: Viên nén Nadecin 10 Arena Group phòng và trị cơn đau thắt ngực, suy tim sung huyết (3 vỉ x 10 viên)
[14/1368] crawled: Viên nén NORMODIPINE 5mg điều trị tăng huyết áp, đau thắt ngực (3 vỉ x 10 viên)
[15/1368] crawled: Viên nén Telmisartan TV Pharm 40mg điều trị tăng huyết áp (3 vỉ x 10 viên)
[16/1368] crawled: Viên nén Noklot 75mg phòng ngừa thành lập cục máu đông, huyết khối (3 vỉ x 10 viên)
[17/1368] crawled: Viên nén Dasarab 75mg phòng ngừa thành lập cục máu đông, huyết khối (2 vỉ x 14 viên)
[18/1368] crawled: Viên nén Dolotin 20mg điều trị tăng cholesterol máu, giảm mỡ máu (1 vỉ x 10 viên)
[19/1368] crawled: Nebilet 5mg (2vix14vien)
[20/1368] crawled: Atozet 10mg/20mg (Hộp 3 vỉ x 10 viên)
Saved checkpoint: 2220 total records
[21/1368] crawled: Bisotexa 10mg (Hộp 3 Vỉ x 10 Viên)
[22/1368] crawled: Simvastatin STELLA 10mg (Hộp 100 Viên)
[23/1368] crawled: Viên nén Pit-Stat 2mg điều trị tăng cholesterol máu, giảm mỡ máu (1 vỉ x 10 viên)
[24/1368] crawled: Furosemide STELLA 40 mg (Hộp 50v)
[25/1368] crawled: Viên nang Amlocor 5mg điều trị tăng huyết áp, đau thắt ngực (3 vỉ x 10 viên)
[26/1368] crawled: Viên nén Losartan 50mg điều trị tăng huyết áp (3 vỉ x 10 viên)
[27/1368] crawled: Osart-20mg Theon Pharma (Hộp 30 viên)
[28/1368] crawled: Beatil Tab 4/10 mg (Hộp 30 viên)
[29/1368] crawled: Spinolac 50mg (Hộp 3 vỉ x 10 viên)
[30/1368] crawled: Autifan 40mg An Thiên (Hộp 3 Vỉ x10 Viên)
Saved checkpoint: 2230 total records
[31/1368] crawled: Rotorlip 20 DHG (Hộp 3 vỉ x 10 viên)
[32/1368] crawled: RiVaxored 15mg Dr.Reddy's (Hop 14 Vien)
[33/1368] crawled: Rosubolic 10mg G.D. Laboratories (Hộp 3 vỉ x 10 viên)
[34/1368] crawled: Agidopa 250mg (10 Vỉ x 10 Viên)
Error clicking 'Xem thêm' button: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.relative.left-1\/2.right-1\/2.-ml-\[50vw\].-mr-\[50vw\].w-screen.bg-surface-neutral-canvas > div > div:nth-child(1) > div > div.max-md\:pb-2.md\:h-auto.md\:max-h-\[inherit\] > div > div.relative.flex.items-center.justify-center"}
  (Session info: chrome=145.0.7632.117); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff78492aa55
	0x7ff784688630
	0x7ff78441d75d
	0x7ff78447862e
	0x7ff78447893c
	0x7ff7844c8d87
	0x7ff7844c591c
	0x7ff784469098
	0x7ff784469f83
	0x7ff784957810
	0x7ff784951afd
	0x7ff784972c1a
	0x7ff7846a3345
	0x7ff7846ab81c
	0x7ff784691924
	0x7ff784691ad6
	0x7ff784677e47
	0x7ffd717ae8d7
	0x7ffd722cc40c

[35/1368] crawled: None
[36/1368] crawled: Sartanpo 50mg OPV (Hộp 3 Vi x 10 Viên)
[37/1368] crawled: Thuốc Atrox 10mg
[38/1368] crawled: Viên nén Co-Diovan 160mg/ 25mg điều trị tăng huyết áp (2 vỉ x 14 viên)
[39/1368] crawled: Viên nén Nebilet 5mg điều trị tăng huyết áp, suy tim (1 vỉ x 14 viên)
[40/1368] crawled: Viên nén Co-Diovan 80mg/12.5mg điều trị tăng huyết áp (2 vỉ x 14 viên)
Saved checkpoint: 2240 total records
[41/1368] crawled: Viên nén Verospiron 25mg điều trị tiền phẫu thuật cường aldosterone, tăng huyết áp (1 vỉ x 20 viên)
[42/1368] crawled: Viên nén Aprovel 300mg điều trị tăng huyết áp (2 vỉ x 14 viên)
[43/1368] crawled: Viên nén Felodipin Stella 5mg retard điều trị tăng huyết áp, đau thắt ngực (10 vỉ x 10 viên)
[44/1368] crawled: Viên nén Thiazifar 25mg điều trị tăng huyết áp, phù do các nguyên nhân khác nhau (10 vỉ x 10 viên)
[45/1368] crawled: Khí dung Nitromint 8mg/g dự phòng và điều trị chứng đau thắt ngực (chai 10g)
[46/1368] crawled: Viên nén Lipitor 10mg điều trị tăng cholesterol máu, giảm mỡ máu (3 vỉ x 10 viên)
[47/1368] crawled: Viên nén Diovan 160mg điều trị tăng huyết áp, suy tim (2 vỉ x 14 viên)
[48/1368] crawled: Viên nén Micardis 80mg điều trị tăng huyết áp (3 vỉ x 10 viên)
[49/1368] crawled: Viên nén Lifezar 50mg điều trị tăng huyết áp, suy tim mạn tính (3 vỉ x 10 viên)
[50/1368] crawled: Viên nén Co-Aprovel 300mg/12,5mg điều trị tăng huyết áp (2 vỉ X 14 viên)
Saved checkpoint: 2250 total records
[51/1368] crawled: Viên nén Captopril Stella 25mg điều trị tăng huyết áp, suy tim (10 vỉ x 10 viên)
[52/1368] crawled: Viên nén Crestor 10mg điều trị tăng cholesterol máu, giảm mỡ máu (2 vỉ x 14 viên)
[53/1368] crawled: Viên nén bao phim Lipanthyl supra 160mg điều trị rối loạn mỡ máu (3 vỉ x 10 viên)
[54/1368] crawled: Viên nén Lostad HCT 50mg/12,5mg điều trị tăng huyết áp (3 vỉ x 10 viên)
[55/1368] crawled: Viên nén Lipistad 20mg Stella điều trị tăng cholesterol máu, giảm mỡ máu (3 vỉ x 10 viên)
[56/1368] crawled: Viên nén Exforge HCT 10mg/160mg/12.5mg điều trị tăng huyết áp (4 vỉ x 7 viên)
[57/1368] crawled: Viên nén Simvastatin Stella 20mg điều trị tăng cholesterol máu, giảm mỡ máu (3 vỉ x 10 viên)
[58/1368] crawled: Viên nén Lodimax 10mg điều trị tăng huyết áp, đau thắt ngực (2 vỉ x 10 viên)
[59/1368] crawled: Viên nén Vashasan MR 35mg điều trị đau thắt ngực ổn định (3 vỉ x 30 viên)
[60/1368] crawled: Viên nén Vastec 20mg điều trị đau thắt ngực ổn định (2 vỉ x 30 viên)
Saved checkpoint: 2260 total records
[61/1368] crawled: Viên nang AMLODIPINE EG 5mg điều trị tăng huyết áp, đau thắt ngực (3 vỉ x 10 viên)
[62/1368] crawled: Viên nén Stadnolol 50mg điều trị tăng huyết áp, đau thắt ngực (10 vỉ x 10 viên)
[63/1368] crawled: Viên nén Ridlor 75mg ngăn ngừa tai biến đông máu (3 vỉ x 10 viên)
[64/1368] crawled: Viên nén Warfarin 5mg SPM điều trị và phòng huyết khối tĩnh mạch và nghẽn mạch phổi (3 vỉ x 10 viên)
[65/1368] crawled: Viên nén Esseil-10mg Davipharm điều trị tăng huyết áp (10 vỉ x 10 viên)
[66/1368] crawled: Viên nén Pinclos 75mg Incepta phòng ngừa thành lập cục máu đông, huyết khối (3 vỉ x 10 viên)
[67/1368] crawled: Viên nang Lipagim 300mg Agimexpharm điều trị tăng cholesterol máu, giảm mỡ máu (3 vỉ x 10 viên)
[68/1368] crawled: Viên nén Cardilopin 5mg điều trị tăng huyết áp, đau thắt ngực (3 vỉ x 10 viên)
[69/1368] crawled: Viên nén Vaspycar MR 35mg - Pymepharco điều trị đau thắt ngực ổn định (2 vỉ x 30 viên)
[70/1368] crawled: Viên nén Atzeti Gon Sa 10mg/10mg trị tăng cholesterol máu, phòng ngừa bệnh tim mạch (3 vỉ x 10 viên)
Saved checkpoint: 2270 total records
[71/1368] crawled: Viên bao tan trong ruột Aspirin 100mg Traphaco dự phòng nhồi máu cơ tim và đột quỵ (3 vỉ x 10 viên)
[72/1368] crawled: Viên nén Rotalzon 50mg điều trị tăng huyết áp (6 vỉ x 10 viên)
[73/1368] crawled: Viên nén Beatil 4mg/5mg điều trị tăng huyết áp vô căn và bệnh mạch vành ổn định (3 vỉ x 10 viên)
[74/1368] crawled: Concor COR Tab 2.5mg (3 vỉ x 10 viên) – Điều trị suy tim mạn tính
[75/1368] crawled: Viên nén Lipagim 160mg điều trị tăng cholesterol máu, giảm mỡ máu (3 vỉ x10 viên)
[76/1368] crawled: Viên uống Cammic 500mg điều trị rong kinh, hội chứng chảy máu (Hộp 10 Vỉ x 10 Viên)
[77/1368] crawled: Viên nén Cancetil 8mg điều trị tăng huyết áp, suy tim (3 vỉ x 10 viên)
[78/1368] crawled: Viên nén Pyzacar 25mg điều trị tăng huyết áp (2 vỉ x 15 viên)
[79/1368] crawled: Viên nén Nisten - F 7.5mg điều trị đau thắt ngực ổn định (4 vỉ x 7 viên)
[80/1368] crawled: Lopigim 600mg (3vi x 10vien)
Saved checkpoint: 2280 total records
[81/1368] crawled: Viên nén Nimotop 30mg điều trị thiếu máu cục bộ (3 vỉ x 10 viên)
[82/1368] crawled: Viên nén Tormeg-20mg điều trị tăng cholesterol máu, giảm mỡ máu (3 vỉ x 10 viên)
[83/1368] crawled: Viên nén Valsartan Stella 80mg điều trị tăng huyết áp, suy tim (3 vỉ x 10 viên)
[84/1368] crawled: Viên nén bao phim Savi Losartan 50mg điều trị tăng huyết áp (3 vỉ x 10 viên)
[85/1368] crawled: Viên nén Savi Prolol 2,5mg điều trị tăng huyết áp, đau thắt ngực, suy tim mạn tính (3 vỉ x 10 viên)
[86/1368] crawled: Viên nén Cozaar 100mg điều trị tăng huyết áp (3 vỉ x 10 viên)
[87/1368] crawled: Viên nén Misenbo 62,5mg điều trị tăng áp động mạch phổi (PAH) (3 vỉ x 10 viên)
[88/1368] crawled: Viên nén bao phim giải phóng có biến đổi Vastec 35mg MR điều trị đau thắt ngực ổn định (5 vỉ x 10 viên)
[89/1368] crawled: Viên nén Lisonorm 5mg/10mg Gedeon điều trị tăng huyết áp (3 vỉ x 10 viên)
[90/1368] crawled: Viên nén Uperio 100mg điều trị suy tim (2 vỉ X 14 viên)
Saved checkpoint: 2290 total records
[91/1368] crawled: Viên nén Xarelto 2.5mg điều trị, phòng ngừa huyết khối tĩnh mạch (1 vỉ x 14 viên)
[92/1368] crawled: Viên nén Misenbo 125mg điều trị tăng huyết áp động mạch phổi (3 vỉ x 10 viên)
[93/1368] crawled: Viên bao tan ở ruột Rabicad 20mg điều trị viêm loét dạ dày, tá tràng (1 vỉ x 10 viên)
[94/1368] crawled: Dourso 200mg (Hộp 3 vỉ x 10 viên)
[95/1368] crawled: Viên nén Agitritine 200mg trị hội chứng ruột kích thích, co thắt dạ dày ruột (5 vỉ x 10 viên)
[96/1368] crawled: Avarino 300mg Mega Wecare điều trị rối loạn tiêu hoá (5 vỉ x 10 viên)
[97/1368] crawled: Viên giải phóng có kiểm soát Pentasa 500MG điều trị viêm loét đại trực tràng (10 vỉ x 10 viên)
[98/1368] crawled: Viên bao tan ở ruột Pantagi 40mg viêm thực quản trào ngược (3 vỉ x 10 viên)
[99/1368] crawled: Viên nén Bài thạch điều trị sỏi thận, sỏi mật (hộp 45 viên)
[100/1368] crawled: Viên bao tan ở ruột Axitan 40mg điều trị dạ dày (3 vỉ x 10 viên)
Saved checkpoint: 2300 total records
[101/1368] crawled: Hỗn dịch uống Gel-Aphos 20% điều trị viêm loét dạ dày tá tràng, viêm thực quản (20 gói x 20g)
[102/1368] crawled: Esoragim 20 (3 vỉ x 10 viên) – Giảm axit, trị trào ngược dạ dày
[103/1368] crawled: Viên nén Agimoti 10mg điều trị triệu chứng nôn và buồn nôn (10 vỉ x 10 viên)
[104/1368] crawled: Viên nang cứng Ursachol 250mg điều trị bệnh nhân xơ gan mật nguyên phát (2 vỉ x 10 viên)
[105/1368] crawled: Dung dịch uống Debby 0,218g/5ml trị tiêu chảy, bệnh lỵ trực khuẩn và chứng viêm ruột kết (chai 30ml)
[106/1368] crawled: Viên bao tan ở ruột Pantoloc 20mg Takeda điều trị loét dạ dày, tá tràng (1 vỉ x 14 viên)
[107/1368] crawled: Viên nang Ursoliv 250mg điều trị sỏi mật, cải thiện chức năng gan (5 vỉ x 10 viên)
[108/1368] crawled: Viên nén Lampar 5mg trị nóng ruột, buồn nôn, trào ngược dạ dày (6 vỉ x 10 viên)
[109/1368] crawled: Thuốc cốm Amiyu Granules 2,5g cung cấp acid amin trên bệnh nhân suy thận mạn tính (30 gói x 2.5g)
[110/1368] crawled: Viên nén Alcomet Axon Drugs điều trị các bệnh lý về gan, nhiễm độc rượu cấp tính (3 vỉ x 10 viên)
Saved checkpoint: 2310 total records
[111/1368] crawled: Viên nén Homan 300mg trị xơ gan ứ mật nguyên phát, làm tan sỏi mật (10 vỉ x 10 viên)
[112/1368] crawled: Viên nang EMANERA 40MG điều trị viêm loét thực quản do trào ngược, tăng tiết acid (4 vỉ x 7 viên)
[113/1368] crawled: Viên nang Livermarin 70mg điều trị viêm gan, xơ gan (3 vỉ x 10 viên)
[114/1368] crawled: Viên uống PYME ABZ 400MG PYMEPHARCO
[115/1368] crawled: Bột pha uống Techepa 3000Mg điều trị viêm gan, xơ gan (hộp 14 gói)
[116/1368] crawled: Medogets 3g (Hộp 20 ống x 10ml)
[117/1368] crawled: Jiracek-20 Davipharm (3 Vỉ = 10 Viên)
[118/1368] crawled: Viên nang mềm Eblamin 200mg điều trị viêm gan mãn tính, xơ gan (2 túi x 6 vỉ x 5 viên)
[119/1368] crawled: Viên nén No- Panes 40mg chống co thắt cơ trơn đường tiêu hóa (10 vỉ x10 viên)
[120/1368] crawled: Viên nén ITOPAGI 50mg điều trị đầy hơi, chướng bụng, ợ nóng, buồn nôn (10 vỉ x 10 viên)
Saved checkpoint: 2320 total records
[121/1368] crawled: Amerisen 40mg Enlie (Hộp 3 Vỉ x 10 Viên)
[122/1368] crawled: Expas 40mg DHG (Hộp 50 viên)
[123/1368] crawled: Prolandex 60 BV Pharma (Hộp 2 vỉ x 10 viên)
[124/1368] crawled: Viên giải phóng có kiểm soát Newbutin trị viêm loét, trào ngược dạ dày thực quản (3 vỉ x 10 viên)
[125/1368] crawled: Thuốc cốm Hidrasec Infants 10mg trị tiêu chảy cấp ở trẻ trên 3 tháng và trẻ em (hộp 16 gói)
[126/1368] crawled: Viên nén Debridat 100mg trị đau, rối loạn nhu động ruột (2 vỉ x 15 viên)
[127/1368] crawled: Thuốc cốm Tràng Vị Khang trị viêm dạ dày, đại tràng cấp và mạn tính (6 gói x 8g)
[128/1368] crawled: Motilium-M 10Mg Tabs. (10 vỉ x 10 viên) – Giảm buồn nôn, khó tiêu hiệu quả
[129/1368] crawled: Viên nang Meteo spasmyl trị trướng bụng, rối loạn chức năng ruột (2 vỉ x 10 viên)
[130/1368] crawled: Viên nén Iboten 100mg trị đau, rối loạn tiêu hóa, hội chứng ruột kích thích (10 vỉ x10 viên)
Saved checkpoint: 2330 total records
[131/1368] crawled: Viên nén Uruso 100mg điều trị sỏi mật, cải thiện chức năng gan (10 vỉ x 10 viên)
[132/1368] crawled: Viên nang Ursimex hỗ trợ cải thiện chức năng gan (6 vỉ x 10 viên)
[133/1368] crawled: Viên nén Redbama 40mg Atlantic viêm thực quản trào ngược (6 vỉ x 10 viên)
[134/1368] crawled: Viên nang Nesteloc 20mg Us Pharma điều trị loét dạ dày, tá tràng (3 vỉ x 10 viên)
[135/1368] crawled: Viên bao tan ở ruột Rabeto 40mg trị trào ngược dạ dày thực quản (10 vỉ x 10 viên)
[136/1368] crawled: Viên nén Ayite 100mg loét dạ dày, tổn thương niêm mạc dạ dày (6 vỉ x 10 viên)
[137/1368] crawled: Viên nén Esomaxcare 40mg điều trị viêm loét thực quản do trào ngược, tăng tiết acid (3 vỉ x 10 viên)
[138/1368] crawled: Estor 40mg (4vi x 7vien)
[139/1368] crawled: Viên nén Sparenil 60mg Imexpharm giảm đau do co thắt cơ trơn ở đường tiêu hoá (3 vỉ x 10 viên)
[140/1368] crawled: Viên bao tan ở ruột Raxium 20mg DHG điều trị loét dạ dày (3 vỉ x 10 viên)
Saved checkpoint: 2340 total records
[141/1368] crawled: Viên nén bao tan trong ruột SaVi Esomeprazole 40mg điều trị viêm loét dạ dày (2 vỉ x 7 viên)
[142/1368] crawled: Viên nang kháng dịch vị Beprasan 20mg điều trị viêm loét dạ dày (1 vỉ x 10 viên)
[143/1368] crawled: Hỗn dịch uống Motilium Suspension 100ml điều trị các triệu chứng nôn và buồn nôn (chai 60ml)
[144/1368] crawled: Pyomezol 20mg (4 vỉ x 7 viên) – Giảm tiết axit, trị loét dạ dày
[145/1368] crawled: Viên bao tan ở ruột Panto-Denk 40mg DENK PHARMA viêm thực quản trào ngược (2 vỉ x 14 viên)
[146/1368] crawled: Viên nang Omeprazol 20mg TVP điều trị loét dạ dày, tá tràng, viêm thực quản (3 vỉ x 10 viên)
[147/1368] crawled: Viên nang Esomeprazol US 20mg trị loét dạ dày tá tràng, viêm thực quản trào ngược (3 vỉ x 10 viên)
[148/1368] crawled: Viên nang APHARNAX 500MG điều trị viêm gan, xơ gan (10 vỉ x 10 viên)
[149/1368] crawled: Viên bao tan ở ruột Esapbe 40mg điều trị loét dạ dày, tá tràng (3 vỉ x 10 viên)
[150/1368] crawled: Viên nén kháng dịch dạ dày NOLPAZA 20MG viêm thực quản trào ngược (2 vỉ x 14 viên)
Saved checkpoint: 2350 total records
[151/1368] crawled: Gastsus (30 goi x 10ml)
[152/1368] crawled: Viên nang Lansoprazol STELLA 30mg trị viêm loét dạ dày tá tràng (Hộp 100 Viên)
[153/1368] crawled: Abgalic Fort (Hộp 60 Viên)
[154/1368] crawled: Prolandex 30 BV Pharma (Hộp 2 vỉ x 10 viên)
[155/1368] crawled: Enpogas 20mg/1.1g S.P.M (Hop 3 vi x 10 vien)
[156/1368] crawled: Famogast 40mg Polpharma (Hộp 20 viên)
[157/1368] crawled: Viên bao phim Famotidin 40mg - Dược phẩm 3/2 điều trị viêm loét dạ dày tá tràng (10 vỉ x10 viên)
[158/1368] crawled: Viên nén Kim tiền thảo điều trị sỏi đường tiết niệu, sỏi thận (hộp 100 viên)
[159/1368] crawled: Viên nang PANTOSTAD 40mg viêm thực quản trào ngược (4 vỉ x 7 viên)
[160/1368] crawled: Viên nang cứng Entero-caps 200 mg điều trị tiêu chảy cấp tính (3 vỉ x 10 viên)
Saved checkpoint: 2360 total records
[161/1368] crawled: Gel dùng đường trực tràng Bibonlax Baby điều trị táo bón (10 tuýp x 5g)
[162/1368] crawled: Viên nén Misoprostol Stella 200 mcg điều trị loét tá tràng, dạ dày lành tính (3 vỉ x 10 viên)
[163/1368] crawled: Bột pha tiêm Nexium 40mg điều trị viêm loét dạ dày (hộp 1 chai)
[164/1368] crawled: Viên nén Uruso 300mg điều trị sỏi mật, cải thiện chức năng gan (3 vỉ x 10 viên)
[165/1368] crawled: Viên nang Prazopro 20mg trị loét dạ dày tá tràng, viêm thực quản trào ngược (2 vỉ x 7 viên)
[166/1368] crawled: Viên nén Hueso 300mg điều trị sỏi túi mật cholesterol, bệnh gan mật mãn tính (3 vỉ x 10 viên)
[167/1368] crawled: Viên nén Eltium 50mg điều trị đầy hơi, chướng bụng, ợ nóng, buồn nôn (5 vỉ x 10 viên)
[168/1368] crawled: Viên nang Phil URSO Phil Inter Pharma hỗ trợ cải thiện chức năng gan (12 vỉ x 5 viên)
[169/1368] crawled: Viên nang Mepraz 20mg điều trị loét dạ dày, tá tràng, viêm thực quản (7 vỉ x 4 viên)
[170/1368] crawled: Carsil 90 (5 vỉ x 6 viên/hộp)
Saved checkpoint: 2370 total records
[171/1368] crawled: Bột pha uống MEZATHIN 3G tăng amoniac trong bệnh xơ gan, tăng cường chức năng gan (hộp 10 gói)