In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
pharmacity_df_1 = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_demo.csv")
pharmacity_df_2 = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_demo(2).csv")
pharmacity_df_3 = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_demo(3).csv")
pharmacity_df_4 = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_demo(4).csv")
pharmacity_df_5 = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_demo(5).csv")
pharmacity_df_6 = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_demo(6).csv")
pharmacity_df_7 = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_demo(7).csv")
pharmacity_df_8 = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_demo(8).csv")
pharmacity_df_9 = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_demo(9).csv")

In [3]:
print(f"pharmacity_df_1: {len(pharmacity_df_1)} records")
print(f"pharmacity_df_2: {len(pharmacity_df_2)} records")
print(f"pharmacity_df_3: {len(pharmacity_df_3)} records")
print(f"pharmacity_df_4: {len(pharmacity_df_4)} records")
print(f"pharmacity_df_5: {len(pharmacity_df_5)} records")
print(f"pharmacity_df_6: {len(pharmacity_df_6)} records")
print(f"pharmacity_df_7: {len(pharmacity_df_7)} records")
print(f"pharmacity_df_8: {len(pharmacity_df_8)} records")
print(f"pharmacity_df_9: {len(pharmacity_df_9)} records")

pharmacity_df_1: 48 records
pharmacity_df_2: 47 records
pharmacity_df_3: 1500 records
pharmacity_df_4: 2200 records
pharmacity_df_5: 2370 records
pharmacity_df_6: 2990 records
pharmacity_df_7: 3310 records
pharmacity_df_8: 3390 records
pharmacity_df_9: 3568 records

In [4]:
print(f"Số dòng của pharmacity_df_9: {pharmacity_df_9.shape[0]}")
print(f"Số cột của pharmacity_df_9: {pharmacity_df_9.shape[1]}")

Số dòng của pharmacity_df_9: 3568
Số cột của pharmacity_df_9: 24

In [5]:
nan_name =  pharmacity_df_9['name'].isna()
nan_name_rows = pharmacity_df_9[nan_name]
print(f"Số dòng có name bị lỗi nan: {len(nan_name_rows)}")
nan_name_links = nan_name_rows['url'].dropna().tolist()
print(f"Số link bị lỗi: {len(nan_name_links)}")
print("Các link bị lỗi:")
for link in nan_name_links:
    print(link)

none_name = pharmacity_df_9['name'].astype(str).str.strip().str.lower().eq('none')
none_name_rows = pharmacity_df_9[none_name]
print(f"Số dòng có name bị lỗi None: {len(none_name_rows)}")

none_name_links = none_name_rows['url'].tolist()
print(f"Số link bị lỗi: {len(none_name_links)}")
print("Các link bị lỗi:")
for link in none_name_links:
    print(link)

Số dòng có name bị lỗi nan: 493
Số link bị lỗi: 493
Các link bị lỗi:
https://www.pharmacity.vn/desloratadine-5mg-hop-2vi-x-15-vien.html
https://www.pharmacity.vn/azicine-500-stella-1-vi-x-6-vien.html
https://www.pharmacity.vn/kodemin-softcap-10vi-x-10vien.html
https://www.pharmacity.vn/thuoc-cam-lanh#
https://www.pharmacity.vn/nasol-spray-chai-70ml.html
https://www.pharmacity.vn/tinh-dau-tre-em-nasomom-4-spray-chai-70ml.html
https://www.pharmacity.vn/at-arginin-200mg-10-vi-x10-vien.html
https://www.pharmacity.vn/nhom-san-pham-giam-dau-da-day-cho-nguoi-lon.html
https://www.pharmacity.vn/thuoc-da-lieu#
https://www.pharmacity.vn/bacterocin-5g.html
https://www.pharmacity.vn/bacterocin-15g.html
https://www.pharmacity.vn/neutrivit-5000-bidiphar-h44-inj.html
https://www.pharmacity.vn/thuoc-than-kinh#
https://www.pharmacity.vn/cao-dan-giam-dau-tiger-balm-plaster-rd-7x10cm-tui-3-mieng.html
https://www.pharmacity.vn/thuoc-co-xuong-khop#
https://www.pharmacity.vn/cao-dan-giam-dau-tiger-balm-plaster-rd-10x14cm-tui-3-mieng.html
https://www.pharmacity.vn/tiger-balm-white-30g.html
https://www.pharmacity.vn/tiger-balm-oil-28ml.html
https://www.pharmacity.vn/tiger-balm-oil-57ml.html
https://www.pharmacity.vn/cao-ho-do-giam-dau-nhuc-co-tiger-balm-red-19-4g.html
https://www.pharmacity.vn/tiger-balm-red-30g.html
https://www.pharmacity.vn/tiger-balm-white-194g.html
https://www.pharmacity.vn/silymarin-vcp-10-vi-x-10-vien.html
https://www.pharmacity.vn/vitamin-va-khoang-chat#
https://www.pharmacity.vn/nhom-san-pham-giam-cam-ho-so-mui-nguoi-lon.html
https://www.pharmacity.vn/bot-pha-hon-dich-uong-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-tiet-nieu-cefaclor-250mg-10-goi-x-2ghop.html
https://www.pharmacity.vn/oos-by-ncc-spirastad-3-miu.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-phoi-nhiem-khuan-vung-tieu-avelox-400mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-viem-tai-giua-viem-duong-ho-hap-ceclor-125mg60ml.html
https://www.pharmacity.vn/thuoc-du-phong-va-dieu-tri-cac-benh-nhiem-khuan-tinidazol-500mg-1-vi-x-4-vien.html
https://www.pharmacity.vn/oos-by-ncc-unasyn-tab-375mg.html
https://www.pharmacity.vn/thuoc-du-phong-va-dieu-tri-nhiem-nam-candida-o-da-niem-mac-nystatin-10-vi-x-8-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-pms-cotrim-960mg-10vi-x10vien.html
https://www.pharmacity.vn/claminat-250mg3125mg-hop12goi.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-do-vi-khuan-nhay-cam-erythromycin-500mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/metrogyl-denta.html
https://www.pharmacity.vn/vien-nen-flagyl-250mg-dieu-tri-nhiem-khuan-2-vi-x-10-vien.html
https://www.pharmacity.vn/itranstad-hop-1-vi-x-6-vien.html
https://www.pharmacity.vn/klamentin-875125-hop-2-vi-x-7-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-clamoxyl-250mg.html
https://www.pharmacity.vn/klamentin-500625-hop-24-goi-x-2g.html
https://www.pharmacity.vn/dieu-tri-nhiem-virus-herpes-ciclevir-800-10-vi-x-5-vienhop.html
https://www.pharmacity.vn/moloxcin-400-hop-1-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-bactamox-625-12-goi-x-1-6g-hop.html
https://www.pharmacity.vn/augbidil-1g-hop-2-vi-x-7-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-nam-spulit-6-vi-x-5-vien-hop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-vigentin-500-62-5mg-dt-2-vi-x-7-vien-hop.html
https://www.pharmacity.vn/metiny-375mg-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-khang-sinh-scd-cefaclor-250mg-2-vi-x-10-vien.html
https://www.pharmacity.vn/naphacogyl-2vi-x-10vien-km.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-duong-ho-hap-curam-1000mg-lek-pharmaceuticals-80-vienhop.html
https://www.pharmacity.vn/cefixim-200mg-cuu-long-2vi-x-10vien.html
https://www.pharmacity.vn/curam-250mg5ml-hop-1-chai-x-75g-bot.html
https://www.pharmacity.vn/acnequidt-20ml.html
https://www.pharmacity.vn/nanfizy-100mg-hop-1-vi-x-3-vien.html
https://www.pharmacity.vn/cefpivoxil-400-3-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-rovas-0-75m-24-goi-x-3g-hop.html
https://www.pharmacity.vn/emycindhg-250-hop-24-goi-x-15g.html
https://www.pharmacity.vn/biocemet-500625-2-vi-x-7-vienhop.html
https://www.pharmacity.vn/imeclor-125-12-goi-x-25ghop.html
https://www.pharmacity.vn/tenfovix-hop-3x10.html
https://www.pharmacity.vn/candisafe-hop-1-vi-x-7-vien.html
https://www.pharmacity.vn/nirdicin-250mg-hop-10-vien-pharmathen.html
https://www.pharmacity.vn/griseofulvin-tab-500mg-box-100.html
https://www.pharmacity.vn/cefpodoxim-100-hv-usp-hop-10-goi.html
https://www.pharmacity.vn/uphaxime-200mg-1vix10vien.html
https://www.pharmacity.vn/cefdinir-300-hv-hop-2-vi-x-10-vien-nang-cung.html
https://www.pharmacity.vn/zelfamox-tab-dt-500mg125-2vix7vien.html
https://www.pharmacity.vn/clarisol-500mg-hop-10-vien.html
https://www.pharmacity.vn/aziphar-susp-dry-200mg5ml-15ml.html
https://www.pharmacity.vn/cefuroxim-500mg-1-vi-x-10-vien-vpc.html
https://www.pharmacity.vn/alfavir-tablet-incepta-10-vien.html
https://www.pharmacity.vn/levofloxacin-kabi-100ml.html
https://www.pharmacity.vn/ciprofloxacin-kabi-200mg-chai-100ml.html
https://www.pharmacity.vn/augbidil-625-h14.html
https://www.pharmacity.vn/agi-cotrim-960mg-hop-100-vien.html
https://www.pharmacity.vn/denvin-300mg-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/griseofulvin-500mg10-vi-x10-vien.html
https://www.pharmacity.vn/acigmentin-1000mg-2vi-x-7-vien.html
https://www.pharmacity.vn/gentamicin-kabi-80mg2ml-hop-100-ong.html
https://www.pharmacity.vn/bot-pha-hon-dich-uong-augmentin-es-gsk-50ml.html
https://www.pharmacity.vn/rx-thuoc-khang-sinh#
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-hiv-aluvia-tab-200mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-vi-khuan-nhay-cam-viem-amidan-viem-tai-giua-viem-xoang-cap-klacid-125mg-5ml.html
https://www.pharmacity.vn/griseofulvin-500mg-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-giun-chi-pizar-6-hop-4vien.html
https://www.pharmacity.vn/pyclin-300-hop-10-vi-x-10-vien.html
https://www.pharmacity.vn/biseptol-80ml.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-duong-ho-hap-psm-claminat-1g.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-pms-roxithromycin-150mg-2vi-x10vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-da-doncef-500mg.html
https://www.pharmacity.vn/distocide-600mg-hop-1-vi-x-4-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-dieu-tri-nhiem-hiv-tuyp-1-savi-tenofovir-300mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-nhiem-khuan-do-chlamydia-rickettsia-lau-cau-xoan-khuan-ta-tetracyclin-500mg-10-vi-x-10-vien.html
https://www.pharmacity.vn/metronidazol-250-hop-10-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-nha-chu-man-tinh-sau-rang-viem-nuou-rang-metrogyl-denta-tuyp-20g.html
https://www.pharmacity.vn/aticef-250-hop-24-goi.html
https://www.pharmacity.vn/fosmicin-500mg-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/aticef-500-caps-hop-2-vi-x-7-vien.html
https://www.pharmacity.vn/cefprozil-250-us-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/pricefil-500mg-1-vi-x-12-vienhop.html
https://www.pharmacity.vn/ofloxacin-200mg-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/haginat-500-hop-2-vi-x-5-vien.html
https://www.pharmacity.vn/clabact-500-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-nhiem-khuan-crocin-100mg-kid-25-goihop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-forlen-600mg-2-vi-x-10-vien-hop.html
https://www.pharmacity.vn/ofmantine-625mg-2-vi-x-7-vienhop.html
https://www.pharmacity.vn/thuoc-tri-viem-nhiem-do-ki-sinh-trung-mecefix-be-50mg-merap-20-goi-x-1grhop.html
https://www.pharmacity.vn/glocip-500-hop-3-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-fabamox-250mg-12-goi-x-1-4g-hop.html
https://www.pharmacity.vn/trimoxtal-500500mg-2vi-x-7vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-orenko-200mg-2-vi-x-10-vien-hop.html
https://www.pharmacity.vn/ivermectin-3-at-hop-1-vi-x-4-vien.html
https://www.pharmacity.vn/pymeazi-500-hop-1-vi-x-3-vien.html
https://www.pharmacity.vn/cefatam-750mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/pricefil-2505ml-chai-30ml.html
https://www.pharmacity.vn/thuoc-khang-sinh-negacef-500mg-2-vi-x-5-vien.html
https://www.pharmacity.vn/thuoc-khang-viem-bactamox-375mg-12-goi-imexpharm.html
https://www.pharmacity.vn/thuoc-khang-sinh-cetraxal-15-ong-x-025mlhop.html
https://www.pharmacity.vn/epclusa-100400mg-hop-28vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-hiv-tuyp-1-viem-gan-b-man-tinh-agifovir-300mg-3-vi-x-10-vienhop.html
https://www.pharmacity.vn/vien-nen-medskin-clovir-200mg-dhg-tri-nhiem-virus-thuy-dau-va-zona-herpes-simplex-5-vi-x-10-vien.html
https://www.pharmacity.vn/nirdicin-500mg-hop-1-vi-x-10-vien.html
https://www.pharmacity.vn/pharcavir-25mg.html
https://www.pharmacity.vn/haginir-300-2vix10vien.html
https://www.pharmacity.vn/tratrison-crm-10g-1.html
https://www.pharmacity.vn/tetracyclin-caps-500mg-box-200.html
https://www.pharmacity.vn/cefpodoxim-hv-tab-fc-200mg-box-30.html
https://www.pharmacity.vn/zolgyl-tab-2vi-x-10vien.html
https://www.pharmacity.vn/ibisaol-caps-pllt-100mg-box-10-hop-10-vien.html
https://www.pharmacity.vn/pharbaren-500mg-hop-1-vi-x-10-vien.html
https://www.pharmacity.vn/agiclari-500mg-2vi-x-5vien.html
https://www.pharmacity.vn/efodyl-sac-150mg-20goix15g.html
https://www.pharmacity.vn/letdion-eye-drops-05-5ml.html
https://www.pharmacity.vn/levoleo-500mg-1-vi-x-10vien.html
https://www.pharmacity.vn/nifin-tab-fc-200mg-box-20dhg-pharma.html
https://www.pharmacity.vn/ciprom-500mg-5-vi-x-10-vien.html
https://www.pharmacity.vn/trimeseptol-480mg-25-vi-x-20-vien.html
https://www.pharmacity.vn/ofbexim-200-usp-hop-30-vien.html
https://www.pharmacity.vn/fugentin-875mg125mg-elpen-hop-12-goi.html
https://www.pharmacity.vn/bostolox-100mg-hop-24-goi.html
https://www.pharmacity.vn/ciprofloxacin-250mg-us-pharma-hop-10-goi.html
https://www.pharmacity.vn/clindastad-150mg-stella-hop-100v.html
https://www.pharmacity.vn/elomentin-pos-400mg-57mg.html
https://www.pharmacity.vn/thuoc-khang-sinh-klamentin-625mg-hop-3-vi-x-4-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-hong-va-viem-amidan-clarithromycin-stada-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-nhiem-khuan-do-vi-khuan-nhay-cam-gay-ra-cephalexin-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-trieu-chung-nhiem-khuan-duong-ho-hap-zinnat-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-nhiem-khuan-nhe-trung-binh-cac-benh-nhiem-khuan-do-vi-khuan-nhay-cam-levofloxacin-stada-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-do-cac-vi-khuan-nhay-cam-cefalexin-500mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/fovirpoxil30vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-nhiem-khuan-duong-ho-hap-cephalexin-250mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-duong-ho-hap-klacid-mr-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-xoang-cap-viem-phe-quan-man-tinh-tavanic-500mg.html
https://www.pharmacity.vn/cefimbrano-100mg-hop-10goi.html
https://www.pharmacity.vn/zinecox-200mg-2vi-x-10vien.html
https://www.pharmacity.vn/claminat-500-mg625-mg-hop-12-goi-x-15g.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-nam-candida-o-niem-mac-duong-tieu-hoa-nystatin-500000iu-2-vi-x-8-vienhop.html
https://www.pharmacity.vn/hafixim-100-kids-hop-24-goi.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-brucella-benh-dich-ta-doxycylin-100mg.html
https://www.pharmacity.vn/getino-b-300mg-chai-30-vien.html
https://www.pharmacity.vn/tvcefuroxime-500mg-3-vi-x-10-vienhop.html
https://www.pharmacity.vn/cefdinir-300mg-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-nhiem-pyfaclor-500mg-1-vi-x-12-vien.html
https://www.pharmacity.vn/medskin-clovir-800-hop-3-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-nhiem-khuan-crocin-200mg-1-vi-x-10-vien-hop.html
https://www.pharmacity.vn/zidocindhg-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/getzlox-750mg-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-ho-hap-claminat-500mg-125mg-hop-12-goi.html
https://www.pharmacity.vn/gentamicin-80mg2ml-10-ong-x-2mlhop.html
https://www.pharmacity.vn/ofmantine-1g-2-vi-x-7-vienhop.html
https://www.pharmacity.vn/meiact-50mg-21-goihop.html
https://www.pharmacity.vn/agiclovir-800-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/cefimed-200-2-vi-x-4-vienhop.html
https://www.pharmacity.vn/vigentin-875125-dt-hop-2-vi-x-7-vien.html
https://www.pharmacity.vn/cttprozil-capl-fc-500mg-1vi-x-10vien.html
https://www.pharmacity.vn/thuoc-khang-sinh-hagimox-250mg-hop-24-goi.html
https://www.pharmacity.vn/hapenxin-500mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-iba-mentin-1000mg-62-5mg-2-vi-x-7-vien-hop.html
https://www.pharmacity.vn/thuoc-khang-viem-metronidazol-250mg-10-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-khang-sinh-bluemoxi-400mg-1-vi-x-7-vien.html
https://www.pharmacity.vn/thuoc-khang-sinh-rifampicin-300mg-10-vi-x-10-vien.html
https://www.pharmacity.vn/at-entecavir-05mg-3vi-x-10-vien.html
https://www.pharmacity.vn/vemlidy-25mg-chai-30-vien.html
https://www.pharmacity.vn/levofloxacin-500-imexpharm-1vi-x10vien.html
https://www.pharmacity.vn/refix-550mg-hop-3vi-x-10-vien.html
https://www.pharmacity.vn/direntab-200-hop-1-vi-x-10-vien.html
https://www.pharmacity.vn/atasic-200mg-3vi-x-10-vien.html
https://www.pharmacity.vn/usarmicin-hop-2-vi-x10-vien.html
https://www.pharmacity.vn/armten-200mgv-hop-1vi-x-10-vien.html
https://www.pharmacity.vn/cefriven-200mg-hop-2vi-x-10-vien.html
https://www.pharmacity.vn/ampicillin-500mg-10vi-x-10vien-brawn.html
https://www.pharmacity.vn/medaxetine-500mg-1vi-x-10vien.html
https://www.pharmacity.vn/lucass-200-2vi-x-10vien.html
https://www.pharmacity.vn/imefed-dt-500mg125mg-2-vi-x-7-vien.html
https://www.pharmacity.vn/acyclovir-tab-800mg-boston-5vi-x-5vien.html
https://www.pharmacity.vn/cefalex-500mg-10-vi-x-10-vien.html
https://www.pharmacity.vn/zelfamox-tab-dt-875mg-125-2vix7vien.html
https://www.pharmacity.vn/lincomycin-caps-500mg-10vi-x-10vien.html
https://www.pharmacity.vn/acyclovir-stella-400mg-hop-50-vien.html
https://www.pharmacity.vn/rodogyl-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-do-duong-ho-hap-gay-ra-dalacin-c-300mg.html
https://www.pharmacity.vn/azicine-hop-1-vi-x-6-vien.html
https://www.pharmacity.vn/ampicillin-500mg-hop-10-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-trung-rang-mieng-cap-man-tinh-dorogyne-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-cho-tre-em-augmentin-250mg.html
https://www.pharmacity.vn/clarithromycin-stella-250-mg-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-duong-ho-hap-duong-sinh-duc-da-zinnat-tab-250mg-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-truong-hop-nhiem-trung-do-vi-khuan-duong-ho-hap-amoxicillin-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-giun-chi-pizar-3-1-vi-x-4-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-viem-tai-giua-va-cac-benh-nhiem-khuan-cotrimstada-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-du-phong-va-dieu-tri-cac-nhiem-khuan-gay-ra-boi-vi-khuan-nhay-cam-penicilin-v-kali-1000000iu-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-euvipharm-cefpodoxim-200mg-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-opecipro-500-2-vi-x-7-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-gan-b-man-tinh-o-nguoi-lon-entecavir-stada-05mg-3-vie-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-hong-viem-amidan-viem-tai-giua-viem-xoang-mecefix-75mg.html
https://www.pharmacity.vn/klamentin-2503125-hop-24-goi.html
https://www.pharmacity.vn/hafixim-50-kids-hop-24-goi.html
https://www.pharmacity.vn/imexime-100mg-hop12goi-imexpharm.html
https://www.pharmacity.vn/pharmox-500mg-10vi-x10vien.html
https://www.pharmacity.vn/griseofulvin-5-hop-1-tuyp-nhom-x-10g.html
https://www.pharmacity.vn/medskin-clovir-400-hop-6-vi-x-10-vien.html
https://www.pharmacity.vn/haginat-125-hop-24-goi.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-va-dieu-tri-du-phong-bien-chung-nhiem-trung-tai-cho-sau-phau-thuat-rang-mieng-spiranisol-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/levodhg-250-hop-3-vi-x-10-vien.html
https://www.pharmacity.vn/levodhg-500-hop-3-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-droxicef-500mg-10-vi-x-10-vien-hop.html
https://www.pharmacity.vn/azithromycin-250-hop-10-vi-x-6-vien.html
https://www.pharmacity.vn/rovas-3m-hop-2-vi-x-5-vien.html
https://www.pharmacity.vn/bicebid-200mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/tvcefuroxime-250mg-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/hepbest-25mg-hop-30-vien.html
https://www.pharmacity.vn/cefprozil-500-us-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/cefbuten-200mg-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/anaferon-for-children-hop-1-vi-x-20-vien.html
https://www.pharmacity.vn/cefadroxil-eg-500mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/efodyl-500-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/ciclevir-400mg-hop-10-vi-x-5-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-duong-ho-hap-duong-tiet-nieu-pms-bactamox-750mg.html
https://www.pharmacity.vn/thuoc-khang-sinh-hapenxin-250-kids-hop-24-goi.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-amoxicillin-250mg-imexpharm-12-goi-hop.html
https://www.pharmacity.vn/haginat-250-hop-2-vi-x-5-vien.html
https://www.pharmacity.vn/vazigoc-4-vi-x-7-vienhop.html
https://www.pharmacity.vn/cepoxitil-200-hop-1-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-khang-sinh-garosi-500mg-1-vi-x-3-vien.html
https://www.pharmacity.vn/cefprozil-500-us-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/ofbexim-tab-fc-200mg-3vi-x-10vien.html
https://www.pharmacity.vn/undtas-500-hop-3-vi-x-10-vien.html
https://www.pharmacity.vn/zebacef-tab-300mg-1vi-x-10vien.html
https://www.pharmacity.vn/auclanityl-2vi-x-7-vien.html
https://www.pharmacity.vn/rocephin-1g-iv-b1-inj-10ml.html
https://www.pharmacity.vn/eucinat-250-h1vi10vien.html
https://www.pharmacity.vn/ciprothepharm-capl-fc-500mg-box-100.html
https://www.pharmacity.vn/cotrimoxazol-tab-480mg-box-400.html
https://www.pharmacity.vn/taromentin-457mg5ml-chai-70ml.html
https://www.pharmacity.vn/pricefil-susp-dry-250mg-5ml-60ml.html
https://www.pharmacity.vn/azismile-susp-dry-200mg-5ml-15ml.html
https://www.pharmacity.vn/ortizole-500mg-5-vi-x-6-vien.html
https://www.pharmacity.vn/acyclovir-stella-800mg-hop-50-vien.html
https://www.pharmacity.vn/betamox-es-1-chai-100ml-atral.html
https://www.pharmacity.vn/sumakin-1g-mekophar-hop-14-vien.html
https://www.pharmacity.vn/bot-pha-hon-dich-uong-augmentin-es-gsk-100ml.html
https://www.pharmacity.vn/pyme-azi-caps-250mg-box-6.html
https://www.pharmacity.vn/ofloxacin-drops-eye-6ml-1.html
https://www.pharmacity.vn/pyme-fucan-caps-150mg-box-1.html
https://www.pharmacity.vn/ceftenmax-200-2vi-x-10vien.html
https://www.pharmacity.vn/azizi-500mg-hop-1-vi-x-3-vien.html
https://www.pharmacity.vn/cepmox-clav-875mg-125mg-2-vi-x-7-vien.html
https://www.pharmacity.vn/imefed-250mg3125mg-hop-1-tui-x-12-goi.html
https://www.pharmacity.vn/doxycycline-100mg-hop-10-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-nang-du-phong-benh-nao-mo-cau-scanax-500mg-5-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-duong-ho-hap-tieu-nieu-ospexin-500mg.html
https://www.pharmacity.vn/bot-pha-hon-dich-uong-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-tiet-nieu-mo-da-cefaclor-125mg-10-goi-x-2ghop.html

In [6]:
#Lấy các link bị lỗi từ pharmacity_df_9
error_name = (nan_name | none_name)   
error_name_links = pharmacity_df_9[error_name]['url'].dropna().tolist()
print(f"Số link bị lỗi: {len(error_name_links)}")
print("Các link bị lỗi:")
for link in error_name_links:
    print(link)

Số link bị lỗi: 493
Các link bị lỗi:
https://www.pharmacity.vn/desloratadine-5mg-hop-2vi-x-15-vien.html
https://www.pharmacity.vn/azicine-500-stella-1-vi-x-6-vien.html
https://www.pharmacity.vn/kodemin-softcap-10vi-x-10vien.html
https://www.pharmacity.vn/thuoc-cam-lanh#
https://www.pharmacity.vn/nasol-spray-chai-70ml.html
https://www.pharmacity.vn/tinh-dau-tre-em-nasomom-4-spray-chai-70ml.html
https://www.pharmacity.vn/at-arginin-200mg-10-vi-x10-vien.html
https://www.pharmacity.vn/nhom-san-pham-giam-dau-da-day-cho-nguoi-lon.html
https://www.pharmacity.vn/thuoc-da-lieu#
https://www.pharmacity.vn/bacterocin-5g.html
https://www.pharmacity.vn/bacterocin-15g.html
https://www.pharmacity.vn/neutrivit-5000-bidiphar-h44-inj.html
https://www.pharmacity.vn/thuoc-than-kinh#
https://www.pharmacity.vn/cao-dan-giam-dau-tiger-balm-plaster-rd-7x10cm-tui-3-mieng.html
https://www.pharmacity.vn/thuoc-co-xuong-khop#
https://www.pharmacity.vn/cao-dan-giam-dau-tiger-balm-plaster-rd-10x14cm-tui-3-mieng.html
https://www.pharmacity.vn/tiger-balm-white-30g.html
https://www.pharmacity.vn/tiger-balm-oil-28ml.html
https://www.pharmacity.vn/tiger-balm-oil-57ml.html
https://www.pharmacity.vn/cao-ho-do-giam-dau-nhuc-co-tiger-balm-red-19-4g.html
https://www.pharmacity.vn/tiger-balm-red-30g.html
https://www.pharmacity.vn/tiger-balm-white-194g.html
https://www.pharmacity.vn/silymarin-vcp-10-vi-x-10-vien.html
https://www.pharmacity.vn/vitamin-va-khoang-chat#
https://www.pharmacity.vn/nhom-san-pham-giam-cam-ho-so-mui-nguoi-lon.html
https://www.pharmacity.vn/bot-pha-hon-dich-uong-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-tiet-nieu-cefaclor-250mg-10-goi-x-2ghop.html
https://www.pharmacity.vn/oos-by-ncc-spirastad-3-miu.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-phoi-nhiem-khuan-vung-tieu-avelox-400mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-viem-tai-giua-viem-duong-ho-hap-ceclor-125mg60ml.html
https://www.pharmacity.vn/thuoc-du-phong-va-dieu-tri-cac-benh-nhiem-khuan-tinidazol-500mg-1-vi-x-4-vien.html
https://www.pharmacity.vn/oos-by-ncc-unasyn-tab-375mg.html
https://www.pharmacity.vn/thuoc-du-phong-va-dieu-tri-nhiem-nam-candida-o-da-niem-mac-nystatin-10-vi-x-8-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-pms-cotrim-960mg-10vi-x10vien.html
https://www.pharmacity.vn/claminat-250mg3125mg-hop12goi.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-do-vi-khuan-nhay-cam-erythromycin-500mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/metrogyl-denta.html
https://www.pharmacity.vn/vien-nen-flagyl-250mg-dieu-tri-nhiem-khuan-2-vi-x-10-vien.html
https://www.pharmacity.vn/itranstad-hop-1-vi-x-6-vien.html
https://www.pharmacity.vn/klamentin-875125-hop-2-vi-x-7-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-clamoxyl-250mg.html
https://www.pharmacity.vn/klamentin-500625-hop-24-goi-x-2g.html
https://www.pharmacity.vn/dieu-tri-nhiem-virus-herpes-ciclevir-800-10-vi-x-5-vienhop.html
https://www.pharmacity.vn/moloxcin-400-hop-1-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-bactamox-625-12-goi-x-1-6g-hop.html
https://www.pharmacity.vn/augbidil-1g-hop-2-vi-x-7-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-nam-spulit-6-vi-x-5-vien-hop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-vigentin-500-62-5mg-dt-2-vi-x-7-vien-hop.html
https://www.pharmacity.vn/metiny-375mg-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-khang-sinh-scd-cefaclor-250mg-2-vi-x-10-vien.html
https://www.pharmacity.vn/naphacogyl-2vi-x-10vien-km.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-duong-ho-hap-curam-1000mg-lek-pharmaceuticals-80-vienhop.html
https://www.pharmacity.vn/cefixim-200mg-cuu-long-2vi-x-10vien.html
https://www.pharmacity.vn/curam-250mg5ml-hop-1-chai-x-75g-bot.html
https://www.pharmacity.vn/acnequidt-20ml.html
https://www.pharmacity.vn/nanfizy-100mg-hop-1-vi-x-3-vien.html
https://www.pharmacity.vn/cefpivoxil-400-3-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-rovas-0-75m-24-goi-x-3g-hop.html
https://www.pharmacity.vn/emycindhg-250-hop-24-goi-x-15g.html
https://www.pharmacity.vn/biocemet-500625-2-vi-x-7-vienhop.html
https://www.pharmacity.vn/imeclor-125-12-goi-x-25ghop.html
https://www.pharmacity.vn/tenfovix-hop-3x10.html
https://www.pharmacity.vn/candisafe-hop-1-vi-x-7-vien.html
https://www.pharmacity.vn/nirdicin-250mg-hop-10-vien-pharmathen.html
https://www.pharmacity.vn/griseofulvin-tab-500mg-box-100.html
https://www.pharmacity.vn/cefpodoxim-100-hv-usp-hop-10-goi.html
https://www.pharmacity.vn/uphaxime-200mg-1vix10vien.html
https://www.pharmacity.vn/cefdinir-300-hv-hop-2-vi-x-10-vien-nang-cung.html
https://www.pharmacity.vn/zelfamox-tab-dt-500mg125-2vix7vien.html
https://www.pharmacity.vn/clarisol-500mg-hop-10-vien.html
https://www.pharmacity.vn/aziphar-susp-dry-200mg5ml-15ml.html
https://www.pharmacity.vn/cefuroxim-500mg-1-vi-x-10-vien-vpc.html
https://www.pharmacity.vn/alfavir-tablet-incepta-10-vien.html
https://www.pharmacity.vn/levofloxacin-kabi-100ml.html
https://www.pharmacity.vn/ciprofloxacin-kabi-200mg-chai-100ml.html
https://www.pharmacity.vn/augbidil-625-h14.html
https://www.pharmacity.vn/agi-cotrim-960mg-hop-100-vien.html
https://www.pharmacity.vn/denvin-300mg-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/griseofulvin-500mg10-vi-x10-vien.html
https://www.pharmacity.vn/acigmentin-1000mg-2vi-x-7-vien.html
https://www.pharmacity.vn/gentamicin-kabi-80mg2ml-hop-100-ong.html
https://www.pharmacity.vn/bot-pha-hon-dich-uong-augmentin-es-gsk-50ml.html
https://www.pharmacity.vn/rx-thuoc-khang-sinh#
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-hiv-aluvia-tab-200mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-vi-khuan-nhay-cam-viem-amidan-viem-tai-giua-viem-xoang-cap-klacid-125mg-5ml.html
https://www.pharmacity.vn/griseofulvin-500mg-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-giun-chi-pizar-6-hop-4vien.html
https://www.pharmacity.vn/pyclin-300-hop-10-vi-x-10-vien.html
https://www.pharmacity.vn/biseptol-80ml.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-duong-ho-hap-psm-claminat-1g.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-pms-roxithromycin-150mg-2vi-x10vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-da-doncef-500mg.html
https://www.pharmacity.vn/distocide-600mg-hop-1-vi-x-4-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-dieu-tri-nhiem-hiv-tuyp-1-savi-tenofovir-300mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-nhiem-khuan-do-chlamydia-rickettsia-lau-cau-xoan-khuan-ta-tetracyclin-500mg-10-vi-x-10-vien.html
https://www.pharmacity.vn/metronidazol-250-hop-10-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-nha-chu-man-tinh-sau-rang-viem-nuou-rang-metrogyl-denta-tuyp-20g.html
https://www.pharmacity.vn/aticef-250-hop-24-goi.html
https://www.pharmacity.vn/fosmicin-500mg-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/aticef-500-caps-hop-2-vi-x-7-vien.html
https://www.pharmacity.vn/cefprozil-250-us-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/pricefil-500mg-1-vi-x-12-vienhop.html
https://www.pharmacity.vn/ofloxacin-200mg-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/haginat-500-hop-2-vi-x-5-vien.html
https://www.pharmacity.vn/clabact-500-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-nhiem-khuan-crocin-100mg-kid-25-goihop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-forlen-600mg-2-vi-x-10-vien-hop.html
https://www.pharmacity.vn/ofmantine-625mg-2-vi-x-7-vienhop.html
https://www.pharmacity.vn/thuoc-tri-viem-nhiem-do-ki-sinh-trung-mecefix-be-50mg-merap-20-goi-x-1grhop.html
https://www.pharmacity.vn/glocip-500-hop-3-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-fabamox-250mg-12-goi-x-1-4g-hop.html
https://www.pharmacity.vn/trimoxtal-500500mg-2vi-x-7vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-orenko-200mg-2-vi-x-10-vien-hop.html
https://www.pharmacity.vn/ivermectin-3-at-hop-1-vi-x-4-vien.html
https://www.pharmacity.vn/pymeazi-500-hop-1-vi-x-3-vien.html
https://www.pharmacity.vn/cefatam-750mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/pricefil-2505ml-chai-30ml.html
https://www.pharmacity.vn/thuoc-khang-sinh-negacef-500mg-2-vi-x-5-vien.html
https://www.pharmacity.vn/thuoc-khang-viem-bactamox-375mg-12-goi-imexpharm.html
https://www.pharmacity.vn/thuoc-khang-sinh-cetraxal-15-ong-x-025mlhop.html
https://www.pharmacity.vn/epclusa-100400mg-hop-28vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-hiv-tuyp-1-viem-gan-b-man-tinh-agifovir-300mg-3-vi-x-10-vienhop.html
https://www.pharmacity.vn/vien-nen-medskin-clovir-200mg-dhg-tri-nhiem-virus-thuy-dau-va-zona-herpes-simplex-5-vi-x-10-vien.html
https://www.pharmacity.vn/nirdicin-500mg-hop-1-vi-x-10-vien.html
https://www.pharmacity.vn/pharcavir-25mg.html
https://www.pharmacity.vn/haginir-300-2vix10vien.html
https://www.pharmacity.vn/tratrison-crm-10g-1.html
https://www.pharmacity.vn/tetracyclin-caps-500mg-box-200.html
https://www.pharmacity.vn/cefpodoxim-hv-tab-fc-200mg-box-30.html
https://www.pharmacity.vn/zolgyl-tab-2vi-x-10vien.html
https://www.pharmacity.vn/ibisaol-caps-pllt-100mg-box-10-hop-10-vien.html
https://www.pharmacity.vn/pharbaren-500mg-hop-1-vi-x-10-vien.html
https://www.pharmacity.vn/agiclari-500mg-2vi-x-5vien.html
https://www.pharmacity.vn/efodyl-sac-150mg-20goix15g.html
https://www.pharmacity.vn/letdion-eye-drops-05-5ml.html
https://www.pharmacity.vn/levoleo-500mg-1-vi-x-10vien.html
https://www.pharmacity.vn/nifin-tab-fc-200mg-box-20dhg-pharma.html
https://www.pharmacity.vn/ciprom-500mg-5-vi-x-10-vien.html
https://www.pharmacity.vn/trimeseptol-480mg-25-vi-x-20-vien.html
https://www.pharmacity.vn/ofbexim-200-usp-hop-30-vien.html
https://www.pharmacity.vn/fugentin-875mg125mg-elpen-hop-12-goi.html
https://www.pharmacity.vn/bostolox-100mg-hop-24-goi.html
https://www.pharmacity.vn/ciprofloxacin-250mg-us-pharma-hop-10-goi.html
https://www.pharmacity.vn/clindastad-150mg-stella-hop-100v.html
https://www.pharmacity.vn/elomentin-pos-400mg-57mg.html
https://www.pharmacity.vn/thuoc-khang-sinh-klamentin-625mg-hop-3-vi-x-4-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-hong-va-viem-amidan-clarithromycin-stada-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-nhiem-khuan-do-vi-khuan-nhay-cam-gay-ra-cephalexin-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-trieu-chung-nhiem-khuan-duong-ho-hap-zinnat-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-nhiem-khuan-nhe-trung-binh-cac-benh-nhiem-khuan-do-vi-khuan-nhay-cam-levofloxacin-stada-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-do-cac-vi-khuan-nhay-cam-cefalexin-500mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/fovirpoxil30vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-nhiem-khuan-duong-ho-hap-cephalexin-250mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-duong-ho-hap-klacid-mr-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-xoang-cap-viem-phe-quan-man-tinh-tavanic-500mg.html
https://www.pharmacity.vn/cefimbrano-100mg-hop-10goi.html
https://www.pharmacity.vn/zinecox-200mg-2vi-x-10vien.html
https://www.pharmacity.vn/claminat-500-mg625-mg-hop-12-goi-x-15g.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-nam-candida-o-niem-mac-duong-tieu-hoa-nystatin-500000iu-2-vi-x-8-vienhop.html
https://www.pharmacity.vn/hafixim-100-kids-hop-24-goi.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-brucella-benh-dich-ta-doxycylin-100mg.html
https://www.pharmacity.vn/getino-b-300mg-chai-30-vien.html
https://www.pharmacity.vn/tvcefuroxime-500mg-3-vi-x-10-vienhop.html
https://www.pharmacity.vn/cefdinir-300mg-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-nhiem-pyfaclor-500mg-1-vi-x-12-vien.html
https://www.pharmacity.vn/medskin-clovir-800-hop-3-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-nhiem-khuan-crocin-200mg-1-vi-x-10-vien-hop.html
https://www.pharmacity.vn/zidocindhg-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/getzlox-750mg-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-ho-hap-claminat-500mg-125mg-hop-12-goi.html
https://www.pharmacity.vn/gentamicin-80mg2ml-10-ong-x-2mlhop.html
https://www.pharmacity.vn/ofmantine-1g-2-vi-x-7-vienhop.html
https://www.pharmacity.vn/meiact-50mg-21-goihop.html
https://www.pharmacity.vn/agiclovir-800-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/cefimed-200-2-vi-x-4-vienhop.html
https://www.pharmacity.vn/vigentin-875125-dt-hop-2-vi-x-7-vien.html
https://www.pharmacity.vn/cttprozil-capl-fc-500mg-1vi-x-10vien.html
https://www.pharmacity.vn/thuoc-khang-sinh-hagimox-250mg-hop-24-goi.html
https://www.pharmacity.vn/hapenxin-500mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-iba-mentin-1000mg-62-5mg-2-vi-x-7-vien-hop.html
https://www.pharmacity.vn/thuoc-khang-viem-metronidazol-250mg-10-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-khang-sinh-bluemoxi-400mg-1-vi-x-7-vien.html
https://www.pharmacity.vn/thuoc-khang-sinh-rifampicin-300mg-10-vi-x-10-vien.html
https://www.pharmacity.vn/at-entecavir-05mg-3vi-x-10-vien.html
https://www.pharmacity.vn/vemlidy-25mg-chai-30-vien.html
https://www.pharmacity.vn/levofloxacin-500-imexpharm-1vi-x10vien.html
https://www.pharmacity.vn/refix-550mg-hop-3vi-x-10-vien.html
https://www.pharmacity.vn/direntab-200-hop-1-vi-x-10-vien.html
https://www.pharmacity.vn/atasic-200mg-3vi-x-10-vien.html
https://www.pharmacity.vn/usarmicin-hop-2-vi-x10-vien.html
https://www.pharmacity.vn/armten-200mgv-hop-1vi-x-10-vien.html
https://www.pharmacity.vn/cefriven-200mg-hop-2vi-x-10-vien.html
https://www.pharmacity.vn/ampicillin-500mg-10vi-x-10vien-brawn.html
https://www.pharmacity.vn/medaxetine-500mg-1vi-x-10vien.html
https://www.pharmacity.vn/lucass-200-2vi-x-10vien.html
https://www.pharmacity.vn/imefed-dt-500mg125mg-2-vi-x-7-vien.html
https://www.pharmacity.vn/acyclovir-tab-800mg-boston-5vi-x-5vien.html
https://www.pharmacity.vn/cefalex-500mg-10-vi-x-10-vien.html
https://www.pharmacity.vn/zelfamox-tab-dt-875mg-125-2vix7vien.html
https://www.pharmacity.vn/lincomycin-caps-500mg-10vi-x-10vien.html
https://www.pharmacity.vn/acyclovir-stella-400mg-hop-50-vien.html
https://www.pharmacity.vn/rodogyl-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-do-duong-ho-hap-gay-ra-dalacin-c-300mg.html
https://www.pharmacity.vn/azicine-hop-1-vi-x-6-vien.html
https://www.pharmacity.vn/ampicillin-500mg-hop-10-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-trung-rang-mieng-cap-man-tinh-dorogyne-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-cho-tre-em-augmentin-250mg.html
https://www.pharmacity.vn/clarithromycin-stella-250-mg-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-duong-ho-hap-duong-sinh-duc-da-zinnat-tab-250mg-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-truong-hop-nhiem-trung-do-vi-khuan-duong-ho-hap-amoxicillin-500mg.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-giun-chi-pizar-3-1-vi-x-4-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-benh-viem-tai-giua-va-cac-benh-nhiem-khuan-cotrimstada-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-du-phong-va-dieu-tri-cac-nhiem-khuan-gay-ra-boi-vi-khuan-nhay-cam-penicilin-v-kali-1000000iu-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-euvipharm-cefpodoxim-200mg-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-opecipro-500-2-vi-x-7-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-gan-b-man-tinh-o-nguoi-lon-entecavir-stada-05mg-3-vie-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-viem-hong-viem-amidan-viem-tai-giua-viem-xoang-mecefix-75mg.html
https://www.pharmacity.vn/klamentin-2503125-hop-24-goi.html
https://www.pharmacity.vn/hafixim-50-kids-hop-24-goi.html
https://www.pharmacity.vn/imexime-100mg-hop12goi-imexpharm.html
https://www.pharmacity.vn/pharmox-500mg-10vi-x10vien.html
https://www.pharmacity.vn/griseofulvin-5-hop-1-tuyp-nhom-x-10g.html
https://www.pharmacity.vn/medskin-clovir-400-hop-6-vi-x-10-vien.html
https://www.pharmacity.vn/haginat-125-hop-24-goi.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-va-dieu-tri-du-phong-bien-chung-nhiem-trung-tai-cho-sau-phau-thuat-rang-mieng-spiranisol-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/levodhg-250-hop-3-vi-x-10-vien.html
https://www.pharmacity.vn/levodhg-500-hop-3-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-droxicef-500mg-10-vi-x-10-vien-hop.html
https://www.pharmacity.vn/azithromycin-250-hop-10-vi-x-6-vien.html
https://www.pharmacity.vn/rovas-3m-hop-2-vi-x-5-vien.html
https://www.pharmacity.vn/bicebid-200mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/tvcefuroxime-250mg-2-vi-x-10-vienhop.html
https://www.pharmacity.vn/hepbest-25mg-hop-30-vien.html
https://www.pharmacity.vn/cefprozil-500-us-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/cefbuten-200mg-1-vi-x-10-vienhop.html
https://www.pharmacity.vn/anaferon-for-children-hop-1-vi-x-20-vien.html
https://www.pharmacity.vn/cefadroxil-eg-500mg-10-vi-x-10-vienhop.html
https://www.pharmacity.vn/efodyl-500-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/ciclevir-400mg-hop-10-vi-x-5-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-duong-ho-hap-duong-tiet-nieu-pms-bactamox-750mg.html
https://www.pharmacity.vn/thuoc-khang-sinh-hapenxin-250-kids-hop-24-goi.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-amoxicillin-250mg-imexpharm-12-goi-hop.html
https://www.pharmacity.vn/haginat-250-hop-2-vi-x-5-vien.html
https://www.pharmacity.vn/vazigoc-4-vi-x-7-vienhop.html
https://www.pharmacity.vn/cepoxitil-200-hop-1-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-khang-sinh-garosi-500mg-1-vi-x-3-vien.html
https://www.pharmacity.vn/cefprozil-500-us-hop-2-vi-x-10-vien.html
https://www.pharmacity.vn/ofbexim-tab-fc-200mg-3vi-x-10vien.html
https://www.pharmacity.vn/undtas-500-hop-3-vi-x-10-vien.html
https://www.pharmacity.vn/zebacef-tab-300mg-1vi-x-10vien.html
https://www.pharmacity.vn/auclanityl-2vi-x-7-vien.html
https://www.pharmacity.vn/rocephin-1g-iv-b1-inj-10ml.html
https://www.pharmacity.vn/eucinat-250-h1vi10vien.html
https://www.pharmacity.vn/ciprothepharm-capl-fc-500mg-box-100.html
https://www.pharmacity.vn/cotrimoxazol-tab-480mg-box-400.html
https://www.pharmacity.vn/taromentin-457mg5ml-chai-70ml.html
https://www.pharmacity.vn/pricefil-susp-dry-250mg-5ml-60ml.html
https://www.pharmacity.vn/azismile-susp-dry-200mg-5ml-15ml.html
https://www.pharmacity.vn/ortizole-500mg-5-vi-x-6-vien.html
https://www.pharmacity.vn/acyclovir-stella-800mg-hop-50-vien.html
https://www.pharmacity.vn/betamox-es-1-chai-100ml-atral.html
https://www.pharmacity.vn/sumakin-1g-mekophar-hop-14-vien.html
https://www.pharmacity.vn/bot-pha-hon-dich-uong-augmentin-es-gsk-100ml.html
https://www.pharmacity.vn/pyme-azi-caps-250mg-box-6.html
https://www.pharmacity.vn/ofloxacin-drops-eye-6ml-1.html
https://www.pharmacity.vn/pyme-fucan-caps-150mg-box-1.html
https://www.pharmacity.vn/ceftenmax-200-2vi-x-10vien.html
https://www.pharmacity.vn/azizi-500mg-hop-1-vi-x-3-vien.html
https://www.pharmacity.vn/cepmox-clav-875mg-125mg-2-vi-x-7-vien.html
https://www.pharmacity.vn/imefed-250mg3125mg-hop-1-tui-x-12-goi.html
https://www.pharmacity.vn/doxycycline-100mg-hop-10-vi-x-10-vien.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-nang-du-phong-benh-nao-mo-cau-scanax-500mg-5-vi-x-10-vienhop.html
https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-duong-ho-hap-tieu-nieu-ospexin-500mg.html
https://www.pharmacity.vn/bot-pha-hon-dich-uong-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-tiet-nieu-mo-da-cefaclor-125mg-10-goi-x-2ghop.html
https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-duong-sinh-duc-tetracylin-500mg.html

<h4>Thực hiện crawl lại các link lỗi</h4>

In [7]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException, NoSuchElementException 
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import re
import time

In [8]:
def set_up_driver():
    chrome_options = Options()
    chrome_options.add_argument("--headless") 
    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument("start-maximized")
    chrome_options.add_argument("--disable-blink-features=AutomationControlled") # Tắt tính năng phát hiện tự động của trình duyệt
    chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"]) # Loại bỏ thông báo "Chrome is being controlled by automated test software"
    chrome_options.add_experimental_option('useAutomationExtension', False) # Vô hiệu hóa tiện ích mở rộng tự động hóa
    driver = webdriver.Chrome(options=chrome_options)
    return driver

In [9]:
def get_product_information(driver, label):
    try:
        # Tìm tất cả p tags có class text-sm (chứa label)
        labels = driver.find_elements(By.CSS_SELECTOR, "p[class*='text-sm'][class*='leading-14']")
        
        for label_el in labels:
            label_text = label_el.text.strip()
            
            if label.lower() in label_text.lower():
                # Lấy parent div grid rồi tìm value trong sibling
                parent = label_el.find_element(By.XPATH, "./ancestor::div[contains(@class, 'grid')][1]")
                # Tìm div chứa text value (không phải label)
                value_els = parent.find_elements(By.CSS_SELECTOR, "div")
                
                for val in value_els:
                    val_text = val.text.strip()
                    # Lấy value khác label
                    if val_text and val_text != label_text:
                        return val_text
    except:
        return None

In [10]:
def get_section_detail(driver, section_id):
    try:
        # Tìm element theo id
        heading = driver.find_element(By.ID, section_id)
        
        # Lấy siblings trực tiếp từ heading
        siblings = heading.find_elements(By.XPATH, "./following-sibling::*")
        
        content = []
        for sib in siblings:
            tag = sib.tag_name.lower()
            
            # Dừng khi gặp heading tiếp theo (h2 hoặc h3)
            if tag in ["h2", "h3"]:
                break
            
            # Lấy text
            t = sib.get_attribute("textContent") or ""
            t = t.strip()
            if t:
                content.append(t)
        
        return "\n".join(content) if content else None
    
    except:
        return None

In [11]:
def get_product_images(driver):
    images = []
    
    try:
        # Tìm tất cả img elements trong product detail
        img_elements = driver.find_elements(By.CSS_SELECTOR, "img[src*='production-cdn'], img[src*='pharmacity']")
        
        for img in img_elements:
            src = img.get_attribute("src")
            
            # Nếu src rỗng, thử lấy từ srcset hoặc data-src
            if not src:
                src = img.get_attribute("srcset") or img.get_attribute("data-src")
            
            if src:
                # Extract URL đầy đủ từ production-cdn.pharmacity.io
                match = re.search(r'(https://production-cdn\.pharmacity\.io/[^\s]+)', src)
                if match:
                    url = match.group(1).split()[0]  # Loại bỏ size info nếu có
                    if url not in images:
                        images.append(url)
                # Hoặc lấy trực tiếp nếu là URL hợp lệ
                elif src.startswith('http') and 'pharmacity' in src:
                    if src not in images:
                        images.append(src)
    
    except Exception as e:
        print(f"Error getting images: {e}")
    
    return images

In [12]:
# Sửa lại phần crawl name
def get_name(driver):
    try:
        name = driver.find_element(By.XPATH, "//*[@id='pmc-v2']/div[4]/div/div[1]/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/h2").text.strip()
        time.sleep(1)
        return name if name else None
    except:
        return None

In [13]:
def get_medicine_data(driver):
    try:
        WebDriverWait(driver, 3).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.mb-4.grid.grid-cols-1.gap-6.lg\:grid-cols-2.lg\:items-start > div.grid.grid-cols-1.gap-4 > div > div > div.flex.flex-col.gap-4")))
    except:
        pass

    try:
        name = driver.find_element(By.XPATH, "//*[@id='pmc-v2']/div[4]/div/div[1]/div[2]/div[2]/div[2]/div/div/div[2]/div[2]/h2").text.strip()
        time.sleep(1)
    except:
        name = None
    
    try:
        price = driver.find_element(By.CSS_SELECTOR, "#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.mb-4.grid.grid-cols-1.gap-6.lg\:grid-cols-2.lg\:items-start > div.grid.grid-cols-1.gap-4 > div > div > div.flex.flex-col.gap-4 > div.rounded-xs.bg-surface-canvas > div > div.flex.flex-row.items-center.gap-2 > h3").text.strip()
        time.sleep(1)
    except:
        price = None

    images = get_product_images(driver)
    time.sleep(1)

    nha_san_xuat = get_product_information(driver, "Nhà sản xuất:")
    noi_san_xuat = get_product_information(driver, "Nơi sản xuất:")
    thuoc_can_ke_don = get_product_information(driver, "Thuốc cần kê đơn:")
    hoat_chat = get_product_information(driver,"Hoạt chất:")
    chi_dinh_tom_tat = get_product_information(driver, "Chỉ định:")
    dang_bao_che = get_product_information(driver, "Dạng bào chế:")
    quy_cach = get_product_information(driver, "Quy cách:")
    luu_y = get_product_information(driver, "Lưu ý:")
    
    try:
        time.sleep(1)
        btn_section = driver.find_element(By.CSS_SELECTOR,"#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.relative.left-1\/2.right-1\/2.-ml-\[50vw\].-mr-\[50vw\].w-screen.bg-surface-neutral-canvas > div > div:nth-child(1) > div > div.max-md\:pb-2.md\:h-auto.md\:max-h-\[inherit\] > div > div.relative.flex.items-center.justify-center")
        time.sleep(1)
        btn = btn_section.find_element(By.TAG_NAME, "button")
        driver.execute_script("arguments[0].scrollIntoView({block: 'center'});", btn)
        time.sleep(1)
        btn.click()
        time.sleep(1)
    except Exception as e:
        print(f"Error clicking 'Xem thêm' button: {e}")


    mo_ta = get_section_detail(driver, "mo-ta")
    thanh_phan = get_section_detail(driver, "thanh-phan")
    chi_dinh_chi_tiet = get_section_detail(driver, "chi-dinh")
    huong_dan_su_dung = get_section_detail(driver, "huong-dan-su-dung")
    cach_su_dung = get_section_detail(driver, "cach-su-dung")
    than_trong = get_section_detail(driver, "than-trong")
    thong_tin_san_xuat = get_section_detail(driver, "thong-tin-san-xuat")

    return {
        "name": name,
        "price": price,
        "images": images,
        "nha_san_xuat": nha_san_xuat,
        "noi_san_xuat": noi_san_xuat,
        "thuoc_can_ke_don": thuoc_can_ke_don,
        "hoat_chat": hoat_chat,
        "chi_dinh_tom_tat": chi_dinh_tom_tat,
        "dang_bao_che": dang_bao_che,
        "quy_cach": quy_cach,
        "luu_y": luu_y,
        "mo_ta": mo_ta,
        "thanh_phan": thanh_phan,
        "chi_dinh_chi_tiet": chi_dinh_chi_tiet,
        "huong_dan_su_dung": huong_dan_su_dung,
        "cach_su_dung": cach_su_dung,
        "than_trong": than_trong,
        "thong_tin_san_xuat": thong_tin_san_xuat
    }

<>:3: SyntaxWarning: invalid escape sequence '\['
<>:14: SyntaxWarning: invalid escape sequence '\['
<>:33: SyntaxWarning: invalid escape sequence '\['
<>:3: SyntaxWarning: invalid escape sequence '\['
<>:14: SyntaxWarning: invalid escape sequence '\['
<>:33: SyntaxWarning: invalid escape sequence '\['
C:\Users\Admin\AppData\Local\Temp\ipykernel_9868\832258993.py:3: SyntaxWarning: invalid escape sequence '\['
  WebDriverWait(driver, 3).until(EC.presence_of_element_located((By.CSS_SELECTOR, "#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.mb-4.grid.grid-cols-1.gap-6.lg\:grid-cols-2.lg\:items-start > div.grid.grid-cols-1.gap-4 > div > div > div.flex.flex-col.gap-4")))
C:\Users\Admin\AppData\Local\Temp\ipykernel_9868\832258993.py:14: SyntaxWarning: invalid escape sequence '\['
  price = driver.find_element(By.CSS_SELECTOR, "#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.mb-4.grid.grid-cols-1.gap-6.lg\:grid-cols-2.lg\:items-start > div.grid.grid-cols-1.gap-4 > div > div > div.flex.flex-col.gap-4 > div.rounded-xs.bg-surface-canvas > div > div.flex.flex-row.items-center.gap-2 > h3").text.strip()
C:\Users\Admin\AppData\Local\Temp\ipykernel_9868\832258993.py:33: SyntaxWarning: invalid escape sequence '\['
  btn_section = driver.find_element(By.CSS_SELECTOR,"#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.relative.left-1\/2.right-1\/2.-ml-\[50vw\].-mr-\[50vw\].w-screen.bg-surface-neutral-canvas > div > div:nth-child(1) > div > div.max-md\:pb-2.md\:h-auto.md\:max-h-\[inherit\] > div > div.relative.flex.items-center.justify-center")

In [14]:
# Lưu các dòng bị lỗi vào file CSV để crawl lại sau
error_df = pharmacity_df_9[error_name]
error_df.to_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_error_links.csv", index=False)
error_df.shape
error_df.head()

,name,price,images,nha_san_xuat,noi_san_xuat,thuoc_can_ke_don,hoat_chat,chi_dinh_tom_tat,dang_bao_che,quy_cach,...,huong_dan_su_dung,cach_su_dung,than_trong,thong_tin_san_xuat,url,category,drug_type,category_link,category_name,error
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/desloratadine-5mg-ho...,NaN,NaN,NaN,NaN,Message: no such element: Unable to locate ele...
117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/azicine-500-stella-1...,NaN,NaN,NaN,NaN,Message: no such element: Unable to locate ele...
206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/kodemin-softcap-10vi...,NaN,NaN,NaN,NaN,Message: no such element: Unable to locate ele...
238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/thuoc-cam-lanh#,NaN,NaN,NaN,NaN,Message: no such element: Unable to locate ele...
270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/nasol-spray-chai-70m...,NaN,NaN,NaN,NaN,Message: no such element: Unable to locate ele...

In [ ]:
# Thực hiện crawl lại các link bị lỗi
if len(error_df) > 0:
    driver = None
    results = []
    retry_failed = []  # Lưu link vẫn lỗi để retry lần sau
    
    try:
        driver = set_up_driver()
        
        for i, row in error_df.iterrows():
            url = row['url']  
            drug_type = row.get('drug_type') if hasattr(row, 'get') else row.get('drug_type', '')
            category_link = row.get('category_link') if hasattr(row, 'get') else row.get('category_link', '')
            
            try:
                print(f"[{i+1}/{len(error_df)}] Crawling: {url}")
                driver.get(url)
                time.sleep(3)
                
                data = get_medicine_data(driver)
                
                # Kiểm tra xem data có hợp lệ không (name không rỗng)
                if data.get('name') and str(data.get('name')).lower() != 'none':
                    data['url'] = url
                    data['drug_type'] = drug_type
                    data['category_link'] = category_link
                    results.append(data)
                    print(f"Crawled successfully: {data.get('name')}")
                else:
                    print(f"Invalid data (name empty): {url}")
                    retry_failed.append(url)
                    
            except Exception as e:
                print(f"Error crawling {url}: {e}")
                retry_failed.append(url)
                
                # Nếu lỗi liên tục, khởi tạo lại driver
                if len(retry_failed) > 3:
                    print("Reinitializing driver...")
                    driver.quit()
                    driver = set_up_driver()
                    retry_failed = []
    
    finally:
        if driver is not None:
            driver.quit()
    
    # Lưu kết quả
    if len(results) > 0:
        df_recrawled = pd.DataFrame(results)
        df_recrawled.to_csv(
            "pharmacity_medicines_recrawled.csv",
            index=False,
            encoding='utf-8'
        )
        print(f"\Saved {len(results)} successfully crawled records")
    
    # Lưu các link vẫn lỗi để crawl lại lần sau
    if len(retry_failed) > 0:
        error_df_retry = error_df[error_df['url'].isin(retry_failed)]
        error_df_retry.to_csv(
            "pharmacity_medicines_still_error.csv",
            index=False,
            encoding='utf-8'
        )
        print(f"{len(retry_failed)} links still have errors - saved to 'still_error.csv'")
    
    print(f"\nSummary:")
    print(f"- Successfully recrawled: {len(results)}")
    print(f"- Still failed: {len(retry_failed)}")

<>:56: SyntaxWarning: invalid escape sequence '\S'
<>:56: SyntaxWarning: invalid escape sequence '\S'
C:\Users\Admin\AppData\Local\Temp\ipykernel_9868\1206357457.py:56: SyntaxWarning: invalid escape sequence '\S'
  print(f"\Saved {len(results)} successfully crawled records")

[49/493] Crawling: https://www.pharmacity.vn/desloratadine-5mg-hop-2vi-x-15-vien.html
Crawled successfully: Viên nén Desloratadine 5mg trị viêm mũi dị ứng, mày đay, ngứa (2 vỉ x 15 viên)
[118/493] Crawling: https://www.pharmacity.vn/azicine-500-stella-1-vi-x-6-vien.html
Crawled successfully: Azicine Stella 500mg điều trị các trường hợp nhiễm khuẩn gây ra bởi các vi khuẩn nhạy cảm với thuốc (1 vỉ x 6 viên)
[207/493] Crawling: https://www.pharmacity.vn/kodemin-softcap-10vi-x-10vien.html
Crawled successfully: Viên nang Kodemin trị ho khan do kích thích (10 vỉ x 10 viên)
[239/493] Crawling: https://www.pharmacity.vn/thuoc-cam-lanh#
Error clicking 'Xem thêm' button: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.relative.left-1\/2.right-1\/2.-ml-\[50vw\].-mr-\[50vw\].w-screen.bg-surface-neutral-canvas > div > div:nth-child(1) > div > div.max-md\:pb-2.md\:h-auto.md\:max-h-\[inherit\] > div > div.relative.flex.items-center.justify-center"}
  (Session info: chrome=145.0.7632.159); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff7cbdaaa55
	0x7ff7cbb08630
	0x7ff7cb89d75d
	0x7ff7cb8f862e
	0x7ff7cb8f893c
	0x7ff7cb948d87
	0x7ff7cb94591c
	0x7ff7cb8e9098
	0x7ff7cb8e9f83
	0x7ff7cbdd7810
	0x7ff7cbdd1afd
	0x7ff7cbdf2c1a
	0x7ff7cbb23345
	0x7ff7cbb2b81c
	0x7ff7cbb11924
	0x7ff7cbb11ad6
	0x7ff7cbaf7e47
	0x7ffd717ae8d7
	0x7ffd722cc40c

Invalid data (name empty): https://www.pharmacity.vn/thuoc-cam-lanh#
[271/493] Crawling: https://www.pharmacity.vn/nasol-spray-chai-70ml.html
Invalid data (name empty): https://www.pharmacity.vn/nasol-spray-chai-70ml.html
[329/493] Crawling: https://www.pharmacity.vn/tinh-dau-tre-em-nasomom-4-spray-chai-70ml.html
Invalid data (name empty): https://www.pharmacity.vn/tinh-dau-tre-em-nasomom-4-spray-chai-70ml.html
[444/493] Crawling: https://www.pharmacity.vn/at-arginin-200mg-10-vi-x10-vien.html
Crawled successfully: Viên nang A.T Arginin 200mg hạ men gan, tăng cường chức năng gan, bổ gan (10 vỉ x10 viên)
[461/493] Crawling: https://www.pharmacity.vn/nhom-san-pham-giam-dau-da-day-cho-nguoi-lon.html
Invalid data (name empty): https://www.pharmacity.vn/nhom-san-pham-giam-dau-da-day-cho-nguoi-lon.html
[661/493] Crawling: https://www.pharmacity.vn/thuoc-da-lieu#
Error clicking 'Xem thêm' button: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.relative.left-1\/2.right-1\/2.-ml-\[50vw\].-mr-\[50vw\].w-screen.bg-surface-neutral-canvas > div > div:nth-child(1) > div > div.max-md\:pb-2.md\:h-auto.md\:max-h-\[inherit\] > div > div.relative.flex.items-center.justify-center"}
  (Session info: chrome=145.0.7632.159); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff7cbdaaa55
	0x7ff7cbb08630
	0x7ff7cb89d75d
	0x7ff7cb8f862e
	0x7ff7cb8f893c
	0x7ff7cb948d87
	0x7ff7cb94591c
	0x7ff7cb8e9098
	0x7ff7cb8e9f83
	0x7ff7cbdd7810
	0x7ff7cbdd1afd
	0x7ff7cbdf2c1a
	0x7ff7cbb23345
	0x7ff7cbb2b81c
	0x7ff7cbb11924
	0x7ff7cbb11ad6
	0x7ff7cbaf7e47
	0x7ffd717ae8d7
	0x7ffd722cc40c

Invalid data (name empty): https://www.pharmacity.vn/thuoc-da-lieu#
[681/493] Crawling: https://www.pharmacity.vn/bacterocin-5g.html
Invalid data (name empty): https://www.pharmacity.vn/bacterocin-5g.html
[699/493] Crawling: https://www.pharmacity.vn/bacterocin-15g.html
Invalid data (name empty): https://www.pharmacity.vn/bacterocin-15g.html
[770/493] Crawling: https://www.pharmacity.vn/neutrivit-5000-bidiphar-h44-inj.html
Crawled successfully: Bột pha tiêm Neutrivit 5000 Bidiphar viêm dây thần kinh, thiếu vitamin B (4 lọ bột + 4 ống dung môi)
[771/493] Crawling: https://www.pharmacity.vn/thuoc-than-kinh#
Error clicking 'Xem thêm' button: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.relative.left-1\/2.right-1\/2.-ml-\[50vw\].-mr-\[50vw\].w-screen.bg-surface-neutral-canvas > div > div:nth-child(1) > div > div.max-md\:pb-2.md\:h-auto.md\:max-h-\[inherit\] > div > div.relative.flex.items-center.justify-center"}
  (Session info: chrome=145.0.7632.159); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff7cbdaaa55
	0x7ff7cbb08630
	0x7ff7cb89d75d
	0x7ff7cb8f862e
	0x7ff7cb8f893c
	0x7ff7cb948d87
	0x7ff7cb94591c
	0x7ff7cb8e9098
	0x7ff7cb8e9f83
	0x7ff7cbdd7810
	0x7ff7cbdd1afd
	0x7ff7cbdf2c1a
	0x7ff7cbb23345
	0x7ff7cbb2b81c
	0x7ff7cbb11924
	0x7ff7cbb11ad6
	0x7ff7cbaf7e47
	0x7ffd717ae8d7
	0x7ffd722cc40c

Invalid data (name empty): https://www.pharmacity.vn/thuoc-than-kinh#
[800/493] Crawling: https://www.pharmacity.vn/cao-dan-giam-dau-tiger-balm-plaster-rd-7x10cm-tui-3-mieng.html
Crawled successfully: Tiger Balm Plaster-RD 7x10cm – Cao dán giảm đau nhức cơ khớp (12 túi x 3 miếng)
[818/493] Crawling: https://www.pharmacity.vn/thuoc-co-xuong-khop#
Error clicking 'Xem thêm' button: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.relative.left-1\/2.right-1\/2.-ml-\[50vw\].-mr-\[50vw\].w-screen.bg-surface-neutral-canvas > div > div:nth-child(1) > div > div.max-md\:pb-2.md\:h-auto.md\:max-h-\[inherit\] > div > div.relative.flex.items-center.justify-center"}
  (Session info: chrome=145.0.7632.159); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff7cbdaaa55
	0x7ff7cbb08630
	0x7ff7cb89d75d
	0x7ff7cb8f862e
	0x7ff7cb8f893c
	0x7ff7cb948d87
	0x7ff7cb94591c
	0x7ff7cb8e9098
	0x7ff7cb8e9f83
	0x7ff7cbdd7810
	0x7ff7cbdd1afd
	0x7ff7cbdf2c1a
	0x7ff7cbb23345
	0x7ff7cbb2b81c
	0x7ff7cbb11924
	0x7ff7cbb11ad6
	0x7ff7cbaf7e47
	0x7ffd717ae8d7
	0x7ffd722cc40c

Invalid data (name empty): https://www.pharmacity.vn/thuoc-co-xuong-khop#
[823/493] Crawling: https://www.pharmacity.vn/cao-dan-giam-dau-tiger-balm-plaster-rd-10x14cm-tui-3-mieng.html
Crawled successfully: Cao dán Tiger Balm Plaster-RD 10X14cm giảm các triệu chứng mỏi cơ, giảm đau và nhức cơ (túi 3 miếng)
[836/493] Crawling: https://www.pharmacity.vn/tiger-balm-white-30g.html
Crawled successfully: Cao xoa Tiger Balm White trị cảm cúm, sổ mũi, nghẹt mũi, chóng mặt, say tàu xe (hộp 30g)
[846/493] Crawling: https://www.pharmacity.vn/tiger-balm-oil-28ml.html
Crawled successfully: Dầu xoa Tiger Balm Oil 28ml đau đầu, đau nhức toàn thân, bong gân (chai 28ml)
[847/493] Crawling: https://www.pharmacity.vn/tiger-balm-oil-57ml.html
Crawled successfully: Dầu xoa Tiger Balm Oil 57ml đau đầu, đau nhức toàn thân, bong gân (chai 57ml)
[849/493] Crawling: https://www.pharmacity.vn/cao-ho-do-giam-dau-nhuc-co-tiger-balm-red-19-4g.html
Crawled successfully: Cao xoa Tiger balm RED trị cảm cúm, sổ mũi, nghẹt mũi, chóng mặt, say tàu xe (hộp 19.4g)
[866/493] Crawling: https://www.pharmacity.vn/tiger-balm-red-30g.html
Crawled successfully: Cao xoa Tiger Balm Red trị cảm cúm, sổ mũi, nghẹt mũi, chóng mặt, say tàu xe (hộp 30g)
[867/493] Crawling: https://www.pharmacity.vn/tiger-balm-white-194g.html
Crawled successfully: Cao xoa Tiger Balm White trị cảm cúm, sổ mũi, nghẹt mũi, chóng mặt, say tàu xe (hộp 19.4g)
[920/493] Crawling: https://www.pharmacity.vn/silymarin-vcp-10-vi-x-10-vien.html
Invalid data (name empty): https://www.pharmacity.vn/silymarin-vcp-10-vi-x-10-vien.html
[946/493] Crawling: https://www.pharmacity.vn/vitamin-va-khoang-chat#
Error clicking 'Xem thêm' button: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#pmc-v2 > div.bg-white.pt-\[--pt-main-pt\].lg\:pt-0 > div > div.bg-white > div:nth-child(2) > div.relative.left-1\/2.right-1\/2.-ml-\[50vw\].-mr-\[50vw\].w-screen.bg-surface-neutral-canvas > div > div:nth-child(1) > div > div.max-md\:pb-2.md\:h-auto.md\:max-h-\[inherit\] > div > div.relative.flex.items-center.justify-center"}
  (Session info: chrome=145.0.7632.159); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
	0x7ff7cbdaaa55
	0x7ff7cbb08630
	0x7ff7cb89d75d
	0x7ff7cb8f862e
	0x7ff7cb8f893c
	0x7ff7cb948d87
	0x7ff7cb94591c
	0x7ff7cb8e9098
	0x7ff7cb8e9f83
	0x7ff7cbdd7810
	0x7ff7cbdd1afd
	0x7ff7cbdf2c1a
	0x7ff7cbb23345
	0x7ff7cbb2b81c
	0x7ff7cbb11924
	0x7ff7cbb11ad6
	0x7ff7cbaf7e47
	0x7ffd717ae8d7
	0x7ffd722cc40c

Invalid data (name empty): https://www.pharmacity.vn/vitamin-va-khoang-chat#
[1036/493] Crawling: https://www.pharmacity.vn/nhom-san-pham-giam-cam-ho-so-mui-nguoi-lon.html
Invalid data (name empty): https://www.pharmacity.vn/nhom-san-pham-giam-cam-ho-so-mui-nguoi-lon.html
[1057/493] Crawling: https://www.pharmacity.vn/bot-pha-hon-dich-uong-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-tiet-nieu-cefaclor-250mg-10-goi-x-2ghop.html
Crawled successfully: Bột pha uống Cefaclor 250mg Domesco kháng sinh điều trị nhiễm khuẩn (10 gói x 2g)
[1058/493] Crawling: https://www.pharmacity.vn/oos-by-ncc-spirastad-3-miu.html
Crawled successfully: Viên nén Spirastad 3 M.IU điều trị nhiễm khuẩn đường răng miệng (2 vỉ x 5 viên)
[1059/493] Crawling: https://www.pharmacity.vn/thuoc-dieu-tri-viem-phoi-nhiem-khuan-vung-tieu-avelox-400mg.html
Crawled successfully: Viên nén Avelox 400mg điều trị nhiễm khuẩn (1 vỉ x 5 viên)
[1060/493] Crawling: https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-viem-tai-giua-viem-duong-ho-hap-ceclor-125mg60ml.html
Crawled successfully: Cốm pha uống Ceclor 125mg kháng sinh điều trị nhiễm khuẩn (chai 60ml)
[1061/493] Crawling: https://www.pharmacity.vn/thuoc-du-phong-va-dieu-tri-cac-benh-nhiem-khuan-tinidazol-500mg-1-vi-x-4-vien.html
Crawled successfully: Viên nén Tinidazol 500mg - Domesco điều triị nhiễm khuẩn (1 vỉ x 4 viên)
[1062/493] Crawling: https://www.pharmacity.vn/oos-by-ncc-unasyn-tab-375mg.html
Crawled successfully: Viên nén Unasyn 375mg điều trị nhiễm khuẩn (2 vỉ x 4 viên)
[1063/493] Crawling: https://www.pharmacity.vn/thuoc-du-phong-va-dieu-tri-nhiem-nam-candida-o-da-niem-mac-nystatin-10-vi-x-8-vienhop.html
Crawled successfully: Viên nén bao đường Nystatin 500.000IU trị nấm Candida (10 vỉ x 8 viên)
[1064/493] Crawling: https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-pms-cotrim-960mg-10vi-x10vien.html
Crawled successfully: Viên nén Cotrim 960mg điều trị nhiễm khuẩn (10 vỉ x10 viên)
[1065/493] Crawling: https://www.pharmacity.vn/claminat-250mg3125mg-hop12goi.html
Crawled successfully: Bột pha uống Claminat 250mg/31.25mg điều trị nhiễm khuẩn (12 gói x 1.1g)
[1066/493] Crawling: https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-do-vi-khuan-nhay-cam-erythromycin-500mg-10-vi-x-10-vienhop.html
Crawled successfully: Viên nén Erythromycin 500mg - Vidipha điều trị nhiễm khuẩn đường hô hấp (10 vỉ x 10 viên)
[1067/493] Crawling: https://www.pharmacity.vn/metrogyl-denta.html
Crawled successfully: Gel bôi niêm mạc miệng Metrogyl Denta điều trị viêm nha chu, sâu răng, viêm nướu (tuýp 10g)
[1068/493] Crawling: https://www.pharmacity.vn/vien-nen-flagyl-250mg-dieu-tri-nhiem-khuan-2-vi-x-10-vien.html
Crawled successfully: Viên nén Flagyl 250mg điều trị nhiễm khuẩn (2 vỉ x 10 viên)
[1069/493] Crawling: https://www.pharmacity.vn/itranstad-hop-1-vi-x-6-vien.html
Crawled successfully: Viên nang Itranstad Stella điều trị các bệnh nhiễm nấm (1 vỉ x 6 viên)
[1070/493] Crawling: https://www.pharmacity.vn/klamentin-875125-hop-2-vi-x-7-vien.html
Crawled successfully: Klamentin 1g (2 vỉ x 7 viên) – Kháng sinh mạnh, trị nhiễm khuẩn đa dạng
[1071/493] Crawling: https://www.pharmacity.vn/thuoc-dieu-tri-cac-benh-nhiem-khuan-duong-ho-hap-clamoxyl-250mg.html
Crawled successfully: Bột pha uống Clamoxyl 250mg điều trị nhiễm khuẩn (hộp 12 gói)
[1072/493] Crawling: https://www.pharmacity.vn/klamentin-500625-hop-24-goi-x-2g.html
Crawled successfully: Thuốc cốm pha hỗn dịch uống Klamentin 500mg điều trị nhiễm khuẩn hô hấp (24 gói x 2g)
[1073/493] Crawling: https://www.pharmacity.vn/dieu-tri-nhiem-virus-herpes-ciclevir-800-10-vi-x-5-vienhop.html
Crawled successfully: Viên nén Ciclevir 800 Glomed trị và phòng virus herpes simplex (10 vỉ x 5 viên)
[1074/493] Crawling: https://www.pharmacity.vn/moloxcin-400-hop-1-vi-x-10-vien.html
Crawled successfully: Viên nén Moloxcin 400mg điều trị nhiễm khuẩn (1 vỉ x 10 viên)
[1075/493] Crawling: https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-bactamox-625-12-goi-x-1-6g-hop.html
Crawled successfully: Thuốc cốm pha hỗn dịch uống Bactamox 625mg điều trị nhiễm khuẩn (12 gói x 1.6g)
[1076/493] Crawling: https://www.pharmacity.vn/augbidil-1g-hop-2-vi-x-7-vien.html
Crawled successfully: Viên nén Augbidil 875mg/125mg điều trị nhiễm khuẩn (2 vỉ x 7 viên)
[1077/493] Crawling: https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-nam-spulit-6-vi-x-5-vien-hop.html
Crawled successfully: Viên nang Spulit 100mg Slavia điều trị các bệnh nhiễm nấm (6 vỉ x 5 viên)
[1078/493] Crawling: https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-vigentin-500-62-5mg-dt-2-vi-x-7-vien-hop.html
Crawled successfully: Viên nén phân tán Vigentin 500mg/62,5mg DT điều trị nhiễm khuẩn (2 vỉ x 7 viên)
[1079/493] Crawling: https://www.pharmacity.vn/metiny-375mg-1-vi-x-10-vienhop.html
Crawled successfully: Viên giải phóng có kiểm soát Metiny 375mg kháng sinh điều trị nhiễm khuẩn (1 vỉ x 10 viên)
[1080/493] Crawling: https://www.pharmacity.vn/thuoc-khang-sinh-scd-cefaclor-250mg-2-vi-x-10-vien.html
Crawled successfully: Viên nang SCD Cefaclor 250mg kháng sinh điều trị nhiễm khuẩn (2 vỉ x 10 viên)
[1081/493] Crawling: https://www.pharmacity.vn/naphacogyl-2vi-x-10vien-km.html
Crawled successfully: Viên nén Naphacogyl phòng ngừa và điều trị nhiễm trùng răng miệng (2 vỉ x 10 viên)
[1082/493] Crawling: https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-trung-duong-ho-hap-curam-1000mg-lek-pharmaceuticals-80-vienhop.html
Crawled successfully: Curam 1000mg (10 vỉ x 8 viên) – Kháng sinh mạnh, trị nhiễm khuẩn
[1083/493] Crawling: https://www.pharmacity.vn/cefixim-200mg-cuu-long-2vi-x-10vien.html
Crawled successfully: Viên nén Cefixim 200mg kháng sinh điều trị nhiễm khuẩn (2 vỉ x 10 viên)
[1084/493] Crawling: https://www.pharmacity.vn/curam-250mg5ml-hop-1-chai-x-75g-bot.html
Crawled successfully: Bột pha uống Curam 250mg/5ml điều trị nhiễm khuẩn (chai 7,5g)
[1085/493] Crawling: https://www.pharmacity.vn/acnequidt-20ml.html
Crawled successfully: ACNEQUIDT (Lo 20ml)
[1086/493] Crawling: https://www.pharmacity.vn/nanfizy-100mg-hop-1-vi-x-3-vien.html
Crawled successfully: Viên đặt âm đạo Nanfizy100mg điều trị nhiễm nấm phụ khoa (1 vỉ x 3 viên)
[1087/493] Crawling: https://www.pharmacity.vn/cefpivoxil-400-3-vi-x-10-vienhop.html
Crawled successfully: Cefpivoxil400 400mg (Hộp 3 vỉ x 10 viên)
[1088/493] Crawling: https://www.pharmacity.vn/thuoc-dieu-tri-nhiem-khuan-rovas-0-75m-24-goi-x-3g-hop.html
Crawled successfully: Bột pha uống Rovas 0.75M IU DHG điều trị nhiễm khuẩn đường hô hấp (hộp 24 gói)
[1089/493] Crawling: https://www.pharmacity.vn/emycindhg-250-hop-24-goi-x-15g.html
Crawled successfully: Bột pha uống Emycin 250mg DHG điều trị nhiễm khuẩn đường hô hấp (hộp 24 gói)
[1090/493] Crawling: https://www.pharmacity.vn/biocemet-500625-2-vi-x-7-vienhop.html
Crawled successfully: Viên nén phân tán Biocemet DT 500mg/62.5mg Imexpharm điều trị nhiễm khuẩn (2 vỉ x 7 viên)
[1091/493] Crawling: https://www.pharmacity.vn/imeclor-125-12-goi-x-25ghop.html
Crawled successfully: Thuốc cốm pha hỗn dịch uống Imeclor 125mg Imexpharm kháng sinh điều trị nhiễm khuẩn (hộp 12 gói)
[1092/493] Crawling: https://www.pharmacity.vn/tenfovix-hop-3x10.html
Crawled successfully: Viên nén Tenfovix điều trị nhiễm HIV, viêm gan siêu vi B  (3 vỉ x 10 viên)
[1093/493] Crawling: https://www.pharmacity.vn/candisafe-hop-1-vi-x-7-vien.html
Crawled successfully: Candisafe (Hộp 1 vỉ x 7 viên)
[1094/493] Crawling: https://www.pharmacity.vn/nirdicin-250mg-hop-10-vien-pharmathen.html
Crawled successfully: Nirdicin 250MG Pharmathen (Hộp 10 viên)
[1095/493] Crawling: https://www.pharmacity.vn/griseofulvin-tab-500mg-box-100.html
Crawled successfully: Viên nén Griseofulvin 500mg Vidipha điều trị nấm da, tóc, lông, móng (10 vỉ x 10 viên)
[1096/493] Crawling: https://www.pharmacity.vn/cefpodoxim-100-hv-usp-hop-10-goi.html
Crawled successfully: Cefpodoxim 100-HV USP (Hộp 10 gói)
[1097/493] Crawling: https://www.pharmacity.vn/uphaxime-200mg-1vix10vien.html
Crawled successfully: Viên nang Uphaxime 200mg kháng sinh điều trị nhiễm khuẩn (1 vỉ x 10 viên)
[1098/493] Crawling: https://www.pharmacity.vn/cefdinir-300-hv-hop-2-vi-x-10-vien-nang-cung.html
Crawled successfully: Viên nang Cefdinir 300 - HV điều trị nhiễm khuẩn (2 vỉ x 10 viên)
[1099/493] Crawling: https://www.pharmacity.vn/zelfamox-tab-dt-500mg125-2vix7vien.html
Crawled successfully: ZELFAMOX TAB DT 500MG/125 (2vix7vien)
[1100/493] Crawling: https://www.pharmacity.vn/clarisol-500mg-hop-10-vien.html
Crawled successfully: Viên nén Clarisol 500mg điều trị nhiễm khuẩn đường hô hấp (1 vỉ x 10 viên)
[1101/493] Crawling: https://www.pharmacity.vn/aziphar-susp-dry-200mg5ml-15ml.html
Crawled successfully: Bột pha uống Aziphar 200mg/5ml điều trị nhiễm khuẩn đường hô hấp (chai 15ml)
[1102/493] Crawling: https://www.pharmacity.vn/cefuroxim-500mg-1-vi-x-10-vien-vpc.html
Crawled successfully: Cefuroxim VPC 500mg (1 vỉ x 10 Viên)
[1103/493] Crawling: https://www.pharmacity.vn/alfavir-tablet-incepta-10-vien.html
Crawled successfully: Thuốc Alfavir Tablet Incepta điều trị viêm gan B mạn tính (1 vỉ x 10 viên)
[1104/493] Crawling: https://www.pharmacity.vn/levofloxacin-kabi-100ml.html
Crawled successfully: Dịch tiêm truyền Levofloxacin Kabi 100ml Fresenius Kabi điều trị nhiễm khuẩn, viêm phổi
[1105/493] Crawling: https://www.pharmacity.vn/ciprofloxacin-kabi-200mg-chai-100ml.html
Crawled successfully: Ciprofloxacin Kabi 200mg (Chai 100ml)
[1106/493] Crawling: https://www.pharmacity.vn/augbidil-625-h14.html
Crawled successfully: Viên nén Augbidil 625 điều trị nhiễm khuẩn (2 vỉ x14 viên)
[1107/493] Crawling: https://www.pharmacity.vn/agi-cotrim-960mg-hop-100-vien.html
Crawled successfully: Viên nén AGI-COTRIM 960MG điều trị nhiễm khuẩn (10 vỉ x 10 viên)
[1108/493] Crawling: https://www.pharmacity.vn/denvin-300mg-hop-2-vi-x-10-vien.html
Crawled successfully: Viên nang Denvin 300mg kháng sinh điều trị nhiễm khuẩn (2 vỉ x 10 viên)
[1109/493] Crawling: https://www.pharmacity.vn/griseofulvin-500mg10-vi-x10-vien.html
Crawled successfully: Viên nén Griseofulvin 500mg Cửu Long điều trị nấm da, tóc, lông, móng (10 vỉ x10 viên)
[1110/493] Crawling: https://www.pharmacity.vn/acigmentin-1000mg-2vi-x-7-vien.html
Crawled successfully: Viên nén Acigmentin 1000mg điều trị nhiễm khuẩn (2 vỉ x 7 viên)
[1111/493] Crawling: https://www.pharmacity.vn/gentamicin-kabi-80mg2ml-hop-100-ong.html
Crawled successfully: Gentamicin Kabi 80mg/2ml ( Hop 100 Ong)
[1112/493] Crawling: https://www.pharmacity.vn/bot-pha-hon-dich-uong-augmentin-es-gsk-50ml.html
Crawled successfully: Bột pha hỗn dịch uống Augmentin ES GSK điều trị các nhiễm trùng do vi khuẩn gây ra ở trẻ (50ml)
[1113/493] Crawling: https://www.pharmacity.vn/rx-thuoc-khang-sinh#

In [19]:
# Kiểm tra file đã recrawled
recrawled_df = pd.read_csv("pharmacity_medicines_recrawled.csv")
print(f"Recrawled DataFrame: {len(recrawled_df)} records")
recrawled_df.head()

Recrawled DataFrame: 454 records

,name,price,images,nha_san_xuat,noi_san_xuat,thuoc_can_ke_don,hoat_chat,chi_dinh_tom_tat,dang_bao_che,quy_cach,...,mo_ta,thanh_phan,chi_dinh_chi_tiet,huong_dan_su_dung,cach_su_dung,than_trong,thong_tin_san_xuat,url,drug_type,category_link
0,Viên nén Desloratadine 5mg trị viêm mũi dị ứng...,NaN,['https://prod-cdn.pharmacity.io/e-com/images/...,Genepharm.SA,Greece,Không,Desloratadin 5mg,"Điều trị Viêm mũi dị ứng, mày đay, ngứa",Viên nén bao phim,2 vỉ x 15 viên,...,Thành phần của Thuốc Desloratadine 5mg\n\nHoạt...,Công dụng của Thuốc Desloratadine 5mg\nChỉ địn...,Cách sử dụng\nCách dùng\n\nViên nén dùng theo ...,Tác dụng phụ\nDesloratadine thường được dung n...,NaN,"Bảo quản\nBảo quản thuốc trong bao bì kín, nơi...",NaN,https://www.pharmacity.vn/desloratadine-5mg-ho...,NaN,NaN
1,Azicine Stella 500mg điều trị các trường hợp n...,NaN,['https://prod-cdn.pharmacity.io/e-com/images/...,STELLA,NaN,NaN,Azithromycin (dưới dạng azithromycin dihydrate),Điều trị các trường hợp nhiễm khuẩn gây ra bởi...,Viên nén bao phim,Hộp 6 viên,...,NaN,Chỉ định (Thuốc dùng cho bệnh gì?)\nĐiều trị c...,Hướng dẫn sử dụng\nLiều dùng\nNgười lớn và trẻ...,Chống chỉ định (Khi nào không nên dùng thuốc n...,NaN,"Thông tin sản xuất\nBảo quản: Nơi khô, nhiệt đ...",NaN,https://www.pharmacity.vn/azicine-500-stella-1...,NaN,NaN
2,Viên nang Kodemin trị ho khan do kích thích (1...,NaN,['https://prod-cdn.pharmacity.io/e-com/images/...,Duoc VTYT Hai Duong,NaN,NaN,Codein phosphat; Guaifenesin,Điều trị ho khan do kích thích,Viên nang mềm,10 vỉ x 10 viên,...,Thành phần Viên nang Kodemin\n\nCodein phospha...,Công dụng của Viên nang Kodemin\nChỉ định (Thu...,Cách sử dụng Viên nang Kodemin\nLiều dùng và c...,Tác dụng phụ của Viên nang Kodemin\nThường gặp...,NaN,Thông tin sản xuất của Viên nang Kodemin\nThươ...,NaN,https://www.pharmacity.vn/kodemin-softcap-10vi...,NaN,NaN
3,"Viên nang A.T Arginin 200mg hạ men gan, tăng c...",NaN,['https://prod-cdn.pharmacity.io/e-com/images/...,An Thien,NaN,NaN,Arginin hydroclorid 200mg,Hỗ trợ điều trị các rối loạn khó tiêu,Viên nang,Chai 85ml,...,NaN,Chỉ định (Thuốc dùng cho bệnh gì?)\n- Điều trị...,Liều dùng \n- Điều trị duy trì tăng amoniac má...,Chống chỉ định (Khi nào không nên dùng thuốc n...,NaN,"Thông tin sản xuất\nBảo quản: Nơi khô, nhiệt đ...",NaN,https://www.pharmacity.vn/at-arginin-200mg-10-...,NaN,NaN
4,Bột pha tiêm Neutrivit 5000 Bidiphar viêm dây ...,NaN,['https://prod-cdn.pharmacity.io/e-com/images/...,BIDIPHAR,NaN,Không,Vitamin B1;Vitamin B6;Vitamin B12,"Viêm dây thần kinh, đau thần kinh tọa, thiếu v...",Bột đông khô pha tiêm,4 lọ bột + 4 ống dung môi,...,NaN,Công dụng của Bột pha tiêm Neutrivit 5000\n\n...,Cách dùng Bột pha tiêm Neutrivit 5000\n\nCách ...,Tác dụng phụ\n\nKhi sử dụng thuốc Neutrivit 50...,NaN,"Bảo quản\n\nNơi mát, nhiệt độ < 30°C, kín, trá...",NaN,https://www.pharmacity.vn/neutrivit-5000-bidip...,NaN,NaN

In [20]:
# Kiểm tra xem cột name có giá trị none hoặc rỗng không
invalid_name = recrawled_df['name'].astype(str).str.strip().str.lower().eq('none') | recrawled_df['name'].isna() | recrawled_df['name'].astype(str).str.strip().eq('')
invalid_name_rows = recrawled_df[invalid_name]
print(f"Số dòng có name bị lỗi none hoặc rỗng: {len(invalid_name_rows)}")
invalid_name_rows.head()

Số dòng có name bị lỗi none hoặc rỗng: 0

Empty DataFrame
Columns: [name, price, images, nha_san_xuat, noi_san_xuat, thuoc_can_ke_don, hoat_chat, chi_dinh_tom_tat, dang_bao_che, quy_cach, luu_y, mo_ta, thanh_phan, chi_dinh_chi_tiet, huong_dan_su_dung, cach_su_dung, than_trong, thong_tin_san_xuat, url, drug_type, category_link]
Index: []

[0 rows x 21 columns]

In [21]:
# Kiểm tra file still_error
still_error_df = pd.read_csv("pharmacity_medicines_still_error.csv")
print(f"Still Error DataFrame: {len(still_error_df)} records")
still_error_df.head()

Still Error DataFrame: 39 records

,name,price,images,nha_san_xuat,noi_san_xuat,thuoc_can_ke_don,hoat_chat,chi_dinh_tom_tat,dang_bao_che,quy_cach,...,huong_dan_su_dung,cach_su_dung,than_trong,thong_tin_san_xuat,url,category,drug_type,category_link,category_name,error
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/thuoc-cam-lanh#,NaN,NaN,NaN,NaN,Message: no such element: Unable to locate ele...
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/nasol-spray-chai-70m...,NaN,NaN,NaN,NaN,Message: no such element: Unable to locate ele...
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/tinh-dau-tre-em-naso...,NaN,NaN,NaN,NaN,Message: no such element: Unable to locate ele...
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/nhom-san-pham-giam-d...,NaN,NaN,NaN,NaN,Message: no such element: Unable to locate ele...
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/thuoc-da-lieu#,NaN,NaN,NaN,NaN,Message: no such element: Unable to locate ele...

In [22]:
# Kiểm tra cột name trong still_error_df
invalid_name_still_error = still_error_df['name'].astype(str).str.strip().str.lower().eq('none') | still_error_df['name'].isna() | still_error_df['name'].astype(str).str.strip().eq('')
invalid_name_still_error_rows = still_error_df[invalid_name_still_error]
print(f"Số dòng có name bị lỗi none hoặc rỗng trong still_error: {len(invalid_name_still_error_rows)}")

# Kiểm tra cột name trong still_error_df có giá trị none hoặc rỗng và các cột khác vẫn có dữ liệu
valid_still_error_rows = still_error_df[~invalid_name_still_error]
print(f"Số dòng có name hợp lệ trong still_error: {len(valid_still_error_rows)}")
valid_still_error_rows.head()

Số dòng có name bị lỗi none hoặc rỗng trong still_error: 39
Số dòng có name hợp lệ trong still_error: 0

Empty DataFrame
Columns: [name, price, images, nha_san_xuat, noi_san_xuat, thuoc_can_ke_don, hoat_chat, chi_dinh_tom_tat, dang_bao_che, quy_cach, luu_y, mo_ta, thanh_phan, chi_dinh_chi_tiet, huong_dan_su_dung, cach_su_dung, than_trong, thong_tin_san_xuat, url, category, drug_type, category_link, category_name, error]
Index: []

[0 rows x 24 columns]