In [1]:
import pandas as pd
import numpy as np

In [2]:
df_fixed = pd.read_csv("pharmacity_medicines_recrawled_fixed.csv")
print(df_fixed.shape)
df_fixed.head()

(477, 21)

,name,price,images,nha_san_xuat,noi_san_xuat,thuoc_can_ke_don,hoat_chat,chi_dinh_tom_tat,dang_bao_che,quy_cach,...,mo_ta,thanh_phan,chi_dinh_chi_tiet,huong_dan_su_dung,cach_su_dung,than_trong,thong_tin_san_xuat,url,drug_type,category_link
0,Thuốc xịt mũi Nasol Spray giảm triệu chứng ngh...,30.000 ₫/Chai,['https://prod-cdn.pharmacity.io/e-com/images/...,RELIV HEALTHCARE,NaN,NaN,Natri Clorid 630mg,"Giảm triệu chứng nghẹt mũi, sổ mũi, Viêm mũi d...",Thuốc xịt mũi,Chai 70ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/nasol-spray-chai-70m...,NaN,NaN
1,Thuốc xịt mũi Nasomom 4 Tinh dầu trẻ em giảm s...,39.000 ₫/Chai,['https://prod-cdn.pharmacity.io/e-com/images/...,RELIV HEALTHCARE,NaN,NaN,Natri Clorid 630mg,"Giảm triệu chứng nghẹt mũi, sổ mũi, Viêm mũi d...",Tinh dầu xịt mũi,Chai 70ml,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/tinh-dau-tre-em-naso...,NaN,NaN
2,Nhóm sản phẩm giảm đau dạ dày cho người lớn,220.900 ₫/Bộ,['https://prod-cdn.pharmacity.io/e-com/images/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/nhom-san-pham-giam-d...,NaN,NaN
3,Thuốc dùng ngoài Bacterocin điều trị tại chỗ b...,47.000 ₫/Tuýp,['https://prod-cdn.pharmacity.io/e-com/images/...,Genuone Sciences Inc.,NaN,Không,Mupirocin,"Bệnh chốc lở, viêm nang lông và mụn mủ do Stap...",Thuốc mỡ,NaN,...,NaN,Công Dụng\nChỉ định\nThuốc Bacterocin Oint chỉ...,NaN,Tác dụng phụ\n\nCác tác dụng không mong muốn k...,NaN,NaN,NaN,https://www.pharmacity.vn/bacterocin-5g.html,NaN,NaN
4,Thuốc dùng ngoài Bacterocin điều trị tại chỗ b...,105.000 ₫/Tuýp,['https://prod-cdn.pharmacity.io/e-com/images/...,Genuone Sciences Inc.,Viet Nam,Không,Mupirocin,"Chốc lở, viêm nang lông và mụn mủ do S.aureus ...",Thuốc mỡ,Tuýp 15g,...,NaN,Công dụng\nChỉ định\nThuốc Bacterocin Oint chỉ...,NaN,Tác dụng phụ\nCác tác dụng không mong muốn khi...,NaN,NaN,NaN,https://www.pharmacity.vn/bacterocin-15g.html,NaN,NaN

In [3]:
df_base = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicines_data_demo(9).csv")
print(df_base.shape)
df_base.head()

(3568, 24)

,name,price,images,nha_san_xuat,noi_san_xuat,thuoc_can_ke_don,hoat_chat,chi_dinh_tom_tat,dang_bao_che,quy_cach,...,huong_dan_su_dung,cach_su_dung,than_trong,thong_tin_san_xuat,url,category,drug_type,category_link,category_name,error
0,Viên nén Postinor 1 (Hộp 1 viên) - Ngừa thai k...,40.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Gedeon Richter,Hungary,Không,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,1 vỉ X 1 viên,...,"Tác dụng phụ\n\nKhi sử dụng thuốc Postinor 1, ...",NaN,Thông tin sản xuất\nBảo quản: Bảo quản nơi khô...,NaN,https://www.pharmacity.vn/vien-nen-postinor-1-...,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
1,Cerciorat Leon Farma (Hộp 1 vỉ x 1 viên) – Trá...,35.990 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,EXELTIS PHARMA,Spain,Không,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,1 vỉ X 1 viên,...,Thận trọng khi dùng thuốc\nChống chỉ định (Khi...,NaN,Thông tin sản xuất\nBảo quản: Ở nhiệt độ dưới ...,NaN,https://www.pharmacity.vn/cerciorat-hop-1-vi-x...,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
2,Viên nén BOCINOR 1.5MG thuốc tránh thai khẩn c...,9.500 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Ba Đình,NaN,NaN,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,1 vỉ X 1 viên,...,Tác dụng phụ\nQuá liều và cách xử trí\n\nCác t...,NaN,"Thông tin sản xuất\nBảo quản: Nơi khô ráo, trá...",NaN,https://www.pharmacity.vn/bocinor-tab-15mg-hop...,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
3,Avalo day (Hộp 28 viên),25.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,CT CP hóa dược VN,NaN,Không,Levonorgestrel,Thuốc tránh thai,Viên nén,Hộp 1 Vỉ x 28 Viên,...,Tác dụng phụ\nChống chỉ địnhMang thai hoặc ngh...,NaN,NaN,NaN,https://www.pharmacity.vn/avalo-day-hop-28-vie...,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
4,Newlevo 0.03mg (1 vỉ x 28 viên),8.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Ba Dinh Pharma,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,https://www.pharmacity.vn/newlevo.html,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN

In [4]:
# Chuẩn hóa url
for df in [df_fixed, df_base]:
    df['url'] = df['url'].astype(str).str.strip()

In [5]:
# Loại trùng
df_fix = df_fixed.drop_duplicates(subset='url',keep='last')

In [6]:
# Xác định các url có lỗi trong df_base
name_col = df_base['name'].astype(str).str.strip().str.lower()
error_mask = df_base['name'].isna() | name_col.isin(['none', 'nan', ''])
error_urls = set(df_base.loc[error_mask, 'url'])

In [7]:
df_fix_target = df_fix[df_fix['url'].isin(error_urls)].copy()
base_idx = df_base.set_index('url')
fix_idx = df_fix_target.set_index('url')

In [9]:
replace_cols = [c for c in fix_idx.columns if c in base_idx.columns]
match_urls = base_idx.index.intersection(fix_idx.index)

In [10]:
base_idx.loc[match_urls, replace_cols] = fix_idx.loc[match_urls, replace_cols]
df_merged = base_idx.reset_index()
df_merged.to_csv("pharmacity_medicines_data_merged.csv", index=False)

In [14]:
new_name_col = df_merged['name'].astype(str).str.strip().str.lower()
remaining_error = df_merged['name'].isna() | new_name_col.isin(['none', 'nan', ''])

print(f"Tổng dòng gốc: {len(df_base)}")
print(f"Số URL lỗi ban đầu: {len(error_urls)}")
print(f"Số URL fix match và đã thay: {len(match_urls)}")
print(f"Số dòng còn lỗi sau thay: {remaining_error.sum()}")
print(f"Đã lưu: pharmacity_medicines_data_merged.csv")

Tổng dòng gốc: 3568
Số URL lỗi ban đầu: 493
Số URL fix match và đã thay: 477
Số dòng còn lỗi sau thay: 16
Đã lưu: pharmacity_medicines_data_merged.csv

In [15]:
df_merged.head()

,url,name,price,images,nha_san_xuat,noi_san_xuat,thuoc_can_ke_don,hoat_chat,chi_dinh_tom_tat,dang_bao_che,...,chi_dinh_chi_tiet,huong_dan_su_dung,cach_su_dung,than_trong,thong_tin_san_xuat,category,drug_type,category_link,category_name,error
0,https://www.pharmacity.vn/vien-nen-postinor-1-...,Viên nén Postinor 1 (Hộp 1 viên) - Ngừa thai k...,40.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Gedeon Richter,Hungary,Không,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,...,Cách dùng viên nén Postinor 1\nCách dùng\nDùng...,"Tác dụng phụ\n\nKhi sử dụng thuốc Postinor 1, ...",NaN,Thông tin sản xuất\nBảo quản: Bảo quản nơi khô...,NaN,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
1,https://www.pharmacity.vn/cerciorat-hop-1-vi-x...,Cerciorat Leon Farma (Hộp 1 vỉ x 1 viên) – Trá...,35.990 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,EXELTIS PHARMA,Spain,Không,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,...,Liều dùng và cách dùng \nLiều dùng\n\nUống 1 v...,Thận trọng khi dùng thuốc\nChống chỉ định (Khi...,NaN,Thông tin sản xuất\nBảo quản: Ở nhiệt độ dưới ...,NaN,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
2,https://www.pharmacity.vn/bocinor-tab-15mg-hop...,Viên nén BOCINOR 1.5MG thuốc tránh thai khẩn c...,9.500 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Ba Đình,NaN,NaN,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,...,Cách dùng Viên nén BOCINOR 1.5MG\nLiều dùng\n\...,Tác dụng phụ\nQuá liều và cách xử trí\n\nCác t...,NaN,"Thông tin sản xuất\nBảo quản: Nơi khô ráo, trá...",NaN,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
3,https://www.pharmacity.vn/avalo-day-hop-28-vie...,Avalo day (Hộp 28 viên),25.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,CT CP hóa dược VN,NaN,Không,Levonorgestrel,Thuốc tránh thai,Viên nén,...,NaN,Tác dụng phụ\nChống chỉ địnhMang thai hoặc ngh...,NaN,NaN,NaN,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
4,https://www.pharmacity.vn/newlevo.html,Newlevo 0.03mg (1 vỉ x 28 viên),8.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Ba Dinh Pharma,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN

In [17]:
# Tìm số dòng còn thiếu category
missing_category = df_merged['category_name'].isna().sum()
print(f"Số dòng còn thiếu category: {missing_category}")

Số dòng còn thiếu category: 469

In [20]:
# Đọc lại file link và bổ sung các dòng thiếu category
df_link = pd.read_csv(r"D:\OU\KhoaLuanTotNghiep\DrugRecommandation\crawlData_Pharmacity\pharmacity_medicine_links.csv")
df_link = df_link.copy()

df_add_category = df_link[df_link['links'].isin(df_merged['url'])][['links', 'category_name']].drop_duplicates(subset='links')
df_final = pd.merge(df_merged, df_add_category, left_on='url', right_on='links', how='left', suffixes=('', '_new'))
df_final['category_name'] = df_final['category_name'].combine_first(df_final['category_name_new'])
df_final.drop(columns=['category_name_new', 'links'], inplace=True)
df_final.to_csv("pharmacity_medicines_data_final.csv", index=False)

In [21]:
df_new = pd.read_csv("pharmacity_medicines_data_final.csv")
print(df_new.shape)
df_new.head()

(3568, 24)

,url,name,price,images,nha_san_xuat,noi_san_xuat,thuoc_can_ke_don,hoat_chat,chi_dinh_tom_tat,dang_bao_che,...,chi_dinh_chi_tiet,huong_dan_su_dung,cach_su_dung,than_trong,thong_tin_san_xuat,category,drug_type,category_link,category_name,error
0,https://www.pharmacity.vn/vien-nen-postinor-1-...,Viên nén Postinor 1 (Hộp 1 viên) - Ngừa thai k...,40.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Gedeon Richter,Hungary,Không,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,...,Cách dùng viên nén Postinor 1\nCách dùng\nDùng...,"Tác dụng phụ\n\nKhi sử dụng thuốc Postinor 1, ...",NaN,Thông tin sản xuất\nBảo quản: Bảo quản nơi khô...,NaN,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
1,https://www.pharmacity.vn/cerciorat-hop-1-vi-x...,Cerciorat Leon Farma (Hộp 1 vỉ x 1 viên) – Trá...,35.990 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,EXELTIS PHARMA,Spain,Không,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,...,Liều dùng và cách dùng \nLiều dùng\n\nUống 1 v...,Thận trọng khi dùng thuốc\nChống chỉ định (Khi...,NaN,Thông tin sản xuất\nBảo quản: Ở nhiệt độ dưới ...,NaN,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
2,https://www.pharmacity.vn/bocinor-tab-15mg-hop...,Viên nén BOCINOR 1.5MG thuốc tránh thai khẩn c...,9.500 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Ba Đình,NaN,NaN,LEVONORGESTREL,Thuốc tránh thai khẩn cấp trong vòng 72 giờ,Viên nén,...,Cách dùng Viên nén BOCINOR 1.5MG\nLiều dùng\n\...,Tác dụng phụ\nQuá liều và cách xử trí\n\nCác t...,NaN,"Thông tin sản xuất\nBảo quản: Nơi khô ráo, trá...",NaN,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
3,https://www.pharmacity.vn/avalo-day-hop-28-vie...,Avalo day (Hộp 28 viên),25.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,CT CP hóa dược VN,NaN,Không,Levonorgestrel,Thuốc tránh thai,Viên nén,...,NaN,Tác dụng phụ\nChống chỉ địnhMang thai hoặc ngh...,NaN,NaN,NaN,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN
4,https://www.pharmacity.vn/newlevo.html,Newlevo 0.03mg (1 vỉ x 28 viên),8.000 ₫/Hộp,['https://prod-cdn.pharmacity.io/e-com/images/...,Ba Dinh Pharma,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Thuốc ngừa thai,Thuốc không kê đơn,https://www.pharmacity.vn/thuoc-ngua-thai,Thuốc ngừa thai,NaN

In [22]:
# Kiểm tra còn dòng nào thiếu category không
missing_category_after = df_new['category_name'].isna().sum()
print(f"Số dòng còn thiếu category sau bổ sung: {missing_category_after}")

Số dòng còn thiếu category sau bổ sung: 0